// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// A record stored as a <see cref="Godot.Collections.Dictionary"/>.
/// </summary>
public sealed class DictionaryRecord : NetwRecord
{
    public DictionaryRecord(IntPtr native) : base(native)
    {
    }

    public new static DictionaryRecord Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new DictionaryRecord(native);
    }

    public new static DictionaryRecord From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    private static readonly IntPtr _bindGetData =
        NetwApi.MethodBind("DictionaryRecord", "get_data", 3102165223UL);

    private static readonly IntPtr _bindSetData =
        NetwApi.MethodBind("DictionaryRecord", "set_data", 4155329257UL);

    /// <summary>
    /// The values of this record.
    /// </summary>
    public Godot.Collections.Dictionary Data
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetData, Checked, ref answered);
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromDictionary(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetData, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }
}
