// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// A <see cref="NetwDatabaseBackend"/> that keeps records in files under one
/// directory.
/// </summary>
/// <remarks>
/// Records outlive the process, so this is the backend a shipped single player
/// or listen server game saves into.
/// <code>
/// var backend := FileSystemDatabase.new()
/// backend.root = "user://saves"
/// Netw.configure_database(self, &amp;"saves").backend(backend)
/// </code>
/// <para>
/// Each slot is a directory under <see cref="FileSystemDatabase.Root"/>, and
/// each record is one file inside it. A record is replaced by writing a new
/// file beside it and renaming over the target, so a write that fails partway
/// leaves the previous record readable rather than a half-written one. A file
/// this library did not write is reported as present and refused as
/// unrecognized. It is never read as an empty save and it is never overwritten
/// by the read that found it. <c>NetwDatabaseBackend._list_slots</c> reads
/// <see cref="FileSystemDatabase.Root"/> itself, so a slot written by an
/// earlier run of the game appears without being opened first.
/// </para>
/// </remarks>
public sealed class FileSystemDatabase : NetwDatabaseBackend
{
    public FileSystemDatabase(IntPtr native) : base(native)
    {
    }

    public new static FileSystemDatabase Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new FileSystemDatabase(native);
    }

    public new static FileSystemDatabase From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    private static readonly IntPtr _bindGetRoot =
        NetwApi.MethodBind("FileSystemDatabase", "get_root", 201670096UL);

    private static readonly IntPtr _bindSetRoot =
        NetwApi.MethodBind("FileSystemDatabase", "set_root", 83702148UL);

    /// <summary>
    /// The directory every slot lives under. A path under <c>user://</c> is the
    /// one a shipped game can write to on every platform.
    /// </summary>
    public string Root
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetRoot, Checked, ref answered);
            string result = VariantUtils.ConvertToString(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromString(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetRoot, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }
}
