// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// A node that gives its children their own <see cref="NetwMultiplayer"/>.
/// </summary>
/// <remarks>
/// Every child's <see cref="Node.Multiplayer"/> is this tree's
/// <see cref="MultiplayerTree.Api"/>, as with <c>SceneTree.set_multiplayer</c>.
/// Two trees in one <see cref="SceneTree"/> are two separate sessions, such as
/// a server and a client in one process.
/// <code>
/// tree.peer_class = &amp;"ENetMultiplayerPeer"
/// tree.transport_settings = { port = 21253 }
///
/// # assign a peer as usual
/// var peer := ENetMultiplayerPeer.new()
/// peer.create_client("127.0.0.1", 21253)
/// tree.api.session_prepare_join(&amp;"PlayerOne", [])
/// tree.api.multiplayer_peer = peer
///
/// # or let the transport create it
/// Netw.connection(tree).create_peer(
///     tree.peer_class,
///     NetwMultiplayer.TRANSPORT_MODE_CLIENT,
///     "127.0.0.1:21253",
///     tree.transport_settings,
///     func(peer: MultiplayerPeer, error: Error, _detail: String) -&gt; void:
///         if error == OK:
///             tree.api.session_prepare_join(&amp;"PlayerOne", [])
///             tree.api.multiplayer_peer = peer,
/// )
/// </code>
/// </remarks>
public sealed class MultiplayerTree : NetwObject
{
    public MultiplayerTree(IntPtr native) : base(native, owned: false)
    {
    }

    public static MultiplayerTree Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new MultiplayerTree(native);
    }

    public static MultiplayerTree From(Variant value)
    {
        return Adopt(NetwApi.ObjectOf(value));
    }

    private static readonly IntPtr _bindGetPeerClass =
        NetwApi.MethodBind("MultiplayerTree", "get_peer_class", 2002593661UL);

    private static readonly IntPtr _bindSetPeerClass =
        NetwApi.MethodBind("MultiplayerTree", "set_peer_class", 3304788590UL);

    /// <summary>
    /// The <see cref="MultiplayerPeer"/> class to use, such as
    /// <c>&amp;"ENetMultiplayerPeer"</c>.
    /// </summary>
    public StringName PeerClass
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetPeerClass, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetPeerClass,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetTransportSettings =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "get_transport_settings",
            3102165223UL);

    private static readonly IntPtr _bindSetTransportSettings =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "set_transport_settings",
            4155329257UL);

    /// <summary>
    /// The settings for creating a <see cref="MultiplayerTree.PeerClass"/>
    /// peer, such as <c>{ port = 21253 }</c> for ENet.
    /// </summary>
    public Godot.Collections.Dictionary TransportSettings
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetTransportSettings, Checked, ref answered);
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromDictionary(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetTransportSettings,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetLinkConditions =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "get_link_conditions",
            2266514204UL);

    private static readonly IntPtr _bindSetLinkConditions =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "set_link_conditions",
            1089193088UL);

    /// <summary>
    /// Simulated latency and packet loss for testing.
    /// </summary>
    public NetwLinkConditions LinkConditions
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(
                _bindGetLinkConditions,
                Checked,
                ref answered);
            return NetwLinkConditions.Adopt(answered);
        }
        set
        {
            IntPtr slot0 = value?.Native ?? IntPtr.Zero;
            long discarded = default;
            NetwThunks.Ptrcall1_IntPtr_Long(
                _bindSetLinkConditions,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetAutoHostHeadless =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "get_auto_host_headless",
            36873697UL);

    private static readonly IntPtr _bindSetAutoHostHeadless =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "set_auto_host_headless",
            2586408642UL);

    /// <summary>
    /// When running headless, hosts at startup with
    /// <see cref="MultiplayerTree.PeerClass"/> and
    /// <see cref="MultiplayerTree.TransportSettings"/>.
    /// </summary>
    public bool AutoHostHeadless
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetAutoHostHeadless,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetAutoHostHeadless,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetDesiredRole =
        NetwApi.MethodBind("MultiplayerTree", "get_desired_role", 2901618068UL);

    private static readonly IntPtr _bindSetDesiredRole =
        NetwApi.MethodBind("MultiplayerTree", "set_desired_role", 3233627807UL);

    /// <summary>
    /// The role this tree takes when it hosts.
    /// </summary>
    public NetwMultiplayer.RoleEnum DesiredRole
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetDesiredRole,
                Checked,
                ref answered);
            return (NetwMultiplayer.RoleEnum)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetDesiredRole,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetAppId =
        NetwApi.MethodBind("MultiplayerTree", "get_app_id", 2002593661UL);

    private static readonly IntPtr _bindSetAppId =
        NetwApi.MethodBind("MultiplayerTree", "set_app_id", 3304788590UL);

    /// <summary>
    /// The game and build. Peers with a different
    /// <see cref="MultiplayerTree.AppId"/> cannot connect. See
    /// <see cref="NetwSessionConfig.AppId"/>.
    /// </summary>
    public StringName AppId
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetAppId, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetAppId, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetDebugJoin =
        NetwApi.MethodBind("MultiplayerTree", "get_debug_join", 4195371391UL);

    private static readonly IntPtr _bindSetDebugJoin =
        NetwApi.MethodBind("MultiplayerTree", "set_debug_join", 2720545769UL);

    /// <summary>
    /// Connects automatically when the game runs, in debug builds only.
    /// </summary>
    public DebugJoinConfig DebugJoin
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(
                _bindGetDebugJoin,
                Checked,
                ref answered);
            return DebugJoinConfig.Adopt(answered);
        }
        set
        {
            IntPtr slot0 = value?.Native ?? IntPtr.Zero;
            long discarded = default;
            NetwThunks.Ptrcall1_IntPtr_Long(
                _bindSetDebugJoin,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetApiScript =
        NetwApi.MethodBind("MultiplayerTree", "get_api_script", 278624046UL);

    private static readonly IntPtr _bindSetApiScript =
        NetwApi.MethodBind("MultiplayerTree", "set_api_script", 3657522847UL);

    /// <summary>
    /// An optional script extending <see cref="NetwMultiplayer"/>, used for
    /// <see cref="MultiplayerTree.Api"/>.
    /// </summary>
    public Script ApiScript
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetApiScript, Checked, ref answered);
            Script result = (Script)VariantUtils.ConvertToGodotObject(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            IntPtr slot0 = value?.NativeInstance ?? IntPtr.Zero;
            long discarded = default;
            NetwThunks.Ptrcall1_IntPtr_Long(
                _bindSetApiScript,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetApi =
        NetwApi.MethodBind("MultiplayerTree", "get_api", 208707294UL);

    /// <summary>
    /// The <see cref="NetwMultiplayer"/> of this tree's children.
    /// </summary>
    public NetwMultiplayer Api
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(_bindGetApi, Checked, ref answered);
            return NetwMultiplayer.Adopt(answered);
        }
    }

    private static readonly IntPtr _bindRaiseEmbeddedServer =
        NetwApi.MethodBind(
            "MultiplayerTree",
            "raise_embedded_server",
            2727226692UL);

    /// <summary>
    /// Duplicates this tree as a sibling named <c>Server</c>, with the role
    /// <see cref="NetwMultiplayer.RoleEnum.DedicatedServer"/>.
    /// <code>
    /// var server := tree.raise_embedded_server()
    /// var peer := ENetMultiplayerPeer.new()
    /// peer.create_server(21253)
    /// server.api.multiplayer_peer = peer
    /// </code>
    /// </summary>
    public MultiplayerTree RaiseEmbeddedServer()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(
            _bindRaiseEmbeddedServer,
            Checked,
            ref answered);
        return MultiplayerTree.Adopt(answered);
    }
}
