// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// A predicted discrete action bound to one authority method.
/// </summary>
/// <remarks>
/// Pairs a local <see cref="NetwAction.Predict"/> effect with a reliable server
/// request. The server receives a <see cref="NetwActionContext"/>, validates at
/// <see cref="NetwActionContext.ViewTick"/>, and either binds an authoritative
/// spawned <see cref="NetwEntity"/> result with
/// <see cref="NetwActionContext.Bind"/> or denies it with
/// <see cref="NetwActionContext.Deny"/>. Each authority method on an entity has
/// its own slot, so actions created at one view tick use distinct effect keys.
/// Create one with <see cref="Netw.Action"/>. The authority method must be a
/// plain <see cref="Callable"/>, not an RPC.
/// <code>
/// @onready var place_bomb := Netw.action(_place_bomb)
///
/// func _ready() -&gt; void:
///     place_bomb.predict = _predict_bomb
///
/// func _network_tick(delta, tick, is_fresh) -&gt; void:
///     if is_fresh and inputs.bombing:
///         place_bomb.request(tick)
///
/// func _place_bomb(ctx: NetwActionContext) -&gt; void:
///     var bomb := BOMB.instantiate()
///     ctx.bind(bomb)
///     $Bombs.add_child(bomb)
/// </code>
/// </remarks>
public sealed class NetwAction : NetwRefCounted
{
    public NetwAction(IntPtr native) : base(native)
    {
    }

    public static NetwAction Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwAction(native);
    }

    public static NetwAction From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    public enum TimingModeEnum : long
    {
        /// <summary>
        /// Execute on the server when <see cref="NetwActionContext.ViewTick"/>
        /// arrives.
        /// </summary>
        TickAligned = 0,
        /// <summary>
        /// Execute after server history records
        /// <see cref="NetwActionContext.ViewTick"/>. This mode is
        /// owner-anchored. It guarantees only that the action owner's recorded
        /// state is ready at the view tick, and gates no other entity, so
        /// cross-entity validation must use
        /// <see cref="NetwMultiplayer.LagcompSample"/> or
        /// <see cref="NetwMultiplayer.LagcompRewind"/> for those targets.
        /// Determinism is a precondition, not a toggle. The placement agrees
        /// with the client only when consuming the same input yields the same
        /// state, and resolution is deferred until that state exists, so remote
        /// peers see the result later. Use
        /// <see cref="NetwAction.TimingModeEnum.Immediate"/> when the action
        /// must not wait. Under loss, the consume policy may fill a missing
        /// input slot: this mode guarantees a recorded state exists, not that
        /// it came from the real input.
        /// </summary>
        TickAlignedStateReady = 1,
        /// <summary>
        /// Execute as soon as the request reaches the server.
        /// </summary>
        Immediate = 2,
    }

    /// <summary>
    /// Emitted when the authoritative result adopts the optimistic effect.
    /// </summary>
    public event Action Confirmed
    {
        add => Connect("confirmed", Callable.From(value));
        remove => Disconnect("confirmed", Callable.From(value));
    }

    /// <summary>
    /// Emitted when the server denies the optimistic effect or it times out.
    /// </summary>
    public event Action Denied
    {
        add => Connect("denied", Callable.From(value));
        remove => Disconnect("denied", Callable.From(value));
    }

    private static readonly IntPtr _bindGetPredict =
        NetwApi.MethodBind("NetwAction", "get_predict", 1307783378UL);

    private static readonly IntPtr _bindSetPredict =
        NetwApi.MethodBind("NetwAction", "set_predict", 1611583062UL);

    /// <summary>
    /// Creates the local optimistic effect and returns the ghost
    /// <see cref="Node"/> that <see cref="NetwAction.Confirm"/> and
    /// <see cref="NetwAction.Revert"/> later receive.
    /// </summary>
    public Callable Predict
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetPredict, Checked, ref answered);
            Callable result = VariantUtils.ConvertToCallable(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromCallable(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetPredict, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetRevert =
        NetwApi.MethodBind("NetwAction", "get_revert", 1307783378UL);

    private static readonly IntPtr _bindSetRevert =
        NetwApi.MethodBind("NetwAction", "set_revert", 1611583062UL);

    /// <summary>
    /// Reverts the optimistic effect, taking the ghost <see cref="Node"/>
    /// <see cref="NetwAction.Predict"/> returned. Unset, the ghost is freed
    /// with <see cref="Node.QueueFree"/>.
    /// </summary>
    public Callable Revert
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetRevert, Checked, ref answered);
            Callable result = VariantUtils.ConvertToCallable(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromCallable(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetRevert, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetConfirm =
        NetwApi.MethodBind("NetwAction", "get_confirm", 1307783378UL);

    private static readonly IntPtr _bindSetConfirm =
        NetwApi.MethodBind("NetwAction", "set_confirm", 1611583062UL);

    /// <summary>
    /// Confirms the optimistic effect, taking the ghost <see cref="Node"/>
    /// <see cref="NetwAction.Predict"/> returned. Unset, the ghost is freed
    /// with <see cref="Node.QueueFree"/>.
    /// </summary>
    public Callable Confirm
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetConfirm, Checked, ref answered);
            Callable result = VariantUtils.ConvertToCallable(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromCallable(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetConfirm, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetTimeoutTicks =
        NetwApi.MethodBind("NetwAction", "get_timeout_ticks", 3905245786UL);

    private static readonly IntPtr _bindSetTimeoutTicks =
        NetwApi.MethodBind("NetwAction", "set_timeout_ticks", 1286410249UL);

    /// <summary>
    /// Ticks before an unresolved request reverts. <c>0</c> derives a
    /// conservative default from the lag-compensation engine.
    /// </summary>
    public long TimeoutTicks
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetTimeoutTicks,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetTimeoutTicks,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetTimingMode =
        NetwApi.MethodBind("NetwAction", "get_timing_mode", 3862591344UL);

    private static readonly IntPtr _bindSetTimingMode =
        NetwApi.MethodBind("NetwAction", "set_timing_mode", 4181664630UL);

    /// <summary>
    /// The server execution policy. Defaults to
    /// <see cref="NetwAction.TimingModeEnum.Immediate"/>, which is arrival-time
    /// execution with no readiness assumptions, so stricter modes are opted
    /// into per action.
    /// </summary>
    public NetwAction.TimingModeEnum TimingMode
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetTimingMode, Checked, ref answered);
            return (NetwAction.TimingModeEnum)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetTimingMode,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindRequest =
        NetwApi.MethodBind("NetwAction", "request", 762430443UL);

    /// <summary>
    /// Requests the server authority method for <paramref name="viewTick"/>,
    /// carrying <paramref name="data"/> as its second argument. The local
    /// controller gets an immediate <see cref="NetwAction.Predict"/> effect.
    /// Non-owning peers do nothing, so server consume and remote display passes
    /// cannot double fire a command. <b>Player request.</b>
    /// </summary>
    public void Request(long viewTick, Variant data = default)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)viewTick);
        godot_variant slot1 = data.CopyNativeVariant();
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindRequest,
            Checked,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        answered.Dispose();
    }
}
