// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// A player identity an auth flow has already validated.
/// </summary>
/// <remarks>
/// An auth provider returns this inside an <see cref="AuthResult"/>. The
/// session treats <see cref="NetwIdentity.UserName"/> as server-authoritative
/// and stores the identity per peer. Access it through
/// <see cref="NetwParticipant.Identity"/>. A session without an auth provider
/// has no identities at all, and <see cref="NetwParticipant.Identity"/> returns
/// <c>null</c> there. It is never replicated. What the server sends other peers
/// is the membership and the <see cref="NetwParticipant.UserName"/>, so a game
/// that wants an identity known elsewhere replicates what it chooses to share.
/// <code>
/// func verify(data: PackedByteArray) -&gt; AuthResult:
///     var identity := NetwIdentity.new()
///     identity.username = &amp;"valeria"
///     identity.external_id = "76561198000000000"
///     identity.service = &amp;"steam"
///     return AuthResult.accept(identity)
/// </code>
/// <para>
/// The two statics are separate from all of that. They name a node for a human
/// or for a log, and they work whether or not the session ever authenticated
/// anyone.
/// </para>
/// </remarks>
public sealed class NetwIdentity : NetwRefCounted
{
    public NetwIdentity(IntPtr native) : base(native)
    {
    }

    public static NetwIdentity Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwIdentity(native);
    }

    public static NetwIdentity From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    private static readonly IntPtr _bindGetUserName =
        NetwApi.MethodBind("NetwIdentity", "get_username", 2002593661UL);

    private static readonly IntPtr _bindSetUserName =
        NetwApi.MethodBind("NetwIdentity", "set_username", 3304788590UL);

    /// <summary>
    /// The display name to spawn and show this player under.
    /// Server-authoritative, because an auth flow validated it rather than the
    /// peer asserting it.
    /// </summary>
    public StringName UserName
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetUserName, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetUserName, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetExternalId =
        NetwApi.MethodBind("NetwIdentity", "get_external_id", 201670096UL);

    private static readonly IntPtr _bindSetExternalId =
        NetwApi.MethodBind("NetwIdentity", "set_external_id", 83702148UL);

    /// <summary>
    /// The provider's own id for this player, such as a Steam id or a Discord
    /// user id.
    /// </summary>
    public string ExternalId
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetExternalId, Checked, ref answered);
            string result = VariantUtils.ConvertToString(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromString(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetExternalId,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetService =
        NetwApi.MethodBind("NetwIdentity", "get_service", 2002593661UL);

    private static readonly IntPtr _bindSetService =
        NetwApi.MethodBind("NetwIdentity", "set_service", 3304788590UL);

    /// <summary>
    /// The auth service that produced this identity.
    /// </summary>
    public StringName Service
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetService, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetService, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetMetadata =
        NetwApi.MethodBind("NetwIdentity", "get_metadata", 3102165223UL);

    private static readonly IntPtr _bindSetMetadata =
        NetwApi.MethodBind("NetwIdentity", "set_metadata", 4155329257UL);

    /// <summary>
    /// Opaque provider data, forwarded as the provider gave it. Nothing in the
    /// session reads it.
    /// </summary>
    public Godot.Collections.Dictionary Metadata
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetMetadata, Checked, ref answered);
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromDictionary(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetMetadata, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindUserNameOf =
        NetwApi.MethodBind("NetwIdentity", "username_of", 3089653882UL);

    /// <summary>
    /// A display name for <paramref name="node"/>, for UI and logs. It returns
    /// the entity id <paramref name="node"/> was bound under when it has one,
    /// and otherwise the part of the node's name before the <c>|</c> separator,
    /// which is where a bound name keeps it. A node that is not valid returns
    /// an empty <see cref="string"/>.
    /// </summary>
    public static string UserNameOf(GodotObject node)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant answered = default;
        NetwThunks.Call1(_bindUserNameOf, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        string result = VariantUtils.ConvertToString(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindStableIdOf =
        NetwApi.MethodBind("NetwIdentity", "stable_id_of", 2112980793UL);

    /// <summary>
    /// A key for <paramref name="node"/> that survives the node being rebuilt,
    /// for a debugger or a log that has to match rows across frames. It returns
    /// the peer <paramref name="node"/>'s entity represents when there is one,
    /// then the peer its name spells, and only then the node path, because a
    /// path changes when the node moves and the first two do not. A node that
    /// is not valid returns an empty <see cref="string"/>.
    /// </summary>
    public static Variant StableIdOf(GodotObject node)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant answered = default;
        NetwThunks.Call1(_bindStableIdOf, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        Variant result = Variant.CreateCopyingBorrowed(answered);
        answered.Dispose();
        return result;
    }
}
