// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// One peer's bid to steer an entity, and the latch any listener rejects it
/// with.
/// </summary>
/// <remarks>
/// <see cref="NetwEntity"/> emits <see cref="NetwEntity.ControlRequested"/>
/// with one <see cref="NetwControlRequest"/> per request. Gameplay code may
/// inspect <see cref="NetwControlRequest.Requester"/> and call
/// <see cref="NetwControlRequest.Deny"/> before the default grant path runs.
/// Every listener sees the same record, so
/// <see cref="NetwControlRequest.Denied"/> is a latch: once a listener rejects,
/// no listener after it can take the rejection back, and listener order does
/// not decide who gets to steer.
/// <code>
/// func _on_control_requested(peer_id: int, request: NetwControlRequest) -&gt; void:
///     if not can_carry(peer_id):
///         request.deny()
/// </code>
/// </remarks>
public sealed class NetwControlRequest : NetwRefCounted
{
    public NetwControlRequest(IntPtr native) : base(native)
    {
    }

    public static NetwControlRequest Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwControlRequest(native);
    }

    public static NetwControlRequest From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    private static readonly IntPtr _bindGetRequester =
        NetwApi.MethodBind("NetwControlRequest", "get_requester", 3905245786UL);

    private static readonly IntPtr _bindSetRequester =
        NetwApi.MethodBind("NetwControlRequest", "set_requester", 1286410249UL);

    /// <summary>
    /// Peer id reported by <see cref="MultiplayerApi.GetRemoteSenderId"/>.
    /// </summary>
    public long Requester
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetRequester, Checked, ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetRequester,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetDenied =
        NetwApi.MethodBind("NetwControlRequest", "get_denied", 36873697UL);

    private static readonly IntPtr _bindSetDenied =
        NetwApi.MethodBind("NetwControlRequest", "set_denied", 2586408642UL);

    /// <summary>
    /// Whether the request should be rejected. Writing <c>false</c> over a
    /// rejection does nothing, because the rejection is a latch.
    /// </summary>
    public bool Denied
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetDenied, Checked, ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetDenied,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetHold =
        NetwApi.MethodBind("NetwControlRequest", "get_hold", 1976353525UL);

    /// <summary>
    /// The <see cref="NetwEntity.HoldEnum"/> the peer asked to hold the entity
    /// with.
    /// </summary>
    public NetwEntity.HoldEnum Hold
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetHold, Checked, ref answered);
            return (NetwEntity.HoldEnum)answered;
        }
    }

    private static readonly IntPtr _bindDeny =
        NetwApi.MethodBind("NetwControlRequest", "deny", 3218959716UL);

    /// <summary>
    /// Rejects this request.
    /// </summary>
    public void Deny()
    {
        long discarded = default;
        NetwThunks.Ptrcall0_Long(_bindDeny, Checked, ref discarded);
    }
}
