// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// One past tick, passed to a <see cref="NetwPropertyConfig.CarryStep"/>
/// callback.
/// </summary>
/// <remarks>
/// Read only from this object in the callback, not from the scene, since it
/// describes a tick in the past.
/// <code>
/// func _carry(value: Vector3, ctx: NetwPredictCarryContext) -&gt; Vector3:
///     var axis := _drive_axis(ctx.state[&amp;"heading"])
///     return value + axis * ctx.state[&amp;"speed"] * ctx.delta
/// </code>
/// </remarks>
public sealed class NetwPredictCarryContext : NetwRefCounted
{
    public NetwPredictCarryContext(IntPtr native) : base(native)
    {
    }

    public static NetwPredictCarryContext Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwPredictCarryContext(
            native);
    }

    public static NetwPredictCarryContext From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    private static readonly IntPtr _bindGetState =
        NetwApi.MethodBind(
            "NetwPredictCarryContext",
            "get_state",
            3102165223UL);

    /// <summary>
    /// The <see cref="NetwPropertyConfig.State"/> values at the start of the
    /// tick.
    /// </summary>
    public Godot.Collections.Dictionary State
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetState, Checked, ref answered);
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetInput =
        NetwApi.MethodBind(
            "NetwPredictCarryContext",
            "get_input",
            3102165223UL);

    /// <summary>
    /// The <see cref="NetwPropertyConfig.Input"/> values of the tick.
    /// </summary>
    public Godot.Collections.Dictionary Input
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetInput, Checked, ref answered);
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetDelta =
        NetwApi.MethodBind(
            "NetwPredictCarryContext",
            "get_delta",
            1740695150UL);

    /// <summary>
    /// The length of the tick, in seconds.
    /// </summary>
    public double Delta
    {
        get
        {
            double answered = default;
            NetwThunks.Ptrcall0_Double(_bindGetDelta, Checked, ref answered);
            return answered;
        }
    }

    private static readonly IntPtr _bindGetLabel =
        NetwApi.MethodBind(
            "NetwPredictCarryContext",
            "get_label",
            3905245786UL);

    /// <summary>
    /// The tick of the input.
    /// </summary>
    public long Label
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetLabel, Checked, ref answered);
            return answered;
        }
    }
}
