// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// The travel declaration every script member shares, and the whole of what an
/// RPC, a signal or a spawn function declares.
/// </summary>
/// <remarks>
/// A member is an RPC, a property, or a signal, and the same fluent builder
/// declares all three because the axes are the same ones: who may author the
/// stream (<see cref="NetwMemberConfig.Authority"/>,
/// <see cref="NetwMemberConfig.Controller"/>,
/// <see cref="NetwMemberConfig.AnyPeer"/>), how it travels
/// (<see cref="NetwMemberConfig.Reliable"/>,
/// <see cref="NetwMemberConfig.Unreliable"/>,
/// <see cref="NetwMemberConfig.Quantize"/>), and what the receiver does with it
/// (<see cref="NetwMemberConfig.DeferUntil"/>,
/// <see cref="NetwMemberConfig.Interpolate"/>).
/// <see cref="Netw.ConfigureRpc"/>, <see cref="Netw.ConfigureSignal"/> and
/// <see cref="Netw.ConfigureSpawn"/> each return one of these, and
/// <see cref="Netw.ConfigureProperty"/> returns the
/// <see cref="NetwPropertyConfig"/> that extends it.
/// <see cref="NetwMemberConfig.ContextType"/> is which of the three this is:
/// <c>0</c> an RPC or spawn function, <c>1</c> a property, <c>2</c> a signal.
/// Everything that has to tell them apart reads that ordinal, which is also why
/// one class serves three doors.
/// <code>
/// func _init() -&gt; void:
///     Netw.configure_rpc(self.fire).unreliable().controller_only()
///     Netw.configure_signal(self.exploded).any_peer()
///     Netw.configure_spawn(self._spawn_bullet).quantize(dir_q)
/// </code>
/// <para>
/// A configuration is keyed per script while <c>Object._init</c> runs per
/// instance, so every spawn of a script re-declares onto the config the first
/// instance created. Re-declaring an axis with the value it already carries is
/// therefore SILENT, and only a genuine disagreement between two call sites
/// warns. That rule is what makes authoring in <c>Object._init</c> quiet rather
/// than one warning per spawn. <b>The chain downgrades to this type.</b> A
/// bound method records one return type, so every verb here returns a
/// <see cref="NetwMemberConfig"/> even when it was called on a
/// <see cref="NetwPropertyConfig"/>. A chain that passes through a base verb
/// loses the property-only verbs from that point on, and a property declaration
/// therefore orders its property-only verbs LAST:
/// <code>
/// Netw.configure_property(self, &amp;"position").state().quantize(pos_q)   # fine
/// Netw.configure_property(self, &amp;"position").quantize(pos_q).state()   # state() is gone
/// </code>
/// </para>
/// </remarks>
public class NetwMemberConfig : NetwRefCounted
{
    public NetwMemberConfig(IntPtr native) : base(native)
    {
    }

    public static NetwMemberConfig Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwMemberConfig(native);
    }

    public static NetwMemberConfig From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    public enum Policy : long
    {
        /// <summary>
        /// Only the node's multiplayer authority may write or emit.
        /// </summary>
        Authority = 0,
        /// <summary>
        /// Only the peer holding <see cref="NetwEntity.Controller"/> may write
        /// or emit.
        /// </summary>
        Controller = 1,
        /// <summary>
        /// Any peer may write or emit.
        /// </summary>
        AnyPeer = 2,
    }

    public enum TransferModeEnum : long
    {
        /// <summary>
        /// Transmit reliably.
        /// </summary>
        Reliable = 0,
        /// <summary>
        /// Transmit unreliably.
        /// </summary>
        Unreliable = 1,
    }

    private static readonly IntPtr _bindGetContextScript =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_context_script",
            278624046UL);

    private static readonly IntPtr _bindSetContextScript =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_context_script",
            3657522847UL);

    /// <summary>
    /// The <see cref="Script"/> that declares the member. The declaration and
    /// <see cref="NetwMemberConfig.WritePolicy"/> use this as their key.
    /// <c>null</c> means the property is declared directly on a node without a
    /// script. Named WITHOUT being owned: the script is held by instance id and
    /// resolved on every read, so a script that has been freed returns
    /// <c>null</c> here rather than a stale object. A declaration is stored in
    /// the declaring script's own metadata book, so an owning back-reference
    /// would close a cycle out of which neither the script nor any config
    /// declared on it could ever be freed.
    /// </summary>
    public Script ContextScript
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetContextScript, Checked, ref answered);
            Script result = (Script)VariantUtils.ConvertToGodotObject(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            IntPtr slot0 = value?.NativeInstance ?? IntPtr.Zero;
            long discarded = default;
            NetwThunks.Ptrcall1_IntPtr_Long(
                _bindSetContextScript,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetContextNodeRef =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_context_node_ref",
            1214101251UL);

    private static readonly IntPtr _bindSetContextNodeRef =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_context_node_ref",
            1114965689UL);

    /// <summary>
    /// An opaque weak reference to the body a property config was authored on,
    /// or <c>null</c>. It is dereferenced only while resolving a property's
    /// declared type, which is read off the live body rather than off
    /// <see cref="NetwMemberConfig.ContextScript"/>, because a node the
    /// framework tracks without a script has no declaration to read it from. A
    /// body that has been freed returns <c>@GlobalScope.TYPE_NIL</c>, which is
    /// why the reference is weak.
    /// </summary>
    public Variant ContextNodeRef
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetContextNodeRef, Checked, ref answered);
            Variant result = Variant.CreateCopyingBorrowed(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = value.CopyNativeVariant();
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetContextNodeRef,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetWritePolicy =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_write_policy",
            3445425618UL);

    private static readonly IntPtr _bindSetWritePolicy =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_write_policy",
            1414759222UL);

    /// <summary>
    /// Who may write or emit this member. Declared through
    /// <see cref="NetwMemberConfig.Authority"/>,
    /// <see cref="NetwMemberConfig.Controller"/> and
    /// <see cref="NetwMemberConfig.AnyPeer"/>, and re-declaring the value it
    /// already carries is silent. Writing it also COMPILES the rule into the
    /// declaring script's own metadata book, so the receive gate returns off
    /// the script rather than walking this registry for every arriving frame.
    /// Nothing is published for an RPC
    /// (<see cref="NetwMemberConfig.ContextType"/> <c>0</c>), which is policed
    /// by its caller gate instead, or for a config naming no
    /// <see cref="NetwMemberConfig.ContextScript"/>, which has no book to write
    /// into.
    /// </summary>
    public NetwMemberConfig.Policy WritePolicy
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetWritePolicy,
                Checked,
                ref answered);
            return (NetwMemberConfig.Policy)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetWritePolicy,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetTransferMode =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_transfer_mode",
            212521333UL);

    private static readonly IntPtr _bindSetTransferMode =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_transfer_mode",
            1591769103UL);

    /// <summary>
    /// How the member travels. Declared through
    /// <see cref="NetwMemberConfig.Reliable"/> and
    /// <see cref="NetwMemberConfig.Unreliable"/>, and re-declaring the value it
    /// already carries is silent.
    /// </summary>
    public NetwMemberConfig.TransferModeEnum TransferMode
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetTransferMode,
                Checked,
                ref answered);
            return (NetwMemberConfig.TransferModeEnum)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetTransferMode,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetIsCallLocal =
        NetwApi.MethodBind("NetwMemberConfig", "get_is_call_local", 36873697UL);

    private static readonly IntPtr _bindSetIsCallLocal =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_is_call_local",
            2586408642UL);

    /// <summary>
    /// Whether the signal or RPC also runs on the sender. Declared through
    /// <see cref="NetwMemberConfig.CallLocal"/> and
    /// <see cref="NetwMemberConfig.CallRemote"/>, and re-declaring the value it
    /// already carries is silent.
    /// </summary>
    public bool IsCallLocal
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetIsCallLocal,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetIsCallLocal,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetContextName =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_context_name",
            2002593661UL);

    private static readonly IntPtr _bindSetContextName =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_context_name",
            3304788590UL);

    /// <summary>
    /// The member this config declares: a method name, a property name, or a
    /// signal name, decided by <see cref="NetwMemberConfig.ContextType"/>.
    /// Written by the <c>Netw.configure_*</c> door that created the config.
    /// </summary>
    public StringName ContextName
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetContextName, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetContextName,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetContextType =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_context_type",
            3905245786UL);

    private static readonly IntPtr _bindSetContextType =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_context_type",
            1286410249UL);

    /// <summary>
    /// Which kind of member this is: <c>0</c> an RPC or a spawn function,
    /// <c>1</c> a property, <c>2</c> a signal. It decides which book
    /// <see cref="NetwMemberConfig.WritePolicy"/> is published into, and which
    /// reflection resolves the member's declared types: a method's argument
    /// types, a live node's property type, or a signal's argument types.
    /// </summary>
    public long ContextType
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetContextType,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetContextType,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetDeferSignalName =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_defer_signal_name",
            2002593661UL);

    private static readonly IntPtr _bindSetDeferSignalName =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_defer_signal_name",
            3304788590UL);

    /// <summary>
    /// The signal a received call waits on before it runs, or empty to run it
    /// as soon as the node is live. Declared through
    /// <see cref="NetwMemberConfig.DeferUntil"/>.
    /// </summary>
    public StringName DeferSignalName
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetDeferSignalName, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetDeferSignalName,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetIsControllerOnly =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_is_controller_only",
            36873697UL);

    private static readonly IntPtr _bindSetIsControllerOnly =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_is_controller_only",
            2586408642UL);

    /// <summary>
    /// Whether only the entity's controller, or the server, may call this RPC.
    /// Declared through <see cref="NetwMemberConfig.ControllerOnly"/>.
    /// </summary>
    public bool IsControllerOnly
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetIsControllerOnly,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetIsControllerOnly,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetQuantizers =
        NetwApi.MethodBind("NetwMemberConfig", "get_quantizers", 3995934104UL);

    private static readonly IntPtr _bindSetQuantizers =
        NetwApi.MethodBind("NetwMemberConfig", "set_quantizers", 381264803UL);

    /// <summary>
    /// Per-position <see cref="NetwQuantize"/> list packing the member's
    /// values. Empty sends every value self-describing, and a null slot does
    /// the same for one position. Declared through
    /// <see cref="NetwMemberConfig.Quantize"/>.
    /// </summary>
    public Godot.Collections.Array Quantizers
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetQuantizers, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromArray(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetQuantizers,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetInterpolators =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "get_interpolators",
            3995934104UL);

    private static readonly IntPtr _bindSetInterpolators =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "set_interpolators",
            381264803UL);

    /// <summary>
    /// Per-position <see cref="NetwInterpolate"/> list smoothing received
    /// values. Empty applies each received value directly. Declared through
    /// <see cref="NetwMemberConfig.Interpolate"/>.
    /// </summary>
    public Godot.Collections.Array Interpolators
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetInterpolators, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromArray(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetInterpolators,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindAuthority =
        NetwApi.MethodBind("NetwMemberConfig", "authority", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.WritePolicy"/>
    /// <see cref="NetwMemberConfig.Policy.Authority"/>: only the node's
    /// multiplayer authority may write or emit. The default, and the safe
    /// choice.
    /// </summary>
    public NetwMemberConfig Authority()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindAuthority, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindController =
        NetwApi.MethodBind("NetwMemberConfig", "controller", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.WritePolicy"/>
    /// <see cref="NetwMemberConfig.Policy.Controller"/>: only the peer holding
    /// <see cref="NetwEntity.Controller"/> may write or emit, which is how a
    /// player drives their own entity.
    /// </summary>
    public NetwMemberConfig Controller()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindController, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindAnyPeer =
        NetwApi.MethodBind("NetwMemberConfig", "any_peer", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.WritePolicy"/>
    /// <see cref="NetwMemberConfig.Policy.AnyPeer"/>: any peer may write or
    /// emit. Trusts every client, so it belongs only where a forged write
    /// cannot matter.
    /// </summary>
    public NetwMemberConfig AnyPeer()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindAnyPeer, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindReliable =
        NetwApi.MethodBind("NetwMemberConfig", "reliable", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.TransferMode"/>
    /// <see cref="NetwMemberConfig.TransferModeEnum.Reliable"/>. The default.
    /// </summary>
    public NetwMemberConfig Reliable()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindReliable, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindUnreliable =
        NetwApi.MethodBind("NetwMemberConfig", "unreliable", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.TransferMode"/>
    /// <see cref="NetwMemberConfig.TransferModeEnum.Unreliable"/>.
    /// </summary>
    public NetwMemberConfig Unreliable()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindUnreliable, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindCallLocal =
        NetwApi.MethodBind("NetwMemberConfig", "call_local", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.IsCallLocal"/>: the signal or RPC
    /// also runs on the sender. <see cref="Netw.ConfigureSignal"/> starts here,
    /// and <see cref="Netw.ConfigureRpc"/> starts at
    /// <see cref="NetwMemberConfig.CallRemote"/>. A property
    /// (<see cref="NetwMemberConfig.ContextType"/> <c>1</c>) has no local-call
    /// axis, because a property assignment is local first by construction, so
    /// declaring one on a <see cref="NetwPropertyConfig"/> warns and records
    /// the axis anyway.
    /// </summary>
    public NetwMemberConfig CallLocal()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindCallLocal, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindCallRemote =
        NetwApi.MethodBind("NetwMemberConfig", "call_remote", 3574862355UL);

    /// <summary>
    /// Clears <see cref="NetwMemberConfig.IsCallLocal"/>: the signal or RPC
    /// reaches remote peers only. The default for an RPC, and warns on a
    /// property for the reason <see cref="NetwMemberConfig.CallLocal"/> gives.
    /// </summary>
    public NetwMemberConfig CallRemote()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindCallRemote, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindDeferUntil =
        NetwApi.MethodBind("NetwMemberConfig", "defer_until", 4061727032UL);

    /// <summary>
    /// Defers a received call until <paramref name="sig"/> fires on the target
    /// node. <c>self.ready</c> is a common choice. The configuration stores the
    /// signal name in <see cref="NetwMemberConfig.DeferSignalName"/>. Declaring
    /// a second signal for one member reports a warning.
    /// </summary>
    public NetwMemberConfig DeferUntil(Signal sig)
    {
        godot_variant slot0 = VariantUtils.CreateFromSignal(sig);
        godot_variant answered = default;
        NetwThunks.Call1(_bindDeferUntil, Checked, in slot0, ref answered);
        slot0.Dispose();
        NetwMemberConfig result =
            NetwMemberConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindControllerOnly =
        NetwApi.MethodBind("NetwMemberConfig", "controller_only", 3574862355UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.IsControllerOnly"/>: only the
    /// entity's controller, or the server, may call this RPC.
    /// </summary>
    public NetwMemberConfig ControllerOnly()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindControllerOnly, Checked, ref answered);
        return NetwMemberConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindQuantize =
        NetwApi.MethodBind("NetwMemberConfig", "quantize", 2087025817UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.Quantizers"/>, one
    /// <see cref="NetwQuantize"/> per argument the member takes, in the order
    /// the member declares them. A property or a one-argument member therefore
    /// takes exactly one, and <c>null</c> sends an argument unpacked.
    /// <code>
    /// Netw.configure_property(self, &amp;"position").quantize(pos_q)
    /// Netw.configure_rpc(self.fire).quantize(dir_q, null, power_q)
    /// </code>
    /// <para>
    /// The count is checked against the arity of
    /// <see cref="NetwMemberConfig.ContextName"/>, which
    /// <see cref="NetwMemberConfig.ContextType"/> decides how to read, so a
    /// member taking three arguments and given one quantizer is rejected rather
    /// than packed halfway. A member whose declaration cannot be read at all is
    /// taken on trust. Passing nothing, or an argument that is not a
    /// <see cref="NetwQuantize"/>, is rejected with an error and leaves the
    /// previous declaration standing. Re-declaring a layout-equal list
    /// (<see cref="NetwQuantize.IsSameLayout"/>) is silent. Only a
    /// re-declaration that changes the bit layout warns, since that is two call
    /// sites genuinely disagreeing about one member's schema. Whether a
    /// declared quantizer can pack the type it sits over is checked against
    /// that same declared type.
    /// </para>
    /// </summary>
    public NetwMemberConfig Quantize(params Variant[] rest)
    {
        int total = 0 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        for (int index = 0; index < total; index++)
        {
            godot_variant carried = rest[index - 0].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(_bindQuantize, Checked, pack, total, ref answered);
        NetwThunks.ArgsFree(pack);
        NetwMemberConfig result =
            NetwMemberConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindInterpolate =
        NetwApi.MethodBind("NetwMemberConfig", "interpolate", 2087025817UL);

    /// <summary>
    /// Declares <see cref="NetwMemberConfig.Interpolators"/>, one
    /// <see cref="NetwInterpolate"/> per value the member carries, in the order
    /// the member declares them. A property or a one-argument member therefore
    /// takes exactly one, and <c>null</c> leaves a value unsmoothed. The rules
    /// are <see cref="NetwMemberConfig.Quantize"/>'s, read against
    /// <see cref="NetwInterpolate.IsSameSpec"/> rather than a bit layout: a
    /// re-declaration of equal specs returns immediately and changes nothing,
    /// so an authoring shell can push freshly built but identical specs after a
    /// reparent, and one that genuinely differs replaces the standing list and
    /// warns.
    /// <code>
    /// Netw.configure_property(self, &amp;"position").interpolate(pos_lerp)
    /// Netw.configure_signal(self.aimed).interpolate(null, dir_slerp)
    /// </code>
    /// </summary>
    public NetwMemberConfig Interpolate(params Variant[] rest)
    {
        int total = 0 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        for (int index = 0; index < total; index++)
        {
            godot_variant carried = rest[index - 0].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindInterpolate,
            Checked,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        NetwMemberConfig result =
            NetwMemberConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindIsPolicyDeclared =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "is_policy_declared",
            36873697UL);

    /// <summary>
    /// Whether <see cref="NetwMemberConfig.WritePolicy"/> was WRITTEN, rather
    /// than what it holds. A set derived from several members of one script
    /// asks this so that a member which declared its policy out loud owns the
    /// set's policy and a member that declared none does not, and declaring the
    /// default value is still declaring it.
    /// </summary>
    public bool IsPolicyDeclared()
    {
        byte answered = default;
        NetwThunks.Ptrcall0_Byte(_bindIsPolicyDeclared, Checked, ref answered);
        return answered != 0;
    }

    private static readonly IntPtr _bindIsTransferDeclared =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "is_transfer_declared",
            36873697UL);

    /// <summary>
    /// Whether <see cref="NetwMemberConfig.TransferMode"/> was WRITTEN, rather
    /// than what it holds. Same reading as
    /// <see cref="NetwMemberConfig.IsPolicyDeclared"/>.
    /// </summary>
    public bool IsTransferDeclared()
    {
        byte answered = default;
        NetwThunks.Ptrcall0_Byte(
            _bindIsTransferDeclared,
            Checked,
            ref answered);
        return answered != 0;
    }

    private static readonly IntPtr _bindIsInterpolationOnly =
        NetwApi.MethodBind(
            "NetwMemberConfig",
            "is_interpolation_only",
            36873697UL);

    /// <summary>
    /// Whether this config only smooths a value and never claims a write: it
    /// carries <see cref="NetwMemberConfig.Interpolators"/> and no
    /// <see cref="NetwMemberConfig.WritePolicy"/>,
    /// <see cref="NetwMemberConfig.TransferMode"/> or
    /// <see cref="NetwMemberConfig.Quantizers"/> was DECLARED. It reads whether
    /// each axis was written at all rather than what it holds, so declaring an
    /// axis its own default value still ends the interpolation-only reading.
    /// Smoothing a property some other set already replicates is expected, and
    /// this is how that case is told apart from a second claim of authority
    /// over the field.
    /// </summary>
    public bool IsInterpolationOnly()
    {
        byte answered = default;
        NetwThunks.Ptrcall0_Byte(
            _bindIsInterpolationOnly,
            Checked,
            ref answered);
        return answered != 0;
    }
}
