// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// Diagnostic counters for one prediction engine.
/// </summary>
/// <remarks>
/// Contains counters, histograms, fingerprint totals, and prediction history
/// diagnostics. Use <see cref="NetwPredictionHandle"/> signals and reports for
/// gameplay decisions. Engine-backed members are read-only and return their
/// defaults when the entity has no active prediction slot. Other members are
/// writable diagnostic state.
/// <code>
/// var stats := NetwEntity.of(self).prediction.stats
/// print("%d corrections, %d skipped" % [stats.corrections, stats.skipped])
/// </code>
/// </remarks>
public sealed class NetwPredictStats : NetwRefCounted
{
    public NetwPredictStats(IntPtr native) : base(native)
    {
    }

    public static NetwPredictStats Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwPredictStats(native);
    }

    public static NetwPredictStats From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    /// <summary>
    /// Buckets <see cref="NetwPredictStats.Arrivals"/> holds, so its size is a
    /// declared fact rather than a shape a writer grew.
    /// </summary>
    public const long ArrivalBuckets = 9;
    /// <summary>
    /// Buckets <see cref="NetwPredictStats.ReplayDepth"/> holds.
    /// </summary>
    public const long ReplayDepthBuckets = 33;

    private static readonly IntPtr _bindGetIntFact =
        NetwApi.MethodBind("NetwPredictStats", "get_int_fact", 923996154UL);

    private static readonly IntPtr _bindSetIntFact =
        NetwApi.MethodBind("NetwPredictStats", "set_int_fact", 3937882851UL);

    /// <summary>
    /// Physics-frame callbacks folded into their tick's existing command
    /// record. A growing value means this peer produces frame callbacks faster
    /// than the shared network clock advances, but it cannot grow the command
    /// queue.
    /// </summary>
    public long AuthoringClamped
    {
        get
        {
            int slot0 = 0;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 0;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Prediction passes held because their unacknowledged horizon reached the
    /// structural ceiling. Input capture continues while the simulated body
    /// holds.
    /// </summary>
    public long SpeculationHeld
    {
        get
        {
            int slot0 = 1;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 1;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Physics steps the world advanced across the newest transition. A
    /// transition is a fixed quantum of simulated time, and a solver body is
    /// integrated by the physics server on its own cadence rather than by the
    /// drive, so two peers only compare a transition meaningfully when they
    /// spend the same number of steps on it. This is that number, measured
    /// rather than assumed, and <see cref="NetwPredictStats.QuantumDeclared"/>
    /// is what it is supposed to be.
    /// </summary>
    public long QuantumSteps
    {
        get
        {
            int slot0 = 2;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 2;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Physics steps one transition is declared to advance, from
    /// <see cref="NetwMultiplayer.ClockGetPhysicsStepsPerTick"/>.
    /// </summary>
    public long QuantumDeclared
    {
        get
        {
            int slot0 = 3;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 3;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Transitions whose measured <see cref="NetwPredictStats.QuantumSteps"/>
    /// differed from <see cref="NetwPredictStats.QuantumDeclared"/>. Any
    /// nonzero value means this peer advanced its solver by an amount no
    /// transition accounts for, so its predictions carry an error the compared
    /// columns cannot describe and no recovery can repair. It is measurable on
    /// one peer alone, before any comparison disagrees.
    /// </summary>
    public long QuantumFaults
    {
        get
        {
            int slot0 = 4;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 4;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Total corrections applied since spawn.
    /// </summary>
    public long Corrections
    {
        get
        {
            int slot0 = 5;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 5;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Deepest replay window walked by any correction, over the slot's whole
    /// life rather than over the last one. It is the high-water mark a budget
    /// is set against, so a single deep replay survives every shallow one after
    /// it. Every path that re-runs unacknowledged work records its own depth
    /// here, and a member a joint pass skipped every transition of records
    /// ZERO. What a replay cost is what it actually re-ran, and a counter
    /// reporting the span the pass covered instead would say a member was
    /// carried when it was not.
    /// </summary>
    public long MaxReplayDepth
    {
        get
        {
            int slot0 = 6;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 6;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Inputs the server consumed into authoritative state.
    /// </summary>
    public long Consumed
    {
        get
        {
            int slot0 = 7;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 7;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Input ticks the server stepped over as lost.
    /// </summary>
    public long Missing
    {
        get
        {
            int slot0 = 8;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 8;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Server ticks that consumed nothing because the queue was empty, the
    /// input stream running dry under the consume cursor. A healthy link holds
    /// this at zero once the standing consume buffer is holding, so a rising
    /// count is the de-jitter buffer being too shallow for the peers' clock
    /// phase drift.
    /// </summary>
    public long Starved
    {
        get
        {
            int slot0 = 9;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 9;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Consume passes that declined a transition they were holding, because the
    /// queue had not risen above the tier's standing buffer. A hold is a frame
    /// the world solved without running a transition, so it costs one
    /// <see cref="NetwPredictStats.QuantumFaults"/> on the next drive and
    /// nothing on the wire tells the owner it happened. Unlike
    /// <see cref="NetwPredictStats.Starved"/> there was a transition available,
    /// which is why the FRAME tier's replay buffer depth defaults to zero and
    /// never produces one.
    /// </summary>
    public long Held
    {
        get
        {
            int slot0 = 10;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 10;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Older eligible inputs skipped by a FRAME-scheduled backlog fold. The
    /// newest eligible input drives once, so this count never represents extra
    /// simulation applications.
    /// </summary>
    public long Folded
    {
        get
        {
            int slot0 = 11;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 11;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Monotone count of scheduled drive applications. This fingerprints their
    /// ordering without changing simulation behavior.
    /// </summary>
    public long DriveSeq
    {
        get
        {
            int slot0 = 12;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 12;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Input label applied by the most recent scheduled drive.
    /// </summary>
    public long LastDriveLabel
    {
        get
        {
            int slot0 = 13;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 13;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Selection kind of the most recent scheduled drive, a
    /// <see cref="NetwPredict.DriveKind"/> value.
    /// </summary>
    public long LastDriveKind
    {
        get
        {
            int slot0 = 14;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 14;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Epoch of the active prediction tape, or <c>-1</c> before one is authored
    /// or received. Rewiring starts a new client-authored epoch. An epoch
    /// change re-keys every tape cursor. Retaining a cursor could resolve it to
    /// a transition reused by the new epoch.
    /// </summary>
    public long TapeEpoch
    {
        get
        {
            int slot0 = 15;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 15;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Index of the newest prediction tape transition authored or received. A
    /// <see cref="NetwSimulationHandle.ScheduleEnum.Tick"/> entity's
    /// transitions are its ticks, so this tracks the newest driven tick there.
    /// </summary>
    public long TapeIndex
    {
        get
        {
            int slot0 = 16;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 16;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Contiguous owner-lane transitions currently queued on the consuming
    /// server at or beyond its replay cursor.
    /// </summary>
    public long TapeQueueDepth
    {
        get
        {
            int slot0 = 17;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 17;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Times the consume cursor gave up walking and re-opened at the live edge,
    /// bounded by the session's max consume lag. A healthy session resyncs once
    /// at most, when the controller's clock first anchors. A rising count means
    /// input is arriving too far ahead of the cursor to consume in order.
    /// </summary>
    public long Resync
    {
        get
        {
            int slot0 = 18;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 18;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Input ticks a <see cref="NetwPredictStats.Resync"/> jump passed over
    /// without simulating. They were already stale by more than the session's
    /// max consume lag, so the authoritative body skips them rather than
    /// replaying second-old intent.
    /// </summary>
    public long Skipped
    {
        get
        {
            int slot0 = 19;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 19;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Owner-lane frames authority dropped whole because they were malformed or
    /// carried a fresh transition without its command. A frame is never parsed
    /// into a shorter one, so this counts frames rather than transitions.
    /// </summary>
    public long FramesDroppedInvalid
    {
        get
        {
            int slot0 = 20;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 20;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Owner-lane frames this peer handed to the transport, counted where the
    /// bytes were produced rather than where they left. The owner writes one on
    /// every frame it drives and on every frame it holds, because a held frame
    /// still owes its commands. Read against the consuming peer's
    /// <see cref="NetwPredictStats.CommandFramesReceived"/>, the pair says how
    /// much of the lane survives the trip, which is the one lane fact neither
    /// peer can state alone.
    /// <code>
    /// sent == received      the lane delivers what it is given
    /// sent &gt;  received      frames are lost or coalesced under the engine, and
    ///                       the redundancy window is healing it silently
    /// </code>
    /// </summary>
    public long CommandFramesSent
    {
        get
        {
            int slot0 = 21;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 21;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Owner-lane frames authority decoded, whether or not they carried
    /// anything new. Counts frames rather than transitions, so it pairs
    /// directly with the owner's
    /// <see cref="NetwPredictStats.CommandFramesSent"/>.
    /// </summary>
    public long CommandFramesReceived
    {
        get
        {
            int slot0 = 22;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 22;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Transitions authority holds with their commands, decoded off the owner
    /// lane and waiting to be replayed.
    /// </summary>
    public long CommandQueueDepth
    {
        get
        {
            int slot0 = 23;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 23;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Relayed transitions this peer filed into the command matrix. Counts
    /// cells rather than frames, so the redundancy window's re-sends do not
    /// inflate it and the value is how much of another peer's authorship this
    /// one actually learned.
    /// </summary>
    public long RelayedRecorded
    {
        get
        {
            int slot0 = 24;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 24;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Relayed transitions dropped for naming a transition older than the
    /// matrix retains. A steady climb here means the relay is arriving later
    /// than the window is wide, so the subscriber is reconstructing a past its
    /// floor has already moved past.
    /// </summary>
    public long RelayedDroppedLate
    {
        get
        {
            int slot0 = 25;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 25;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// The highest transition the owner has received an acknowledgement for, or
    /// <c>-1</c> before any. This is the authority lane's confirmation
    /// frontier, and it is what floors both lanes' redundancy windows, so a
    /// value stuck at <c>-1</c> means the lane is not arriving rather than that
    /// it has nothing to say.
    /// </summary>
    public long AckConfirmed
    {
        get
        {
            int slot0 = 26;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 26;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// The transition authority's acknowledgement lane is currently able to
    /// ship, <c>-1</c> on an owner. It is the lesser of the consumed transition
    /// and the journal's closed prefix, so a value trailing the consumed one
    /// names the closed prefix as what is holding the lane back.
    /// </summary>
    public long AckFrontier
    {
        get
        {
            int slot0 = 27;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 27;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// The newest transition whose journal row is closed with every earlier
    /// retained row also closed, <c>-1</c> when none is. One row left open caps
    /// this for as long as the ring retains it, which caps
    /// <see cref="NetwPredictStats.AckFrontier"/> with it.
    /// </summary>
    public long JournalClosed
    {
        get
        {
            int slot0 = 28;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 28;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Authoritative frames this owner reached a divergence verdict on. Read it
    /// beside <see cref="NetwPredictStats.ComparisonsSkipped"/>: a divergence
    /// of zero means the peers agreed only when this is the counter that moved.
    /// A predicted entity whose skipped count climbs while this one stands
    /// still is speculating with no reconciliation at all, however healthy its
    /// divergence reads.
    /// </summary>
    public long ComparisonsRan
    {
        get
        {
            int slot0 = 29;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 29;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Authoritative frames this owner acknowledged without reaching a verdict,
    /// because the masked stream had not reconstructed a whole row to compare
    /// against. Every one of them reports a zero divergence it did not measure.
    /// </summary>
    public long ComparisonsSkipped
    {
        get
        {
            int slot0 = 30;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 30;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Transitions authority ran with a command the owner never authored, as
    /// declared on the acknowledgement lane. A silent substitution is the fault
    /// this counter exists to make impossible.
    /// </summary>
    public long Substituted
    {
        get
        {
            int slot0 = 31;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 31;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetBucketsFact =
        NetwApi.MethodBind(
            "NetwPredictStats",
            "get_buckets_fact",
            1706082319UL);

    private static readonly IntPtr _bindSetBucketsFact =
        NetwApi.MethodBind(
            "NetwPredictStats",
            "set_buckets_fact",
            3500328261UL);

    /// <summary>
    /// New transitions the owner lane delivered to authority, bucketed by how
    /// many arrived in one frame.
    /// <see cref="NetwSimulationHandle.ScheduleEnum.Frame"/> consume only.
    /// Arrival shape, not arrival total, sets consume health: a lane delivering
    /// one transition every frame and a lane delivering six every sixth frame
    /// have the same total and nothing else in common. Authority replays at
    /// most one per frame, so the second lane leaves five frames dry for every
    /// burst and no buffer setting changes that. Read it beside
    /// <see cref="NetwPredictStats.ReplayDepth"/> to tell a lane defect from a
    /// rate one. Indexed by arrival count, saturating at
    /// <see cref="NetwPredictStats.ArrivalBuckets"/> minus one.
    /// </summary>
    public int[] Arrivals
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)32);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindGetBucketsFact,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            int[] result =
                VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)32);
            godot_variant slot1 =
                VariantUtils.CreateFromPackedInt32Array(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetBucketsFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    /// <summary>
    /// Standing queued-transition depth at each authority frame's consume
    /// boundary, bucketed by depth.
    /// <see cref="NetwSimulationHandle.ScheduleEnum.Frame"/> consume only.
    /// Depth is the owner's lead over authority measured in transitions, so
    /// this reads the clock relationship rather than a queue: a distribution
    /// parked near zero says the two peers run at the same rate, and one that
    /// ratchets upward says the owner is authoring faster than authority is
    /// solving. Neither is returned by a replay buffer depth setting, which
    /// shifts this whole distribution and changes its shape not at all. Indexed
    /// by depth, saturating at
    /// <see cref="NetwPredictStats.ReplayDepthBuckets"/> minus one.
    /// </summary>
    public int[] ReplayDepth
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)33);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindGetBucketsFact,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            int[] result =
                VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)33);
            godot_variant slot1 =
                VariantUtils.CreateFromPackedInt32Array(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetBucketsFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetDictFact =
        NetwApi.MethodBind("NetwPredictStats", "get_dict_fact", 3485342025UL);

    private static readonly IntPtr _bindSetDictFact =
        NetwApi.MethodBind("NetwPredictStats", "set_dict_fact", 64545446UL);

    /// <summary>
    /// Authority frames bucketed by <c>"consumed,quantum_steps"</c>: how many
    /// transitions the frame ran against how much simulated time the last of
    /// them measured. <see cref="NetwSimulationHandle.ScheduleEnum.Frame"/>
    /// consume only. <c>"1,1"</c> is the healthy shape, one transition per
    /// solve. Every other key names a frame that spent simulated time no single
    /// transition accounts for, which is the divergence
    /// <see cref="NetwPredictStats.QuantumFaults"/> totals. This histogram is
    /// that total broken down by how each frame misspent.
    /// </summary>
    public Godot.Collections.Dictionary ConsumeShape
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)34);
            godot_variant answered = default;
            NetwThunks.Call1(_bindGetDictFact, Checked, in slot0, ref answered);
            slot0.Dispose();
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)34);
            godot_variant slot1 = VariantUtils.CreateFromDictionary(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetDictFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    /// <summary>
    /// Acknowledged transitions the owner reached a fingerprint verdict on, the
    /// denominator <see cref="NetwPredictStats.FpMismatches"/> is unreadable
    /// without. Every acknowledged transition counts here, because authority
    /// sends the fingerprint of the state its own replay produced alongside the
    /// acknowledgement it answers.
    /// </summary>
    public long FpVerified
    {
        get
        {
            int slot0 = 35;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 35;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Acknowledged transitions whose prediction fingerprinted unequal to the
    /// authority state, counted out of
    /// <see cref="NetwPredictStats.FpVerified"/>. On a run where every
    /// antecedent of the recurrence matched this stays zero, so a nonzero count
    /// names a broken antecedent rather than a tolerance that wants widening.
    /// The verdict is the correction trigger for a transition labeled
    /// <see cref="NetwPredictJournal.Domain.InDomain"/>, and a report for one
    /// that is not. Which label a transition receives is decided by the
    /// entity's selection through <see cref="NetwEntity.Simulation"/>, so an
    /// entity that selects nothing is compared against its tolerance. It is the
    /// trigger only where it arrives in time to be one. The verdict rides the
    /// acknowledgement lane while the comparison runs when the authoritative
    /// state arrives, so a transition compared before its acknowledgement is
    /// judged by tolerance and this counter reports a divergence nothing acted
    /// on. A set that ships whole rows can be judged on arrival. A
    /// <see cref="NetwPropertyConfig.Masked"/> set cannot, because a masked
    /// frame carries only the fields that changed and the authority row it
    /// belongs to cannot be fingerprinted from it. Read this counter as what
    /// the peers disagreed about, never as what was corrected.
    /// </summary>
    public long FpMismatches
    {
        get
        {
            int slot0 = 36;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 36;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// The first transition <see cref="NetwPredictStats.FpMismatches"/>
    /// counted, or <c>-1</c> while none has. This is the transition to inspect,
    /// since every later mismatch may be the propagation of this one.
    /// </summary>
    public long FirstDivergentTransition
    {
        get
        {
            int slot0 = 37;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 37;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Rows whose pre-state did not chain from the preceding post-state and
    /// carried no operator provenance. Any nonzero value names an
    /// out-of-transition write.
    /// </summary>
    public long ChainBreaks
    {
        get
        {
            int slot0 = 38;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 38;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Transitions authority reached a verdict on for the owner's claimed
    /// post-state, the denominator
    /// <see cref="NetwPredictStats.ClientMismatches"/> is unreadable without.
    /// The authority-side mirror of <see cref="NetwPredictStats.FpVerified"/>.
    /// Authority judges a claim only once its own row for that transition has
    /// closed, so a claim that arrives before authority has run the transition
    /// waits rather than counting.
    /// </summary>
    public long ClientFpVerified
    {
        get
        {
            int slot0 = 39;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 39;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Transitions where the owner's claimed post-state disagreed with the one
    /// authority reached, counted out of
    /// <see cref="NetwPredictStats.ClientFpVerified"/> and reported through
    /// <see cref="NetwMultiplayer.PredictOwnerDivergence"/>. This counts what
    /// authority found, never what it did about it. Authority pushes nothing
    /// back on the strength of a mismatch, so a run of these is evidence for a
    /// game to weigh rather than a correction already applied.
    /// </summary>
    public long ClientMismatches
    {
        get
        {
            int slot0 = 40;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 40;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetNamesFact =
        NetwApi.MethodBind("NetwPredictStats", "get_names_fact", 647634434UL);

    private static readonly IntPtr _bindSetNamesFact =
        NetwApi.MethodBind("NetwPredictStats", "set_names_fact", 3353661094UL);

    /// <summary>
    /// The selection this engine last committed through
    /// <see cref="NetwEntity.Simulation"/>, by entity id, sorted. Sorted
    /// because the roster is an antecedent of the fingerprint both peers
    /// compute, and two peers that agree on the members but not on their order
    /// would disagree on the digest.
    /// </summary>
    public string[] IslandMembers
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)41);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindGetNamesFact,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            string[] result =
                VariantUtils.ConvertAsPackedStringArrayToSystemArray(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)41);
            godot_variant slot1 =
                VariantUtils.CreateFromPackedStringArray(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetNamesFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    /// <summary>
    /// The subset of <see cref="NetwPredictStats.IslandMembers"/> this peer
    /// steps locally rather than displaying as a received proxy.
    /// </summary>
    public string[] SimulatedMembers
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)42);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindGetNamesFact,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            string[] result =
                VariantUtils.ConvertAsPackedStringArrayToSystemArray(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)42);
            godot_variant slot1 =
                VariantUtils.CreateFromPackedStringArray(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetNamesFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    /// <summary>
    /// Joint passes this group has run, one per tick whose floor moved. A group
    /// coalesces every basis it received into one pass, so this counts ticks
    /// that replayed rather than authoritative rows that arrived.
    /// </summary>
    public long JointPasses
    {
        get
        {
            int slot0 = 43;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 43;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Transitions replayed per joint pass, as depth -&gt; passes. The span a
    /// pass covered, which is not the deepest single member re-run: a member
    /// the pass skipped every transition of contributes zero to that depth
    /// while contributing the full span here.
    /// </summary>
    public Godot.Collections.Dictionary JointDepth
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)44);
            godot_variant answered = default;
            NetwThunks.Call1(_bindGetDictFact, Checked, in slot0, ref answered);
            slot0.Dispose();
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)44);
            godot_variant slot1 = VariantUtils.CreateFromDictionary(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetDictFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    /// <summary>
    /// The transition the last joint pass restored its members to, or -1 before
    /// a pass has run. Published with
    /// <see cref="NetwPredictStats.JointPresent"/> because the two bound the
    /// replay a consumer is watching, and a consumer that had to infer them
    /// would be reading the loop's own state to do it.
    /// </summary>
    public long JointFloor
    {
        get
        {
            int slot0 = 45;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 45;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// The transition the last joint pass replayed forward to, or -1 before a
    /// pass has run.
    /// </summary>
    public long JointPresent
    {
        get
        {
            int slot0 = 46;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 46;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Members the last joint pass stepped, lingering ones included.
    /// </summary>
    public long JointMembers
    {
        get
        {
            int slot0 = 47;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 47;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Cells the joint pass drove from a relayed command.
    /// </summary>
    public long CellsRelayed
    {
        get
        {
            int slot0 = 48;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 48;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Cells the joint pass drove from a local predictor standing in for an
    /// author whose command never arrived.
    /// </summary>
    public long CellsSubstituted
    {
        get
        {
            int slot0 = 49;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 49;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// What moved the floor, as source -&gt; moves.
    /// <code>
    /// Dictionary
    /// ┠╴ack     int  an acknowledgement lane row
    /// ┠╴state   int  an authoritative state row
    /// ┠╴relay   int  a relayed command older than the present
    /// ┖╴epoch   int  an epoch bump nothing replays across
    /// </code>
    /// </summary>
    public Godot.Collections.Dictionary FloorMovesBySource
    {
        get
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)50);
            godot_variant answered = default;
            NetwThunks.Call1(_bindGetDictFact, Checked, in slot0, ref answered);
            slot0.Dispose();
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromInt((long)50);
            godot_variant slot1 = VariantUtils.CreateFromDictionary(value);
            godot_variant answered = default;
            NetwThunks.Call2(
                _bindSetDictFact,
                Checked,
                in slot0,
                in slot1,
                ref answered);
            slot0.Dispose();
            slot1.Dispose();
            answered.Dispose();
        }
    }

    /// <summary>
    /// Passes that found a basis older than history and snapped to the newest
    /// recorded state instead of replaying.
    /// </summary>
    public long HealSnaps
    {
        get
        {
            int slot0 = 51;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 51;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    /// <summary>
    /// Members held past their tenure because the group's replay horizon has
    /// not passed their departure yet.
    /// </summary>
    public long LingerHeld
    {
        get
        {
            int slot0 = 52;
            long answered = default;
            NetwThunks.Ptrcall1_Int_Long(
                _bindGetIntFact,
                Checked,
                in slot0,
                ref answered);
            return answered;
        }
        set
        {
            int slot0 = 52;
            long slot1 = value;
            long discarded = default;
            NetwThunks.Ptrcall2_Int_Long_Long(
                _bindSetIntFact,
                Checked,
                in slot0,
                in slot1,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindToDictionary =
        NetwApi.MethodBind("NetwPredictStats", "to_dictionary", 3102165223UL);

    /// <summary>
    /// Returns every fact on this object, by name, for an instrument that
    /// serializes rather than reads one thing. Built from the same table every
    /// property getter reads from, so a fact that exists on
    /// <see cref="NetwPredictStats"/> is in the returned
    /// <see cref="Godot.Collections.Dictionary"/> by existing, with no second
    /// list to keep in step.
    /// </summary>
    public Godot.Collections.Dictionary ToDictionary()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindToDictionary, Checked, ref answered);
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }
}
