// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// Categorical outcome of a server probe.
/// </summary>
/// <remarks>
/// <c>NetwConnector.probe</c> returns one, and <c>NetwServerBrowser</c> caches
/// the latest one per target so a browser row can render before anyone commits
/// to joining. A probe never throws and never half-returns: every route out of
/// it, including a null target and a transport that cannot probe at all, ends
/// at one <see cref="NetwProbeResult.StatusEnum.Ok"/> ..
/// <see cref="NetwProbeResult.StatusEnum.Incompatible"/> value, so a caller
/// branches on <see cref="NetwProbeResult.Status"/> rather than on whether it
/// got a result. <see cref="NetwProbeResult.Status"/> decides which of the
/// other members carries anything. Only
/// <see cref="NetwProbeResult.StatusEnum.Ok"/> and
/// <see cref="NetwProbeResult.StatusEnum.Incompatible"/> carry an
/// <see cref="NetwProbeResult.Info"/>, only
/// <see cref="NetwProbeResult.StatusEnum.Ok"/> carries a meaningful
/// <see cref="NetwProbeResult.LatencyMs"/>, and
/// <see cref="NetwProbeResult.Message"/> is diagnostic detail rather than text
/// to show a player.
/// <code>
/// var result := await NetwConnector.of(api).probe(target)
/// if result.is_ok():
///     print("%d/%d players, %d ms" % [
///         result.info.players, result.info.max_players, result.latency_ms,
///     ])
/// elif result.status == NetwProbeResult.STATUS_INCOMPATIBLE:
///     # info survives here, so the row can still show who is on the server.
///     show_banner("That server runs a different build.")
/// </code>
/// <para>
/// The seven static factories are the only way to get a result whose status and
/// payload agree, and a <see cref="NetwTransport"/> that returns a probe at all
/// returns one of them.
/// </para>
/// </remarks>
public sealed class NetwProbeResult : NetwRefCounted
{
    public NetwProbeResult(IntPtr native) : base(native)
    {
    }

    public static NetwProbeResult Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwProbeResult(native);
    }

    public static NetwProbeResult From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    public enum StatusEnum : long
    {
        /// <summary>
        /// The server returned and this build may join it.
        /// <see cref="NetwProbeResult.IsOk"/> tests for exactly this.
        /// </summary>
        Ok = 0,
        /// <summary>
        /// The connection or the peer authentication failed before the server
        /// replied.
        /// </summary>
        Unreachable = 1,
        /// <summary>
        /// Nothing came back inside the probe window.
        /// </summary>
        Timeout = 2,
        /// <summary>
        /// The transport cannot probe, so the server's state is unknown rather
        /// than bad.
        /// </summary>
        Unsupported = 3,
        /// <summary>
        /// The server returned and rejected, being full or rate limiting
        /// probes.
        /// </summary>
        Busy = 4,
        /// <summary>
        /// The probe itself failed, with <see cref="NetwProbeResult.Message"/>
        /// naming the step.
        /// </summary>
        Error = 5,
        /// <summary>
        /// The server returned with a build this client cannot join, and
        /// <see cref="NetwProbeResult.Info"/> survives so a row can still be
        /// rendered.
        /// </summary>
        Incompatible = 6,
    }

    private static readonly IntPtr _bindGetStatus =
        NetwApi.MethodBind("NetwProbeResult", "get_status", 2112352124UL);

    private static readonly IntPtr _bindSetStatus =
        NetwApi.MethodBind("NetwProbeResult", "set_status", 1576803290UL);

    /// <summary>
    /// The outcome category, and the member every caller branches on. It
    /// defaults to <see cref="NetwProbeResult.StatusEnum.Unsupported"/>, so a
    /// bare <c>new()</c> reads as "nothing was asked" rather than as a failure.
    /// </summary>
    public NetwProbeResult.StatusEnum Status
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetStatus, Checked, ref answered);
            return (NetwProbeResult.StatusEnum)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetStatus,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetInfo =
        NetwApi.MethodBind("NetwProbeResult", "get_info", 3880981058UL);

    private static readonly IntPtr _bindSetInfo =
        NetwApi.MethodBind("NetwProbeResult", "set_info", 1251535023UL);

    /// <summary>
    /// What the server advertised about itself, or <c>null</c> when it never
    /// returned. Carried by <see cref="NetwProbeResult.StatusEnum.Ok"/> and
    /// <see cref="NetwProbeResult.StatusEnum.Incompatible"/>, and by nothing
    /// else.
    /// </summary>
    public NetwServerInfo Info
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(_bindGetInfo, Checked, ref answered);
            return NetwServerInfo.Adopt(answered);
        }
        set
        {
            IntPtr slot0 = value?.Native ?? IntPtr.Zero;
            long discarded = default;
            NetwThunks.Ptrcall1_IntPtr_Long(
                _bindSetInfo,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetLatencyMs =
        NetwApi.MethodBind("NetwProbeResult", "get_latency_ms", 3905245786UL);

    private static readonly IntPtr _bindSetLatencyMs =
        NetwApi.MethodBind("NetwProbeResult", "set_latency_ms", 1286410249UL);

    /// <summary>
    /// The probe round trip in milliseconds, or <c>-1</c> when the result came
    /// from a directory listing instead of a round trip. Meaningful only under
    /// <see cref="NetwProbeResult.StatusEnum.Ok"/>.
    /// </summary>
    public long LatencyMs
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetLatencyMs, Checked, ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetLatencyMs,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetMessage =
        NetwApi.MethodBind("NetwProbeResult", "get_message", 201670096UL);

    private static readonly IntPtr _bindSetMessage =
        NetwApi.MethodBind("NetwProbeResult", "set_message", 83702148UL);

    /// <summary>
    /// Diagnostic detail about why the probe ended the way it did. It names the
    /// failing step for a log, so it is not player-facing text.
    /// </summary>
    public string Message
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetMessage, Checked, ref answered);
            string result = VariantUtils.ConvertToString(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromString(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetMessage, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindOk =
        NetwApi.MethodBind("NetwProbeResult", "ok", 1547152133UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Ok"/> result advertising
    /// <paramref name="info"/>, measured at <paramref name="latencyMs"/>. A
    /// result discovered through a lobby directory rather than a round trip
    /// passes <c>-1</c>, which is how <c>NetwServerBrowser</c> marks a row it
    /// has no ping for.
    /// </summary>
    public static NetwProbeResult Ok(NetwServerInfo info, long latencyMs = 0)
    {
        IntPtr slot0 = info?.Native ?? IntPtr.Zero;
        long slot1 = latencyMs;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_Long_IntPtr(
            _bindOk,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwProbeResult.Adopt(answered);
    }

    private static readonly IntPtr _bindUnreachable =
        NetwApi.MethodBind("NetwProbeResult", "unreachable", 2096380847UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Unreachable"/> result
    /// carrying <paramref name="message"/>. The connection or the peer
    /// authentication failed before any server reply.
    /// </summary>
    public static NetwProbeResult Unreachable(string message = "")
    {
        godot_variant slot0 = VariantUtils.CreateFromString(message);
        godot_variant answered = default;
        NetwThunks.Call1(_bindUnreachable, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        NetwProbeResult result =
            NetwProbeResult.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindTimeout =
        NetwApi.MethodBind("NetwProbeResult", "timeout", 2096380847UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Timeout"/> result
    /// carrying <paramref name="message"/>. The probe reached the wire and
    /// nothing came back inside the window.
    /// </summary>
    public static NetwProbeResult Timeout(string message = "")
    {
        godot_variant slot0 = VariantUtils.CreateFromString(message);
        godot_variant answered = default;
        NetwThunks.Call1(_bindTimeout, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        NetwProbeResult result =
            NetwProbeResult.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindUnsupported =
        NetwApi.MethodBind("NetwProbeResult", "unsupported", 649969015UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Unsupported"/> result.
    /// This is what a <see cref="NetwTransport"/> returns when it has no cheap
    /// way to ask, so a caller reads it as "unknown", never as "down".
    /// </summary>
    public static NetwProbeResult Unsupported()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindUnsupported, IntPtr.Zero, ref answered);
        return NetwProbeResult.Adopt(answered);
    }

    private static readonly IntPtr _bindBusy =
        NetwApi.MethodBind("NetwProbeResult", "busy", 2096380847UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Busy"/> result carrying
    /// <paramref name="message"/>. The server returned and rejected: it is
    /// full, or the probe arrived outside its rate window.
    /// </summary>
    public static NetwProbeResult Busy(string message = "")
    {
        godot_variant slot0 = VariantUtils.CreateFromString(message);
        godot_variant answered = default;
        NetwThunks.Call1(_bindBusy, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        NetwProbeResult result =
            NetwProbeResult.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindError =
        NetwApi.MethodBind("NetwProbeResult", "error", 2096380847UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Error"/> result carrying
    /// <paramref name="message"/>. The probe itself went wrong, rather than the
    /// server returning something.
    /// </summary>
    public static NetwProbeResult Error(string message = "")
    {
        godot_variant slot0 = VariantUtils.CreateFromString(message);
        godot_variant answered = default;
        NetwThunks.Call1(_bindError, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        NetwProbeResult result =
            NetwProbeResult.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindIncompatible =
        NetwApi.MethodBind("NetwProbeResult", "incompatible", 2284208957UL);

    /// <summary>
    /// Returns a <see cref="NetwProbeResult.StatusEnum.Incompatible"/> result
    /// carrying <paramref name="message"/>. The server returned with a
    /// <see cref="NetwServerInfo.AppId"/> or
    /// <see cref="NetwServerInfo.Version"/> this build cannot join, so
    /// <paramref name="info"/> is kept: a browser row still has something to
    /// show even though the join would be rejected.
    /// </summary>
    public static NetwProbeResult Incompatible(
        NetwServerInfo info = null,
        string message = "")
    {
        godot_variant slot0 =
            VariantUtils.CreateFromGodotObjectPtr(info?.Native ?? IntPtr.Zero);
        godot_variant slot1 = VariantUtils.CreateFromString(message);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindIncompatible,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        NetwProbeResult result =
            NetwProbeResult.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindIsOk =
        NetwApi.MethodBind("NetwProbeResult", "is_ok", 36873697UL);

    /// <summary>
    /// Returns <c>true</c> when <see cref="NetwProbeResult.Status"/> is
    /// <see cref="NetwProbeResult.StatusEnum.Ok"/>, which is the one status
    /// that says the server returned and this build may join it.
    /// </summary>
    public bool IsOk()
    {
        byte answered = default;
        NetwThunks.Ptrcall0_Byte(_bindIsOk, Checked, ref answered);
        return answered != 0;
    }
}
