// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// The property face of <see cref="NetwMemberConfig"/>: one fluent declaration
/// that decides how a script variable travels for the rest of its life.
/// </summary>
/// <remarks>
/// Marking a field with <see cref="NetwPropertyConfig.State"/>,
/// <see cref="NetwPropertyConfig.Input"/>, or
/// <see cref="NetwPropertyConfig.Broadcast"/> enrolls it in one of the script's
/// per-tick sets, and from then on the session's sync pump ships every change
/// automatically. Writing the variable is the whole job, there is no send call
/// in the gameplay code.
/// <code>
/// func _init() -&gt; void:
///     Netw.configure_property(self, &amp;"position").state().quantize(pos_q)
///     Netw.configure_property(self, &amp;"move_dir").input()
///     Netw.configure_property(self, &amp;"aim_dir").broadcast()
///
/// func _physics_process(_dt: float) -&gt; void:
///     move_dir = Input.get_vector("left", "right", "up", "down")
///     aim_dir = (get_global_mouse_position() - position).normalized()
///     # no send call: the next pump tick ships every marked change
/// </code>
/// <para>
/// Pick the kind by returning who owns the value, who sees it, and whether the
/// server polices it. <see cref="NetwPropertySet.RecordEnum"/> holds the
/// comparison table. A field with no kind mark rides no per-tick set and syncs
/// only when <see cref="Netw.SyncProperty"/> pushes it explicitly.
/// <see cref="NetwPropertyConfig.Volatile"/>,
/// <see cref="NetwPropertyConfig.Retained"/>,
/// <see cref="NetwPropertyConfig.Epsilon"/>, and
/// <see cref="NetwPropertyConfig.Persisted"/> refine one property.
/// <see cref="NetwPropertyConfig.EveryTick"/>,
/// <see cref="NetwPropertyConfig.OnChange"/>,
/// <see cref="NetwPropertyConfig.Heartbeat"/>,
/// <see cref="NetwPropertyConfig.Windowed"/>,
/// <see cref="NetwPropertyConfig.Audience"/>, and
/// <see cref="NetwPropertyConfig.Masked"/> write through to the script's whole
/// <see cref="NetwPropertySet"/> from any member, so the last member to name a
/// knob owns it. <b>The chain downgrades to the base type.</b>
/// <see cref="NetwMemberConfig.CallLocal"/> and
/// <see cref="NetwMemberConfig.CallRemote"/> are not re-declared here, and
/// neither is any other base verb: a bound method records one return type, so a
/// chain that passes through a base verb returns a
/// <see cref="NetwMemberConfig"/> from that point on even though the object is
/// still this <see cref="NetwPropertyConfig"/>. Property-only verbs therefore
/// come LAST in a chain. The local-call axis has no meaning for a property,
/// since a property assignment is local first by construction.
/// </para>
/// </remarks>
public sealed class NetwPropertyConfig : NetwMemberConfig
{
    public NetwPropertyConfig(IntPtr native) : base(native)
    {
    }

    public new static NetwPropertyConfig Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwPropertyConfig(native);
    }

    public new static NetwPropertyConfig From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    /// <summary>
    /// The spelling of an integer set-level knob no member has written yet,
    /// which is what <see cref="NetwPropertyConfig.SetTrigger"/>,
    /// <see cref="NetwPropertyConfig.SetHeartbeatTicks"/> and
    /// <see cref="NetwPropertyConfig.SetWindow"/> hold until one does. It is
    /// the absence of a declaration rather than a value, so a reader tests
    /// against it instead of using it.
    /// </summary>
    public const long Unset = -1;

    private static readonly IntPtr _bindGetLane =
        NetwApi.MethodBind("NetwPropertyConfig", "get_lane", 3235490189UL);

    private static readonly IntPtr _bindSetLane =
        NetwApi.MethodBind("NetwPropertyConfig", "set_lane", 298003126UL);

    /// <summary>
    /// The field's delivery lane: <see cref="NetwPropertySet.Lane.Volatile"/>
    /// freshest wins, <see cref="NetwPropertySet.Lane.Retained"/> reliable on
    /// change. Declared through <see cref="NetwPropertyConfig.Volatile"/> and
    /// <see cref="NetwPropertyConfig.Retained"/>, and written by every kind
    /// mark.
    /// </summary>
    public NetwPropertySet.Lane Lane
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetLane, Checked, ref answered);
            return (NetwPropertySet.Lane)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetLane,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetSetAudience =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_set_audience",
            2118769895UL);

    private static readonly IntPtr _bindSetSetAudience =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_set_audience",
            1963165040UL);

    /// <summary>
    /// The script set's <see cref="NetwPropertySet.Audience"/>. Written by
    /// <see cref="NetwPropertyConfig.Audience"/> and by the
    /// <see cref="NetwPropertyConfig.Input"/> preset.
    /// </summary>
    public NetwPropertySet.AudienceEnum SetAudience
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetSetAudience,
                Checked,
                ref answered);
            return (NetwPropertySet.AudienceEnum)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetSetAudience,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetPropertyClass =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_property_class",
            1912487024UL);

    private static readonly IntPtr _bindSetPropertyClass =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_property_class",
            3837869372UL);

    /// <summary>
    /// What the value does in the simulation, which decides whether a
    /// reconciliation compares and restores it. Declared through
    /// <see cref="NetwPropertyConfig.Causal"/>,
    /// <see cref="NetwPropertyConfig.Derived"/> and
    /// <see cref="NetwPropertyConfig.Cosmetic"/>.
    /// </summary>
    public NetwPropertySet.PropertyClass PropertyClass
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetPropertyClass,
                Checked,
                ref answered);
            return (NetwPropertySet.PropertyClass)answered;
        }
        set
        {
            long slot0 = (long)value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetPropertyClass,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetIsProperty =
        NetwApi.MethodBind("NetwPropertyConfig", "get_is_property", 36873697UL);

    private static readonly IntPtr _bindSetIsProperty =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_is_property",
            2586408642UL);

    /// <summary>
    /// Always <c>true</c> on a property config, which is how a registry holding
    /// both kinds tells this apart from the plain
    /// <see cref="NetwMemberConfig"/> an RPC or a signal returns when only the
    /// base type is known.
    /// </summary>
    public bool IsProperty
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetIsProperty, Checked, ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetIsProperty,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetIsSpawnState =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_is_spawn_state",
            36873697UL);

    private static readonly IntPtr _bindSetIsSpawnState =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_is_spawn_state",
            2586408642UL);

    /// <summary>
    /// Whether the property's value rides the SPAWN frame and is applied on
    /// every receiving peer before the node enters the tree. Declared through
    /// <see cref="NetwPropertyConfig.OnSpawn"/>.
    /// </summary>
    public bool IsSpawnState
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetIsSpawnState,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetIsSpawnState,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetInStateSet =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_in_state_set",
            36873697UL);

    private static readonly IntPtr _bindSetInStateSet =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_in_state_set",
            2586408642UL);

    /// <summary>
    /// Whether <see cref="NetwPropertyConfig.State"/> marked this property into
    /// its script's state set.
    /// </summary>
    public bool InStateSet
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetInStateSet, Checked, ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetInStateSet,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetInInputSet =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_in_input_set",
            36873697UL);

    private static readonly IntPtr _bindSetInInputSet =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_in_input_set",
            2586408642UL);

    /// <summary>
    /// Whether <see cref="NetwPropertyConfig.Input"/> marked this property into
    /// its script's input set.
    /// </summary>
    public bool InInputSet
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetInInputSet, Checked, ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetInInputSet,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetInBroadcastSet =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_in_broadcast_set",
            36873697UL);

    private static readonly IntPtr _bindSetInBroadcastSet =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_in_broadcast_set",
            2586408642UL);

    /// <summary>
    /// Whether <see cref="NetwPropertyConfig.Broadcast"/> marked this property
    /// into its script's broadcast set, the trusted display stream outside the
    /// rewind boundary.
    /// </summary>
    public bool InBroadcastSet
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetInBroadcastSet,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetInBroadcastSet,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetEpsilonOverride =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_epsilon_override",
            1740695150UL);

    private static readonly IntPtr _bindSetEpsilonOverride =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_epsilon_override",
            373806689UL);

    /// <summary>
    /// The field's own divergence threshold, or a negative value to inherit the
    /// entity's <see cref="NetwPredictionHandle.DivergenceEpsilon"/>. Declared
    /// through <see cref="NetwPropertyConfig.Epsilon"/>.
    /// </summary>
    public double EpsilonOverride
    {
        get
        {
            double answered = default;
            NetwThunks.Ptrcall0_Double(
                _bindGetEpsilonOverride,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            double slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Double_Long(
                _bindSetEpsilonOverride,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetTeleportAtOverride =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_teleport_at_override",
            1740695150UL);

    private static readonly IntPtr _bindSetTeleportAtOverride =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_teleport_at_override",
            373806689UL);

    /// <summary>
    /// The field's own teleport-tier distance, or a negative value to inherit
    /// the entity's <see cref="NetwPredictionHandle.TeleportThreshold"/>.
    /// Declared through <see cref="NetwPropertyConfig.TeleportAt"/>.
    /// </summary>
    public double TeleportAtOverride
    {
        get
        {
            double answered = default;
            NetwThunks.Ptrcall0_Double(
                _bindGetTeleportAtOverride,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            double slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Double_Long(
                _bindSetTeleportAtOverride,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetSetTrigger =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_set_trigger",
            3905245786UL);

    private static readonly IntPtr _bindSetSetTrigger =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_set_trigger",
            1286410249UL);

    /// <summary>
    /// The script set's <see cref="NetwPropertySet.Trigger"/>, or
    /// <see cref="NetwPropertyConfig.Unset"/>. Written by
    /// <see cref="NetwPropertyConfig.EveryTick"/> and
    /// <see cref="NetwPropertyConfig.OnChange"/>, and by all three kind marks.
    /// </summary>
    public long SetTrigger
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetSetTrigger, Checked, ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetSetTrigger,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetSetEveryTickInterval =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_set_every_tick_interval",
            1740695150UL);

    private static readonly IntPtr _bindSetSetEveryTickInterval =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_set_every_tick_interval",
            373806689UL);

    /// <summary>
    /// The script set's every-tick throttle in seconds, or a negative value
    /// when unset. Written by <see cref="NetwPropertyConfig.EveryTick"/>.
    /// </summary>
    public double SetEveryTickInterval
    {
        get
        {
            double answered = default;
            NetwThunks.Ptrcall0_Double(
                _bindGetSetEveryTickInterval,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            double slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Double_Long(
                _bindSetSetEveryTickInterval,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetSetHeartbeatTicks =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_set_heartbeat_ticks",
            3905245786UL);

    private static readonly IntPtr _bindSetSetHeartbeatTicks =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_set_heartbeat_ticks",
            1286410249UL);

    /// <summary>
    /// The script set's heartbeat interval in ticks, or
    /// <see cref="NetwPropertyConfig.Unset"/>. Written by
    /// <see cref="NetwPropertyConfig.Heartbeat"/>.
    /// </summary>
    public long SetHeartbeatTicks
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(
                _bindGetSetHeartbeatTicks,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetSetHeartbeatTicks,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetSetWindow =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_set_window",
            3905245786UL);

    private static readonly IntPtr _bindSetSetWindow =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_set_window",
            1286410249UL);

    /// <summary>
    /// The script set's <see cref="NetwPropertySet.Window"/>, or
    /// <see cref="NetwPropertyConfig.Unset"/>. Written by
    /// <see cref="NetwPropertyConfig.Windowed"/>.
    /// </summary>
    public long SetWindow
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetSetWindow, Checked, ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetSetWindow,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetSetMasked =
        NetwApi.MethodBind("NetwPropertyConfig", "get_set_masked", 36873697UL);

    private static readonly IntPtr _bindSetSetMasked =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_set_masked",
            2586408642UL);

    /// <summary>
    /// The script set's <see cref="NetwPropertySet.Masked"/>. Written by
    /// <see cref="NetwPropertyConfig.Masked"/>.
    /// </summary>
    public bool SetMasked
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetSetMasked, Checked, ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetSetMasked,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetConvergeStiffness =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_converge_stiffness",
            1740695150UL);

    private static readonly IntPtr _bindSetConvergeStiffness =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_converge_stiffness",
            373806689UL);

    /// <summary>
    /// How firmly a recovery pulls this value toward the authoritative one
    /// rather than writing it outright, or <c>0.0</c> to write it. Declared
    /// through <see cref="NetwPropertyConfig.Converge"/>.
    /// </summary>
    public double ConvergeStiffness
    {
        get
        {
            double answered = default;
            NetwThunks.Ptrcall0_Double(
                _bindGetConvergeStiffness,
                Checked,
                ref answered);
            return answered;
        }
        set
        {
            double slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Double_Long(
                _bindSetConvergeStiffness,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetCarryChannel =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_carry_channel",
            2002593661UL);

    private static readonly IntPtr _bindSetCarryChannel =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_carry_channel",
            3304788590UL);

    /// <summary>
    /// The replicated channel a recovery advances this value along, or empty
    /// when it is restored at the acknowledged value. Declared through
    /// <see cref="NetwPropertyConfig.CarryAlong"/>.
    /// </summary>
    public StringName CarryChannel
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetCarryChannel, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetCarryChannel,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetExplicitTeleportOnly =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_explicit_teleport_only",
            36873697UL);

    private static readonly IntPtr _bindSetExplicitTeleportOnly =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_explicit_teleport_only",
            2586408642UL);

    /// <summary>
    /// Whether <see cref="NetwPropertyConfig.TeleportOnly"/> restricted the
    /// field to teleport-tier recoveries.
    /// </summary>
    public bool ExplicitTeleportOnly
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetExplicitTeleportOnly,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetExplicitTeleportOnly,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetExplicitReconcileOnly =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "get_explicit_reconcile_only",
            36873697UL);

    private static readonly IntPtr _bindSetExplicitReconcileOnly =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "set_explicit_reconcile_only",
            2586408642UL);

    /// <summary>
    /// Whether <see cref="NetwPropertyConfig.ReconcileOnly"/> excluded the
    /// field from triggering a correction on its own.
    /// </summary>
    public bool ExplicitReconcileOnly
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetExplicitReconcileOnly,
                Checked,
                ref answered);
            return answered != 0;
        }
        set
        {
            byte slot0 = value ? (byte)1 : (byte)0;
            long discarded = default;
            NetwThunks.Ptrcall1_Byte_Long(
                _bindSetExplicitReconcileOnly,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindState =
        NetwApi.MethodBind("NetwPropertyConfig", "state", 1162647290UL);

    /// <summary>
    /// The server owns this value, every observer sees it, and hit detection
    /// can rewind it. The authoritative kind, the body pose the whole game
    /// agrees on. See <see cref="NetwPropertySet.RecordEnum"/> to compare
    /// kinds.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_property(self, &amp;"position").state().quantize(pos_q)
    ///
    /// func _physics_process(dt: float) -&gt; void:
    ///     position += velocity * dt
    ///     # on the server that write is enough: the pump tick replicates it,
    ///     # and every client's copy of this node follows
    /// </code>
    /// <para>
    /// Writes <see cref="NetwPropertyConfig.InStateSet"/>, the
    /// <see cref="NetwPropertySet.Lane.Volatile"/>
    /// <see cref="NetwPropertyConfig.Lane"/>, and a
    /// <see cref="NetwPropertyConfig.SetTrigger"/> of
    /// <see cref="NetwPropertySet.TriggerEnum.OnChange"/>, and nothing else, so
    /// it leaves the audience public. A state field is also the reconciliation
    /// anchor: a client predicting this entity is corrected against the
    /// server's stream, within the tolerance
    /// <see cref="NetwPropertyConfig.Epsilon"/> grants.
    /// </para>
    /// </summary>
    public NetwPropertyConfig State()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindState, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindInput =
        NetwApi.MethodBind("NetwPropertyConfig", "input", 1162647290UL);

    /// <summary>
    /// The controller owns this value, only the server sees it, and the server
    /// re-runs it to verify. The controls kind, the command stream a client is
    /// trusted to author but never to resolve. See
    /// <see cref="NetwPropertySet.RecordEnum"/> to compare kinds.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_property(self, &amp;"move_dir").input()
    ///
    /// func _physics_process(dt: float) -&gt; void:
    ///     if entity.is_controlled_locally:
    ///         move_dir = Input.get_vector("left", "right", "up", "down")
    ///     # both peers run this: the client predicts, the server decides
    ///     velocity = move_dir * SPEED
    /// </code>
    /// <para>
    /// Writes <see cref="NetwPropertyConfig.InInputSet"/>, the
    /// <see cref="NetwPropertySet.Lane.Volatile"/>
    /// <see cref="NetwPropertyConfig.Lane"/>, a
    /// <see cref="NetwPropertyConfig.SetTrigger"/> of
    /// <see cref="NetwPropertySet.TriggerEnum.OnChange"/>, and the
    /// <see cref="NetwPropertySet.AudienceEnum.ServerOnly"/>
    /// <see cref="NetwPropertyConfig.SetAudience"/>. That last axis is what
    /// makes it a command stream rather than a public one, and it is the only
    /// kind mark that writes it. An input set is windowed by default so a lost
    /// tick heals from a redundant sample instead of a retransmit.
    /// <see cref="NetwPropertyConfig.Windowed"/> resizes that window. An input
    /// column is canonicalized and shipped, never recovered, so only its key,
    /// its quantizer and its type reach the engine. A recovery mark written
    /// onto an input column, a carry rule or a teleport distance among them, is
    /// read and discarded rather than rejected, because the input lane has no
    /// ladder that could read it.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Input()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindInput, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindBroadcast =
        NetwApi.MethodBind("NetwPropertyConfig", "broadcast", 1162647290UL);

    /// <summary>
    /// The controller owns this value, every observer sees it, and nobody
    /// checks it. The display kind, for cosmetic streams like an aim arrow or a
    /// look direction where being wrong costs nothing, so the server keeps no
    /// history and never rewinds it. See
    /// <see cref="NetwPropertySet.RecordEnum"/> to compare kinds.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_property(self, &amp;"aim_dir").broadcast()
    ///
    /// func _process(_dt: float) -&gt; void:
    ///     aim_dir = (get_global_mouse_position() - position).normalized()
    ///     # nothing else to do: each pump tick broadcasts the change and
    ///     # every other player's copy of this node updates its arrow
    /// </code>
    /// <para>
    /// Writes <see cref="NetwPropertyConfig.InBroadcastSet"/>, the
    /// <see cref="NetwPropertySet.Lane.Volatile"/>
    /// <see cref="NetwPropertyConfig.Lane"/>, and a
    /// <see cref="NetwPropertyConfig.SetTrigger"/> of
    /// <see cref="NetwPropertySet.TriggerEnum.OnChange"/>, and nothing else.
    /// Add <see cref="NetwPropertyConfig.Masked"/> when many viewers watch the
    /// same entity, so each one receives only the fields that changed for them.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Broadcast()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindBroadcast, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindVolatile =
        NetwApi.MethodBind("NetwPropertyConfig", "volatile", 1162647290UL);

    /// <summary>
    /// Routes the field onto the <see cref="NetwPropertySet.Lane.Volatile"/>
    /// freshest-wins <see cref="NetwPropertyConfig.Lane"/>, right for a value
    /// that changes continuously, where a lost sample is superseded by the next
    /// tick anyway. The default lane.
    /// </summary>
    public NetwPropertyConfig Volatile()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindVolatile, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindRetained =
        NetwApi.MethodBind("NetwPropertyConfig", "retained", 1162647290UL);

    /// <summary>
    /// Routes the field onto the <see cref="NetwPropertySet.Lane.Retained"/>
    /// reliable-on-change <see cref="NetwPropertyConfig.Lane"/>, right for a
    /// discrete value that changes rarely and must never miss a change.
    /// <code>
    /// # a dropped "stunned = true" would desync forever, so it rides reliably
    /// Netw.configure_property(self, &amp;"stunned").state().retained()
    /// </code>
    /// <para>
    /// Rejected on a PREDICTED entity's state, whatever the value is worth:
    /// predicted state has to be volatile for a timeline snapshot to arrive
    /// atomically, and a retained field would land on its own schedule and be
    /// compared against a row no single tick returns for.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Retained()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindRetained, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindCausal =
        NetwApi.MethodBind("NetwPropertyConfig", "causal", 1162647290UL);

    /// <summary>
    /// Marks the value an antecedent of the simulation, one the next step reads
    /// from, so a reconciliation compares it and restores it. The default
    /// <see cref="NetwPropertyConfig.PropertyClass"/>.
    /// <code>
    /// # the body integrates from velocity, so a restore that skipped it would
    /// # rebase the position and then immediately drift away from it again
    /// Netw.configure_property(self, &amp;"velocity").state().causal()
    /// </code>
    /// <para>
    /// See <see cref="NetwPropertySet.PropertyClass"/> to compare classes.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Causal()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindCausal, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindDerived =
        NetwApi.MethodBind("NetwPropertyConfig", "derived", 1162647290UL);

    /// <summary>
    /// Marks the value one the body recomputes from causal fields each step, so
    /// no reconciliation compares it and none is raised on its account. A
    /// recovery still writes it. Restoration is not gated on the class, and a
    /// value the next step recomputes is harmless to write and worth having for
    /// observers in the meantime. What the class buys is the vote. A field the
    /// body recomputes cannot demand a recovery for a disagreement that only
    /// restates one the causal fields already carry.
    /// <code>
    /// # recomputed from velocity every tick, so it decides no correction
    /// Netw.configure_property(self, &amp;"speed").state().derived()
    /// </code>
    /// <para>
    /// See <see cref="NetwPropertySet.PropertyClass"/> to compare classes.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Derived()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindDerived, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindCosmetic =
        NetwApi.MethodBind("NetwPropertyConfig", "cosmetic", 1162647290UL);

    /// <summary>
    /// Marks the value display-only, so no reconciliation compares it, exactly
    /// as <see cref="NetwPropertyConfig.Derived"/> does and for the same
    /// reason. A cosmetic field that disagreed would otherwise correct a
    /// simulation over a value no simulation reads. A recovery still writes it,
    /// so observers see the authoritative value. The two classes differ in what
    /// they tell a reader rather than in what the kernel does.
    /// <see cref="NetwPropertyConfig.Derived"/> says the body recomputes the
    /// value, <see cref="NetwPropertyConfig.Cosmetic"/> says nothing simulated
    /// reads it at all.
    /// <code>
    /// Netw.configure_property(self, &amp;"skid_intensity").state().cosmetic()
    /// </code>
    /// <para>
    /// See <see cref="NetwPropertySet.PropertyClass"/> to compare classes.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Cosmetic()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindCosmetic, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConverge =
        NetwApi.MethodBind("NetwPropertyConfig", "converge", 3192356254UL);

    /// <summary>
    /// Pulls the field toward the authoritative value at
    /// <paramref name="stiffness"/> during a recovery instead of writing it
    /// outright, bounded to that one recovery. Writes
    /// <see cref="NetwPropertyConfig.ConvergeStiffness"/>.
    /// <code>
    /// Netw.configure_property(self, &amp;"heading").state().causal().converge(0.4)
    /// </code>
    /// <para>
    /// A stiffness of <c>0.0</c> restores the value outright, the default. So
    /// does a value whose type has no meaningful midpoint, whatever stiffness
    /// is declared. Converging asks for the error between two values and a
    /// fraction of the way along it, which a boolean, a name or an id does not
    /// have, so such a field is restored outright rather than left uncorrected
    /// or moved to a value neither peer holds.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Converge(double stiffness)
    {
        double slot0 = stiffness;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Double_IntPtr(
            _bindConverge,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindCarryAlong =
        NetwApi.MethodBind("NetwPropertyConfig", "carry_along", 187488283UL);

    /// <summary>
    /// Advances this value along <paramref name="channel"/>, a sibling
    /// replicated field holding its rate, when a recovery restores it. Writes
    /// <see cref="NetwPropertyConfig.CarryChannel"/>. A restore carries
    /// authority's value for the transition it acknowledged, which is already
    /// <see cref="NetwPredictionHandle.AckAgeTicks"/> old by the time it lands,
    /// so a field still moving is written behind where it is. The channel is
    /// what closes that gap, at one constant rate, which is exact only while
    /// that rate holds still across the window. A field that declares nothing
    /// is written at the acknowledged value.
    /// <code>
    /// # the body integrates position from velocity, so a restore advances along it
    /// Netw.configure_property(self, &amp;"position").state().carry_along(&amp;"velocity")
    /// </code>
    /// <para>
    /// <paramref name="channel"/> must name another
    /// <see cref="NetwPropertyConfig.State"/> property of the same entity, and
    /// declaring the pair is also what sorts the two: this field joins the pose
    /// <see cref="NetwPredictionHandle.TeleportThreshold"/> is measured over,
    /// and <paramref name="channel"/> joins the momentum family. A value whose
    /// rate turns, decays, or jumps inside the window wants
    /// <see cref="NetwPropertyConfig.CarryStep"/> instead, and declaring both
    /// on one column is an error that keeps neither. A
    /// <paramref name="channel"/> this entity's state set does not carry
    /// compiles to no projection at all, exactly as declaring none does,
    /// because a channel the set does not ship cannot be read at the same tick
    /// as the field it advances and the pair is not one the engine can honour.
    /// This is a reconciliation declaration, independent of
    /// <see cref="NetwInterpolate.ProjectBy"/>, which decides how a remote
    /// display extrapolates past its newest sample.
    /// </para>
    /// </summary>
    public NetwPropertyConfig CarryAlong(StringName channel)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(channel);
        godot_variant answered = default;
        NetwThunks.Call1(_bindCarryAlong, Checked, in slot0, ref answered);
        slot0.Dispose();
        NetwPropertyConfig result =
            NetwPropertyConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindCarryStep =
        NetwApi.MethodBind("NetwPropertyConfig", "carry_step", 3770852400UL);

    /// <summary>
    /// Advances this value by running <paramref name="step"/> once over each
    /// transition the owner recorded since the acknowledgement. Where
    /// <see cref="NetwPropertyConfig.CarryAlong"/> extrapolates one rate, this
    /// re-runs the part of the simulation that moves this one field, so a rate
    /// that turns, decays or jumps inside the window is followed rather than
    /// averaged. Nothing else is re-simulated and the physics server is never
    /// stepped. <b>The rule must reproduce the whole change the transition made
    /// to this field</b>, and that is what the engine checks it against. So the
    /// verb is for a field whose change the game authors ENTIRELY. A field the
    /// solver also moves cannot be advanced this way, however correct the rule
    /// is about the game's own share: the recovery needs the value the body
    /// actually reached, and the solver's contribution is neither authored here
    /// nor re-runnable, and a physics server that could be re-stepped would not
    /// need this verb at all. Such a rule is rejected and retired, and the
    /// retirement says so. A carry result is accepted only when the rule did
    /// not write the body, reproduced the recorded transitions, returned the
    /// same finite type, and stayed below the teleport threshold. Otherwise
    /// recovery writes the acknowledged value. Declaring both this and
    /// <see cref="NetwPropertyConfig.CarryAlong"/> on one column is an error
    /// and keeps NEITHER. One field, one forward model: the step is for a rate
    /// that varies across the acknowledgement window and the channel for one
    /// that holds still, and no field is both.
    /// <code>
    /// # yes -- a scripted value the solver never touches
    /// Netw.configure_property(self, &amp;"charge").state().carry_step(_carry_charge)
    ///
    /// # no -- the solver moves this too, so its whole change is not yours to
    /// # restate. Measured on a rolling sphere: the game's own term was 1.667 rad/s
    /// # per transition against a realized 0.329, and the rule was RIGHT about the
    /// # 1.667.
    /// Netw.configure_property(self, &amp;"angular_velocity").state() \
    ///         .carry_step(_carry_spin)
    /// </code>
    /// <para>
    /// <see cref="NetwPredictionHandle.Reachability"/> reports whether a
    /// declared rule is live, and why when it is not.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_property(self, &amp;"spin").state().carry_step(_carry_spin)
    ///
    /// func _carry_spin(value: Vector3, ctx: NetwPredictCarryContext) -&gt; Vector3:
    ///     return value + _drive_axis(ctx.state) * ctx.state[&amp;"speed"] * ctx.delta
    /// </code>
    /// </para>
    /// <para>
    /// <paramref name="step"/> may read only its
    /// <see cref="NetwPredictCarryContext"/> and must write nothing. The engine
    /// holds it to that rather than trusting it: a step is replayed against
    /// transitions the owner already recorded and retired once it stops
    /// reproducing them, and a rejected carry writes the acknowledged value
    /// exactly as an undeclared field does.
    /// <see cref="NetwPredictionHandle.FieldRecovery"/> counts both. The rule
    /// is stored per node rather than per script, because a
    /// <see cref="Callable"/> is bound to one body while a property declaration
    /// is shared by every instance of the script that declares it.
    /// <paramref name="step"/> therefore has to be a method or lambda of a
    /// <see cref="Node"/>, which is the body it will advance. A
    /// <paramref name="step"/> that is invalid, or valid but bound to something
    /// that is not a <see cref="Node"/>, is reported through the error channel
    /// and binds nothing, leaving this config exactly as it was. The rule lands
    /// in a per-node overlay, which is keyed by node instance rather than by
    /// <see cref="NetwMemberConfig.ContextScript"/>.
    /// </para>
    /// </summary>
    public NetwPropertyConfig CarryStep(Callable step)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(step);
        godot_variant answered = default;
        NetwThunks.Call1(_bindCarryStep, Checked, in slot0, ref answered);
        slot0.Dispose();
        NetwPropertyConfig result =
            NetwPropertyConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindTeleportOnly =
        NetwApi.MethodBind("NetwPropertyConfig", "teleport_only", 1162647290UL);

    /// <summary>
    /// Restricts the field to teleport-tier recoveries, so an ordinary one
    /// leaves it alone, by writing
    /// <see cref="NetwPropertyConfig.ExplicitTeleportOnly"/>. Right for a value
    /// whose mid-flight rewrite is more disruptive than the drift it would
    /// correct. Recovery cannot write a field marked this way until it promotes
    /// to a full restore. Pair it with
    /// <see cref="NetwPropertyConfig.CarryAlong"/> or
    /// <see cref="NetwPropertyConfig.CarryStep"/> to restore it at the current
    /// state, or with <see cref="NetwPropertyConfig.ReconcileOnly"/> to prevent
    /// its drift from triggering recovery of other fields.
    /// <code>
    /// Netw.configure_property(self, &amp;"angular_velocity").state().teleport_only()
    /// </code>
    /// </summary>
    public NetwPropertyConfig TeleportOnly()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindTeleportOnly, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindEpsilon =
        NetwApi.MethodBind("NetwPropertyConfig", "epsilon", 3192356254UL);

    /// <summary>
    /// Sets this field's own divergence <paramref name="threshold"/>, the
    /// distance its predicted value may drift from the authoritative one before
    /// a correction triggers, in
    /// <see cref="NetwPropertyConfig.EpsilonOverride"/>. A field without one
    /// inherits the entity's
    /// <see cref="NetwPredictionHandle.DivergenceEpsilon"/>. A single scalar
    /// mixes units badly for a body whose state spans meters, radians, and
    /// meters per second, so the field that needs its own tolerance declares it
    /// in its own units.
    /// <code>
    /// Netw.configure_property(self, &amp;"velocity").state().epsilon(0.05)
    /// </code>
    /// <para>
    /// The threshold is the largest error the field is allowed to HOLD, so
    /// <c>0.0</c> means any error at all triggers a correction. That is how an
    /// exact field is declared, and it costs a recovery on every quantization
    /// step, so declare it only for a value whose grid the two peers truly
    /// share. A field that should never trigger is
    /// <see cref="NetwPropertyConfig.ReconcileOnly"/>, not <c>epsilon(INF)</c>.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Epsilon(double threshold)
    {
        double slot0 = threshold;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Double_IntPtr(
            _bindEpsilon,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindTeleportAt =
        NetwApi.MethodBind("NetwPropertyConfig", "teleport_at", 3192356254UL);

    /// <summary>
    /// Sets this field's own teleport-tier <paramref name="distance"/> in
    /// <see cref="NetwPropertyConfig.TeleportAtOverride"/>: the error at which
    /// a recovery stops repairing partially and restores the whole closure
    /// verbatim. A field without one inherits the entity's
    /// <see cref="NetwPredictionHandle.TeleportThreshold"/>. Same argument as
    /// <see cref="NetwPropertyConfig.Epsilon"/>, and the same units problem:
    /// the tier is measured over the fields that can be advanced to the
    /// present, which on a 3D body span metres, radians and radians per second.
    /// One scalar across them compares a rotation rate against a distance, so a
    /// field enrolled in that measurement declares the tier in its own units or
    /// inherits a number that means nothing for it.
    /// <code>
    /// Netw.configure_property(self, &amp;"position").state() \
    ///         .carry_along(&amp;"velocity").teleport_at(3.0)      # metres
    /// Netw.configure_property(self, &amp;"heading").state() \
    ///         .carry_along(&amp;"angular_speed").teleport_at(1.0)  # radians
    /// </code>
    /// <para>
    /// Declaring it also enrols the field in the tier measurement, so a field
    /// with no <see cref="NetwPropertyConfig.CarryAlong"/> channel can still
    /// name the distance past which its own error means the body holds nothing
    /// worth keeping. <c>0.0</c> therefore means every recovery this field
    /// triggers is a teleport.
    /// </para>
    /// </summary>
    public NetwPropertyConfig TeleportAt(double distance)
    {
        double slot0 = distance;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Double_IntPtr(
            _bindTeleportAt,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindReconcileOnly =
        NetwApi.MethodBind(
            "NetwPropertyConfig",
            "reconcile_only",
            1162647290UL);

    /// <summary>
    /// Excludes the field from triggering a correction, while a correction
    /// another field triggers still restores it, by writing
    /// <see cref="NetwPropertyConfig.ExplicitReconcileOnly"/>. Right for a
    /// value whose own drift is tolerable but that must land with the rest of
    /// the closure when one lands. This is the mark a
    /// <see cref="NetwPropertyConfig.Causal"/> field needs to say that. No
    /// class but causal votes in the first place, so adding it to a
    /// <see cref="NetwPropertyConfig.Derived"/> or
    /// <see cref="NetwPropertyConfig.Cosmetic"/> field states an intent the
    /// class already carries.
    /// <code>
    /// Netw.configure_property(self, &amp;"heading").state().reconcile_only()
    /// </code>
    /// </summary>
    public NetwPropertyConfig ReconcileOnly()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindReconcileOnly, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindEveryTick =
        NetwApi.MethodBind("NetwPropertyConfig", "every_tick", 2969492179UL);

    /// <summary>
    /// Sends the whole set every eligible tick whether or not a field changed,
    /// throttled to at most one send per <paramref name="interval"/> seconds.
    /// Writes <see cref="NetwPropertyConfig.SetTrigger"/> and
    /// <see cref="NetwPropertyConfig.SetEveryTickInterval"/>, and so decides
    /// <see cref="NetwPropertySet.Trigger"/> for every field in the set.
    /// <code>
    /// # position changes every tick anyway, change detection is pure overhead
    /// Netw.configure_property(self, &amp;"position").state().every_tick()
    /// </code>
    /// <para>
    /// A second member of the same script that writes the trigger warns,
    /// because that is two call sites disagreeing about one set-level knob.
    /// </para>
    /// </summary>
    public NetwPropertyConfig EveryTick(double interval = 0.0)
    {
        double slot0 = interval;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Double_IntPtr(
            _bindEveryTick,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindOnChange =
        NetwApi.MethodBind("NetwPropertyConfig", "on_change", 1162647290UL);

    /// <summary>
    /// Sends the set only when a field changed since the last send, by writing
    /// <see cref="NetwPropertyConfig.SetTrigger"/>
    /// <see cref="NetwPropertySet.TriggerEnum.OnChange"/>. The default
    /// <see cref="NetwPropertySet.Trigger"/> of every kind mark, and warns on a
    /// second writer exactly as <see cref="NetwPropertyConfig.EveryTick"/>
    /// does.
    /// </summary>
    public NetwPropertyConfig OnChange()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindOnChange, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindHeartbeat =
        NetwApi.MethodBind("NetwPropertyConfig", "heartbeat", 1358280359UL);

    /// <summary>
    /// Re-sends the whole set every <paramref name="ticks"/> ticks even when
    /// nothing changed, so a peer that missed an
    /// <see cref="NetwPropertyConfig.OnChange"/> send converges in bounded
    /// time. Writes <see cref="NetwPropertyConfig.SetHeartbeatTicks"/>, and
    /// warns when a second member of the same script writes it too.
    /// <code>
    /// # a lost "stunned" flip heals within a second at 60 ticks
    /// Netw.configure_property(self, &amp;"stunned").state().heartbeat(60)
    /// </code>
    /// </summary>
    public NetwPropertyConfig Heartbeat(long ticks)
    {
        long slot0 = ticks;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Long_IntPtr(
            _bindHeartbeat,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindWindowed =
        NetwApi.MethodBind("NetwPropertyConfig", "windowed", 1358280359UL);

    /// <summary>
    /// Carries the last <paramref name="samples"/> ticks of values in every
    /// volatile send, so a lost datagram heals from the next one's redundancy
    /// instead of a retransmit round trip. Writes
    /// <see cref="NetwPropertyConfig.SetWindow"/>, and so
    /// <see cref="NetwPropertySet.Window"/> for the whole set, warning when a
    /// second member of the same script writes it too.
    /// <code>
    /// # input() already windows at 2; 3 survives two consecutive lost datagrams
    /// Netw.configure_property(self, &amp;"motion").input().windowed(3)
    /// </code>
    /// </summary>
    public NetwPropertyConfig Windowed(long samples)
    {
        long slot0 = samples;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Long_IntPtr(
            _bindWindowed,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindAudience =
        NetwApi.MethodBind("NetwPropertyConfig", "audience", 231730980UL);

    /// <summary>
    /// Narrows the set to the server only, or back to every recipient. Writes
    /// <see cref="NetwPropertyConfig.SetAudience"/> for the whole set, which
    /// becomes the set's <see cref="NetwPropertySet.Audience"/>. The
    /// <see cref="NetwPropertyConfig.Input"/> preset already narrows its set to
    /// the server.
    /// </summary>
    public NetwPropertyConfig Audience(bool serverOnly = true)
    {
        byte slot0 = serverOnly ? (byte)1 : (byte)0;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Byte_IntPtr(
            _bindAudience,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindMasked =
        NetwApi.MethodBind("NetwPropertyConfig", "masked", 1162647290UL);

    /// <summary>
    /// Sends each viewer only the fields that changed since they last
    /// confirmed, instead of one shared row to everyone. Writes
    /// <see cref="NetwPropertyConfig.SetMasked"/>, and so
    /// <see cref="NetwPropertySet.Masked"/> for the whole set. The same values
    /// arrive, in fewer bytes.
    /// <code>
    /// # 50 spectators, each gets only what changed for them
    /// Netw.configure_property(self, &amp;"position").broadcast().masked()
    /// </code>
    /// <para>
    /// Riding a masked set is not a mistake for a causal field, and the wiring
    /// report does not flag one. The reconstruction invariant means the owner
    /// rebuilds the whole row from the masked stream before anything compares
    /// it, so a masked causal field is still reconcilable.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Masked()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindMasked, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindPersisted =
        NetwApi.MethodBind("NetwPropertyConfig", "persisted", 1627830810UL);

    /// <summary>
    /// Fills <paramref name="column"/> of this entity's saved row with this
    /// property, independent of whether the property also syncs. The database
    /// only ever sees the value the server sees. <paramref name="column"/>
    /// comes from the same <see cref="NetwSchema"/> the entity handed
    /// <see cref="NetwPersistenceConfig.Schema"/>, and one taken from another
    /// schema is refused whatever its index. The property's declared type and
    /// stride have to be what that column stores.
    /// <code>
    /// var schema := game.save_schema
    ///
    /// # never syncs, a server secret the row still keeps
    /// Netw.configure_property(self, &amp;"gold").persisted(schema.column_ref(0))
    ///
    /// # synced per tick, and saved on the entity's own cadence
    /// Netw.configure_property(self, &amp;"position") \
    ///         .state().persisted(schema.column_ref(1))
    ///
    /// # client-authored, savable because input() delivers it to the server
    /// Netw.configure_property(self, &amp;"loadout") \
    ///         .input().persisted(schema.column_ref(2))
    /// </code>
    /// <para>
    /// The cadence belongs to the whole row, through
    /// <see cref="NetwPersistenceConfig.Interval"/>, so a column names no
    /// interval of its own.
    /// </para>
    /// </summary>
    public NetwPropertyConfig Persisted(NetwColumnRef column)
    {
        IntPtr slot0 = column?.Native ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindPersisted,
            Checked,
            in slot0,
            ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindOnSpawn =
        NetwApi.MethodBind("NetwPropertyConfig", "on_spawn", 1162647290UL);

    /// <summary>
    /// Marks this property as spawn state, in
    /// <see cref="NetwPropertyConfig.IsSpawnState"/>. The value is captured
    /// from the authority's instance when the SPAWN frame is snapshotted and
    /// applied on every receiving peer while the node is still orphaned, so
    /// <c>Node._enter_tree</c> and <c>Node._ready</c> read it on every peer.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_property(self, &amp;"pet_name").on_spawn()
    /// </code>
    /// </summary>
    public NetwPropertyConfig OnSpawn()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindOnSpawn, Checked, ref answered);
        return NetwPropertyConfig.Adopt(answered);
    }
}
