// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// The players, scenes and signals of a <see cref="Node.Multiplayer"/> session.
/// </summary>
/// <remarks>
/// Reached with <see cref="Netw.Session"/> from any <see cref="Node"/>. Mostly
/// useful for connecting signals.
/// <code>
/// var s := Netw.session(self)
/// s.entered.connect(on_entered)
/// s.disconnected.connect(on_over)
/// s.ended.connect(on_over)
/// for player: NetwPlayer in s.players:
///         scoreboard.add(player)
/// </code>
/// <para>
/// There is one handle per session, so it is safe to keep it across an await.
/// Connecting is done as you would normally do with
/// <see cref="SceneMultiplayer"/>, by assigning
/// <see cref="MultiplayerApi.MultiplayerPeer"/>. See
/// <see cref="NetwConnectHandle"/> to manage endpoints and
/// <see cref="Netw.PrepareJoin"/> to join as a player.
/// </para>
/// </remarks>
public sealed class NetwSessionHandle : NetwRefCounted
{
    public NetwSessionHandle(IntPtr native) : base(native)
    {
    }

    public static NetwSessionHandle Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwSessionHandle(native);
    }

    public static NetwSessionHandle From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    /// <summary>
    /// This peer's join was accepted.
    /// </summary>
    public event Action Entered
    {
        add => Connect("entered", Callable.From(value));
        remove => Disconnect("entered", Callable.From(value));
    }

    /// <summary>
    /// This session has ended.
    /// </summary>
    public event Action Ended
    {
        add => Connect("ended", Callable.From(value));
        remove => Disconnect("ended", Callable.From(value));
    }

    /// <summary>
    /// Same as <see cref="MultiplayerApi.ServerDisconnected"/>, re-emitted here
    /// so it can be connected beside <see cref="NetwSessionHandle.Ended"/>.
    /// </summary>
    public event Action Disconnected
    {
        add => Connect("disconnected", Callable.From(value));
        remove => Disconnect("disconnected", Callable.From(value));
    }

    /// <summary>
    /// The server announced it is going down with <c>reason</c>.
    /// </summary>
    public event Action<string> Disconnecting
    {
        add => Connect("disconnecting", Callable.From(value));
        remove => Disconnect("disconnecting", Callable.From(value));
    }

    /// <summary>
    /// A <see cref="NetwPlayer"/> has joined, including this peer's own.
    /// </summary>
    public event Action<Variant> PlayerJoined
    {
        add => Connect("player_joined", Callable.From(value));
        remove => Disconnect("player_joined", Callable.From(value));
    }

    /// <summary>
    /// The <see cref="NetwPlayer"/> of this peer has joined.
    /// <see cref="NetwSessionHandle.LocalPlayer"/> is set from here on.
    /// </summary>
    public event Action<Variant> LocalJoined
    {
        add => Connect("local_joined", Callable.From(value));
        remove => Disconnect("local_joined", Callable.From(value));
    }

    /// <summary>
    /// A <see cref="NetwPlayer"/> has left, either because their peer
    /// disconnected or because of <see cref="NetwSessionHandle.Kick"/>.
    /// <see cref="NetwPlayer.IsActive"/> is already <c>false</c>.
    /// </summary>
    public event Action<Variant> PlayerLeft
    {
        add => Connect("player_left", Callable.From(value));
        remove => Disconnect("player_left", Callable.From(value));
    }

    /// <summary>
    /// This peer's join was rejected with <c>code</c> and the <c>reason</c> the
    /// server gave. <see cref="NetwSessionHandle.LocalPlayer"/> stays
    /// <c>null</c>.
    /// </summary>
    public event Action<Error, string> JoinFailed
    {
        add => Connect("join_failed", Callable.From(value));
        remove => Disconnect("join_failed", Callable.From(value));
    }

    /// <summary>
    /// A scene is live. It fires after the scene root is ready, so the whole
    /// scene can be accessed.
    /// <code>
    /// func _on_scene_live(arena: NetwSceneHandle) -&gt; void:
    ///     arena.root.get_node(^"Spawns").arrange()
    /// </code>
    /// </summary>
    public event Action<Variant> SceneLive
    {
        add => Connect("scene_live", Callable.From(value));
        remove => Disconnect("scene_live", Callable.From(value));
    }

    /// <summary>
    /// A <see cref="Netw.ChangeSceneToFile"/> has finished. <c>scene</c> is the
    /// destination and <c>arrived</c> are the players it brought, which is
    /// where their nodes are spawned. A player already watching the destination
    /// is not in <c>arrived</c>.
    /// <code>
    /// func _on_scene_changed(
    ///         scene: NetwSceneHandle,
    ///         arrived: Array[NetwPlayer]) -&gt; void:
    ///     for who in arrived:
    ///         scene.root.add_child(
    ///                 Netw.spawn_player(who, make_player))
    /// </code>
    /// <para>
    /// <b>Server Only.</b>
    /// </para>
    /// </summary>
    public event Action<Variant, Godot.Collections.Array> SceneChanged
    {
        add => Connect("scene_changed", Callable.From(value));
        remove => Disconnect("scene_changed", Callable.From(value));
    }

    /// <summary>
    /// <see cref="NetwSessionHandle.PresentedScene"/> changed from <c>from</c>
    /// to <c>to</c>, either may be <c>null</c>.
    /// </summary>
    public event Action<Variant, Variant> PresentationChanged
    {
        add => Connect("presentation_changed", Callable.From(value));
        remove => Disconnect("presentation_changed", Callable.From(value));
    }

    private static readonly IntPtr _bindGetPlayers =
        NetwApi.MethodBind("NetwSessionHandle", "get_players", 3995934104UL);

    /// <summary>
    /// Every <see cref="NetwPlayer"/> that has joined, including those whose
    /// peer has since disconnected. See
    /// <see cref="NetwMultiplayer.ConnectedPlayers"/> for only the connected
    /// ones.
    /// </summary>
    public Godot.Collections.Array Players
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetPlayers, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetLocalPlayer =
        NetwApi.MethodBind(
            "NetwSessionHandle",
            "get_local_player",
            1167648220UL);

    /// <summary>
    /// The <see cref="NetwPlayer"/> of this peer, <c>null</c> until
    /// <see cref="NetwSessionHandle.LocalJoined"/>.
    /// </summary>
    public NetwPlayer LocalPlayer
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(
                _bindGetLocalPlayer,
                Checked,
                ref answered);
            return NetwPlayer.Adopt(answered);
        }
    }

    private static readonly IntPtr _bindGetPresentedScene =
        NetwApi.MethodBind(
            "NetwSessionHandle",
            "get_presented_scene",
            931191233UL);

    /// <summary>
    /// The scene this peer draws, <c>null</c> when it draws none. It is the
    /// scene holding a body of this peer, or else the scene this peer watches.
    /// When there are two, it is <c>null</c> and a warning is logged. On a
    /// listen server this is what <see cref="HostSceneView"/> draws. See
    /// <see cref="NetwSceneHandle.Watch"/> to choose what a player receives.
    /// </summary>
    public NetwSceneHandle PresentedScene
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(
                _bindGetPresentedScene,
                Checked,
                ref answered);
            return NetwSceneHandle.Adopt(answered);
        }
    }

    private static readonly IntPtr _bindGetRole =
        NetwApi.MethodBind("NetwSessionHandle", "get_role", 2901618068UL);

    /// <summary>
    /// What this peer is in the session.
    /// </summary>
    public NetwMultiplayer.RoleEnum Role
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetRole, Checked, ref answered);
            return (NetwMultiplayer.RoleEnum)answered;
        }
    }

    private static readonly IntPtr _bindGetIsOnline =
        NetwApi.MethodBind("NetwSessionHandle", "get_is_online", 36873697UL);

    /// <summary>
    /// Whether a peer is assigned and connected.
    /// </summary>
    public bool IsOnline
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetIsOnline, Checked, ref answered);
            return answered != 0;
        }
    }

    private static readonly IntPtr _bindGetIsLocalClient =
        NetwApi.MethodBind(
            "NetwSessionHandle",
            "get_is_local_client",
            36873697UL);

    /// <summary>
    /// Whether this peer is a client. A listen server host reads <c>false</c>.
    /// </summary>
    public bool IsLocalClient
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(
                _bindGetIsLocalClient,
                Checked,
                ref answered);
            return answered != 0;
        }
    }

    private static readonly IntPtr _bindGetRoot =
        NetwApi.MethodBind("NetwSessionHandle", "get_root", 3160264692UL);

    /// <summary>
    /// The <see cref="Node"/> replicated nodes are under, <c>null</c> when the
    /// session is not in the tree.
    /// </summary>
    public Node Root
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetRoot, Checked, ref answered);
            Node result = (Node)VariantUtils.ConvertToGodotObject(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetScenes =
        NetwApi.MethodBind("NetwSessionHandle", "get_scenes", 3995934104UL);

    /// <summary>
    /// Every live scene. Use <see cref="Netw.Scene"/> to reach one by name.
    /// </summary>
    public Godot.Collections.Array Scenes
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetScenes, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetConfig =
        NetwApi.MethodBind("NetwSessionHandle", "get_config", 855560725UL);

    /// <summary>
    /// A copy of the <see cref="NetwSessionConfig"/> this session was
    /// configured with. Writing to it changes nothing, use
    /// <see cref="Netw.ConfigureSession"/> before connecting and
    /// <see cref="NetwSessionHandle.SetServerInfo"/> after.
    /// </summary>
    public NetwSessionConfig Config
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(_bindGetConfig, Checked, ref answered);
            return NetwSessionConfig.Adopt(answered);
        }
    }

    private static readonly IntPtr _bindGetStats =
        NetwApi.MethodBind("NetwSessionHandle", "get_stats", 3102165223UL);

    /// <summary>
    /// Every counter this session keeps, keyed by
    /// <see cref="NetwMultiplayer.Stat"/>.
    /// </summary>
    public Godot.Collections.Dictionary Stats
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetStats, Checked, ref answered);
            Godot.Collections.Dictionary result =
                VariantUtils.ConvertToDictionary(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindPlayerOf =
        NetwApi.MethodBind("NetwSessionHandle", "player_of", 8045813UL);

    /// <summary>
    /// The <see cref="NetwPlayer"/> of <paramref name="peer"/>, <c>null</c>
    /// when there is none.
    /// </summary>
    public NetwPlayer PlayerOf(long peer)
    {
        long slot0 = peer;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_Long_IntPtr(
            _bindPlayerOf,
            Checked,
            in slot0,
            ref answered);
        return NetwPlayer.Adopt(answered);
    }

    private static readonly IntPtr _bindBucketOf =
        NetwApi.MethodBind("NetwSessionHandle", "bucket_of", 1944677757UL);

    /// <summary>
    /// The per-peer game data of <paramref name="type"/> stored for
    /// <paramref name="peer"/>, created on first use. See
    /// <see cref="NetwMultiplayer.PeerGetBucket"/>.
    /// </summary>
    public Variant BucketOf(long peer, Variant type)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)peer);
        godot_variant slot1 = type.CopyNativeVariant();
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindBucketOf,
            Checked,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        Variant result = Variant.CreateCopyingBorrowed(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindSetServerInfo =
        NetwApi.MethodBind(
            "NetwSessionHandle",
            "set_server_info",
            1251535023UL);

    /// <summary>
    /// Replaces what this session advertises about itself, such as the name
    /// shown in a server list. <b>Server Only.</b>
    /// </summary>
    public void SetServerInfo(NetwServerInfo info)
    {
        IntPtr slot0 = info?.Native ?? IntPtr.Zero;
        long discarded = default;
        NetwThunks.Ptrcall1_IntPtr_Long(
            _bindSetServerInfo,
            Checked,
            in slot0,
            ref discarded);
    }

    private static readonly IntPtr _bindLeave =
        NetwApi.MethodBind("NetwSessionHandle", "leave", 1931563502UL);

    /// <summary>
    /// Leaves the session. The server saves its entity rows first, and stays
    /// online if the database refuses a row. The promise resolves with an
    /// <c>@GlobalScope.Error</c> once the peer is down or the save failed.
    /// </summary>
    public NetwPromise Leave()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindLeave, Checked, ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindSaveEntities =
        NetwApi.MethodBind("NetwSessionHandle", "save_entities", 1931563502UL);

    /// <summary>
    /// Saves every entity row that changed since its last save, including rows
    /// of entities that already left. Call it again to retry a row the database
    /// refused. <see cref="NetwSessionHandle.Leave"/> runs the same save.
    /// <code>
    /// Error
    /// ┠╴OK                every changed row is stored
    /// ┠╴ERR_UNAUTHORIZED  this peer is not the server
    /// ┠╴ERR_UNCONFIGURED  this handle outlived its session
    /// ┖╴a row's code      the first row still unsaved, see NetwPersistenceHandle.save
    /// </code>
    /// <para>
    /// <b>Server Only.</b>
    /// </para>
    /// </summary>
    public NetwPromise SaveEntities()
    {
        IntPtr answered = default;
        NetwThunks.Ptrcall0_IntPtr(_bindSaveEntities, Checked, ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindKick =
        NetwApi.MethodBind("NetwSessionHandle", "kick", 1232915396UL);

    /// <summary>
    /// Removes <paramref name="player"/> from the session and disconnects their
    /// peer with <paramref name="reason"/>. The server's own player cannot be
    /// kicked, use <see cref="NetwSessionHandle.Leave"/> instead. <b>Server
    /// Only.</b>
    /// </summary>
    public Error Kick(NetwPlayer player, string reason = "")
    {
        godot_variant slot0 =
            VariantUtils.CreateFromGodotObjectPtr(
                player?.Native ?? IntPtr.Zero);
        godot_variant slot1 = VariantUtils.CreateFromString(reason);
        godot_variant answered = default;
        NetwThunks.Call2(_bindKick, Checked, in slot0, in slot1, ref answered);
        slot0.Dispose();
        slot1.Dispose();
        Error result = (Error)VariantUtils.ConvertToInt64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRequestScene =
        NetwApi.MethodBind("NetwSessionHandle", "request_scene", 4150322833UL);

    /// <summary>
    /// Asks the server for the scene at <paramref name="path"/> over
    /// <paramref name="scope"/>. The promise resolves when the scene is live,
    /// or is rejected when the server declines. <b>Player request.</b>
    /// </summary>
    public NetwPromise RequestScene(string path, NetwMultiplayer.SceneChange scope =
        (NetwMultiplayer.SceneChange)0)
    {
        godot_variant slot0 = VariantUtils.CreateFromString(path);
        godot_variant slot1 = VariantUtils.CreateFromInt((long)scope);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindRequestScene,
            Checked,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        NetwPromise result =
            NetwPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }
}
