// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// Packed-column snapshot of the transitions a prediction engine drove.
/// </summary>
/// <remarks>
/// Production ownership stays in the native engine. A caller never builds one
/// up: <see cref="NetwPredictionHandle.Journal"/> materializes this
/// tooling-cadence view without changing the retained native rows, and
/// <c>NetwPredictJournal.new()</c> itself yields an empty snapshot with
/// <see cref="NetwPredictJournal.Size"/> zero. A closed row names one drive
/// completely. A row is a complete account of the transition it names, so a
/// transition is reproducible from its row alone. Nothing the engine decided is
/// held outside the row and read back later, which is what lets two peers
/// compare transitions instead of comparing engines. Two peers that ran the
/// same transition closure agree on <see cref="NetwPredictJournal.PostFps"/> at
/// every acked transition, and the first transition where they disagree is the
/// one that broke, not the one where the error grew visible. A native enum is
/// not a <see cref="Godot.Collections.Dictionary"/> at runtime the way a
/// GDScript enum is, so <see cref="NetwPredictJournal.AttributionNames"/>,
/// <see cref="NetwPredictJournal.OperatorNames"/>,
/// <see cref="NetwPredictJournal.DomainNames"/>, and
/// <see cref="NetwPredictJournal.StateFamilyNames"/> exist for a caller that
/// wants a name for a stored value rather than the bare
/// <see cref="NetwPredictJournal.Attribution"/>,
/// <see cref="NetwPredictJournal.Operator"/>,
/// <see cref="NetwPredictJournal.Domain"/>, or
/// <see cref="NetwPredictJournal.StateFamily"/>.
/// <code>
/// var journal := entity.prediction.journal()
/// var transitions := journal.transitions()
/// var flags := journal.flags()
/// for i in transitions.size():
///     if flags[i] &amp; NetwPredictJournal.ROW_DIVERGENT:
///         print("diverged at transition ", transitions[i])
///         break
/// </code>
/// </remarks>
public sealed class NetwPredictJournal : NetwRefCounted
{
    public NetwPredictJournal(IntPtr native) : base(native)
    {
    }

    public static NetwPredictJournal Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwPredictJournal(native);
    }

    public static NetwPredictJournal From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    public enum Attribution : long
    {
        /// <summary>
        /// Required peer evidence was absent, so no boundary is blamed.
        /// </summary>
        Unknown = 0,
        /// <summary>
        /// The peers entered the transition with different declared state.
        /// </summary>
        PreState = 1,
        /// <summary>
        /// The command differed. Authority ran input the owner did not author.
        /// </summary>
        Command = 2,
        /// <summary>
        /// The environment differed. The transition ran against unequal world
        /// facts.
        /// </summary>
        Environment = 3,
        /// <summary>
        /// The execution topology or body mode differed.
        /// </summary>
        Topology = 4,
        /// <summary>
        /// Canonical state agreed but optional raw execution bits differed.
        /// </summary>
        Execution = 5,
        /// <summary>
        /// Equal observed antecedents produced a different contact witness.
        /// </summary>
        Contact = 6,
        /// <summary>
        /// Every observed antecedent agreed but the produced state differed.
        /// </summary>
        Closure = 7,
    }

    public enum Operator : long
    {
        /// <summary>
        /// No operator wrote the body since the preceding row.
        /// </summary>
        None = 0,
        /// <summary>
        /// A projected authoritative basis was restored.
        /// </summary>
        RebaseProjected = 1,
        /// <summary>
        /// An exact authoritative basis was restored.
        /// </summary>
        RebaseExact = 2,
        /// <summary>
        /// The teleport tier restored the full declared closure.
        /// </summary>
        FullClosure = 3,
        /// <summary>
        /// Present-time moving transport composed an aligned delta.
        /// </summary>
        TransportDelta = 4,
        /// <summary>
        /// Fallback seeded the body from authority.
        /// </summary>
        Reseed = 5,
        /// <summary>
        /// The first post-reseed comparison aligned the acknowledgement
        /// horizon.
        /// </summary>
        ReseedAlign = 6,
        /// <summary>
        /// A witnessed boundary breach closed speculation without closing
        /// input.
        /// </summary>
        Demote = 7,
        /// <summary>
        /// A clean momentum-only divergence was left to contract without a
        /// write.
        /// </summary>
        Dissipate = 8,
        /// <summary>
        /// A joint pass restored the whole replay group to its shared floor.
        /// </summary>
        JointRebase = 9,
    }

    public enum StateFamily : long
    {
        /// <summary>
        /// No family differed or the peer evidence was unavailable. Named
        /// <c>FAMILY_NONE</c> rather than <c>NONE</c> because a bound enum's
        /// members flatten into the class namespace alongside
        /// <see cref="NetwPredictJournal.Operator"/>, which already claims
        /// <c>NONE</c>.
        /// </summary>
        FamilyNone = 0,
        /// <summary>
        /// Position and orientation fields.
        /// </summary>
        Pose = 1,
        /// <summary>
        /// Declared derivative and velocity fields.
        /// </summary>
        Momentum = 2,
        /// <summary>
        /// Remaining controller state and latches.
        /// </summary>
        ControllerLatch = 3,
    }

    public enum Domain : long
    {
        /// <summary>
        /// Every antecedent of the transition is declared equal on both peers,
        /// so its fingerprints must match exactly.
        /// </summary>
        InDomain = 0,
        /// <summary>
        /// An antecedent is declared unequal or unknown, so the transition is
        /// compared by tolerance rather than by fingerprint.
        /// </summary>
        OutOfDomain = 1,
    }

    /// <summary>
    /// How many transitions a journal retains before the oldest row falls off
    /// when none is given explicitly.
    /// </summary>
    public const long CapacityDefault = 256;
    /// <summary>
    /// The row has been acknowledged by authority. Set by <c>mark_ack</c> on
    /// the native engine.
    /// </summary>
    public const long RowAcked = 1;
    /// <summary>
    /// The acknowledged authority state fingerprinted equal to
    /// <see cref="NetwPredictJournal.PostFps"/>.
    /// </summary>
    public const long RowMatched = 2;
    /// <summary>
    /// Authority ran a command the owner never authored for this transition.
    /// </summary>
    public const long RowSubstituted = 4;
    /// <summary>
    /// A later acknowledgement replaced this row's verdict with a truer one.
    /// </summary>
    public const long RowSuperseded = 8;
    /// <summary>
    /// The acknowledged authority state fingerprinted unequal to
    /// <see cref="NetwPredictJournal.PostFps"/>.
    /// </summary>
    public const long RowDivergent = 16;
    /// <summary>
    /// The row's drive has produced its state, so
    /// <see cref="NetwPredictJournal.PostFps"/> carries a real fingerprint
    /// rather than the zero an open row holds.
    /// </summary>
    public const long RowClosed = 32;
    /// <summary>
    /// The row's <see cref="NetwPredictJournal.PreFps"/> did not chain from the
    /// preceding produced state and no operator provenance accounts for the
    /// intervening write.
    /// </summary>
    public const long RowChainBroken = 64;
    /// <summary>
    /// Both peers declared a realized witness for the row and its fingerprint
    /// matched. The local witness detail may therefore describe the peer's
    /// stable witness facts too.
    /// </summary>
    public const long RowWitnessMatched = 128;
    /// <summary>
    /// The row carries a declared realized-transition witness.
    /// </summary>
    public const long EvidenceWitness = 1;
    /// <summary>
    /// The row carries the optional raw pre-state fingerprint.
    /// </summary>
    public const long EvidenceRaw = 2;

    private static readonly IntPtr _bindFnv1A =
        NetwApi.MethodBind("NetwPredictJournal", "fnv1a", 165934931UL);

    /// <summary>
    /// Returns the fingerprint of <paramref name="bytes"/> as fnv1a-32, the one
    /// hash the journal, the wire, and every later comparison share. The result
    /// is a signed 32-bit integer because that is the width the columns and the
    /// wire both carry, so a fingerprint never changes representation between
    /// being computed, stored, and sent.
    /// </summary>
    public static int Fnv1A(byte[] bytes)
    {
        godot_variant slot0 = VariantUtils.CreateFromPackedByteArray(bytes);
        godot_variant answered = default;
        NetwThunks.Call1(_bindFnv1A, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        int result = VariantUtils.ConvertToInt32(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindAttributionNames =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "attribution_names",
            2382534195UL);

    /// <summary>
    /// Returns <see cref="NetwPredictJournal.Attribution"/> member names mapped
    /// to their values, for looking a value up by name where a bare enum offers
    /// no such lookup.
    /// </summary>
    public static Godot.Collections.Dictionary AttributionNames()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindAttributionNames, IntPtr.Zero, ref answered);
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindOperatorNames =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "operator_names",
            2382534195UL);

    /// <summary>
    /// Returns <see cref="NetwPredictJournal.Operator"/> member names mapped to
    /// their values, for looking a value up by name where a bare enum offers no
    /// such lookup.
    /// </summary>
    public static Godot.Collections.Dictionary OperatorNames()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindOperatorNames, IntPtr.Zero, ref answered);
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindDomainNames =
        NetwApi.MethodBind("NetwPredictJournal", "domain_names", 2382534195UL);

    /// <summary>
    /// Returns <see cref="NetwPredictJournal.Domain"/> member names mapped to
    /// their values, for looking a value up by name where a bare enum offers no
    /// such lookup.
    /// </summary>
    public static Godot.Collections.Dictionary DomainNames()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindDomainNames, IntPtr.Zero, ref answered);
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindStateFamilyNames =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "state_family_names",
            2382534195UL);

    /// <summary>
    /// Returns <see cref="NetwPredictJournal.StateFamily"/> member names mapped
    /// to their values, for looking a value up by name where a bare enum offers
    /// no such lookup.
    /// </summary>
    public static Godot.Collections.Dictionary StateFamilyNames()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindStateFamilyNames, IntPtr.Zero, ref answered);
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRowAt =
        NetwApi.MethodBind("NetwPredictJournal", "row_at", 3485342025UL);

    /// <summary>
    /// Returns the row recorded for <paramref name="transition"/>, or an empty
    /// <see cref="Godot.Collections.Dictionary"/> when it has fallen out of the
    /// ring. This is the tooling-cadence read. Bulk readers take the columns
    /// through <see cref="NetwPredictJournal.Transitions"/> and its siblings
    /// instead of materializing a row per transition.
    /// <code>
    /// Dictionary
    /// ┠╴transition   int   the recurrence index, injective within an epoch
    /// ┠╴label        int   the clock label the drive carried
    /// ┠╴kind         int   a DriveKind value naming the command selection
    /// ┠╴c_hash       int   fingerprint of the canonical command bytes
    /// ┠╴e_digest     int   fingerprint of the declared environment facts
    /// ┠╴post_fp      int   fingerprint of the state the drive produced
    /// ┠╴domain       int   a Domain value
    /// ┠╴attribution  int   an Attribution value
    /// ┖╴flags        int   the ROW_ bitfield
    /// </code>
    /// <para>
    /// The row also exposes <c>pre_fp</c>, the pre and post <c>pose_fp</c>,
    /// <c>momentum_fp</c>, and <c>controller_fp</c> families, plus the
    /// preceding operator's <c>episode_id</c>, <c>write_id</c>,
    /// <c>operator</c>, and <c>basis</c>. Settled rows expose
    /// <c>aligned_error</c>, and witnessed rows expose
    /// <c>witness_class_bits</c>.
    /// </para>
    /// </summary>
    public Godot.Collections.Dictionary RowAt(long transition)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)transition);
        godot_variant answered = default;
        NetwThunks.Call1(_bindRowAt, Checked, in slot0, ref answered);
        slot0.Dispose();
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindAttributionAt =
        NetwApi.MethodBind("NetwPredictJournal", "attribution_at", 923996154UL);

    /// <summary>
    /// Returns the <see cref="NetwPredictJournal.Attribution"/> charged to
    /// <paramref name="transition"/>, or
    /// <see cref="NetwPredictJournal.Attribution.Unknown"/> when nothing
    /// charged it or the row has fallen out of the ring.
    /// </summary>
    public int AttributionAt(long transition)
    {
        long slot0 = transition;
        int answered = default;
        NetwThunks.Ptrcall1_Long_Int(
            _bindAttributionAt,
            Checked,
            in slot0,
            ref answered);
        return answered;
    }

    private static readonly IntPtr _bindDomainAt =
        NetwApi.MethodBind("NetwPredictJournal", "domain_at", 923996154UL);

    /// <summary>
    /// Returns the <see cref="NetwPredictJournal.Domain"/> recorded for
    /// <paramref name="transition"/>, or
    /// <see cref="NetwPredictJournal.Domain.OutOfDomain"/> when the row has
    /// fallen out of the ring. A transition nobody retained is one nobody can
    /// show was entitled to exactness, so the forgotten row reads as the label
    /// that claims nothing.
    /// </summary>
    public int DomainAt(long transition)
    {
        long slot0 = transition;
        int answered = default;
        NetwThunks.Ptrcall1_Long_Int(
            _bindDomainAt,
            Checked,
            in slot0,
            ref answered);
        return answered;
    }

    private static readonly IntPtr _bindFlagsAt =
        NetwApi.MethodBind("NetwPredictJournal", "flags_at", 923996154UL);

    /// <summary>
    /// Returns the <c>ROW_*</c> bitfield recorded for
    /// <paramref name="transition"/>, or <c>0</c> when the row has fallen out
    /// of the ring. This and <see cref="NetwPredictJournal.DomainAt"/> are the
    /// per-transition reads the compare path makes on every authoritative
    /// frame, which is why they return a scalar instead of going through
    /// <see cref="NetwPredictJournal.RowAt"/>. Materializing a row dictionary
    /// to read one byte out of it allocates once per frame per predicted
    /// entity.
    /// </summary>
    public int FlagsAt(long transition)
    {
        long slot0 = transition;
        int answered = default;
        NetwThunks.Ptrcall1_Long_Int(
            _bindFlagsAt,
            Checked,
            in slot0,
            ref answered);
        return answered;
    }

    private static readonly IntPtr _bindLastClosed =
        NetwApi.MethodBind("NetwPredictJournal", "last_closed", 3905245786UL);

    /// <summary>
    /// Returns the newest transition whose row is
    /// <see cref="NetwPredictJournal.RowClosed"/> with every older retained row
    /// closed too, or <c>-1</c> when none is. This is the frontier an
    /// acknowledgement may claim. A row that is open holds a zero fingerprint,
    /// so acknowledging it would assert a state the drive has not produced yet.
    /// </summary>
    public long LastClosed()
    {
        long answered = default;
        NetwThunks.Ptrcall0_Long(_bindLastClosed, Checked, ref answered);
        return answered;
    }

    private static readonly IntPtr _bindFirstUnmatched =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "first_unmatched",
            3905245786UL);

    /// <summary>
    /// Returns the oldest transition whose row is not
    /// <see cref="NetwPredictJournal.RowMatched"/>, or <c>-1</c> when every
    /// retained row matched. This is the transition a recovery rebases at.
    /// </summary>
    public long FirstUnmatched()
    {
        long answered = default;
        NetwThunks.Ptrcall0_Long(_bindFirstUnmatched, Checked, ref answered);
        return answered;
    }

    private static readonly IntPtr _bindFirstChainBreak =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "first_chain_break",
            3905245786UL);

    /// <summary>
    /// Returns the first retained transition marked
    /// <see cref="NetwPredictJournal.RowChainBroken"/>, or <c>-1</c> when the
    /// retained chain is intact.
    /// </summary>
    public long FirstChainBreak()
    {
        long answered = default;
        NetwThunks.Ptrcall0_Long(_bindFirstChainBreak, Checked, ref answered);
        return answered;
    }

    private static readonly IntPtr _bindClear =
        NetwApi.MethodBind("NetwPredictJournal", "clear", 1286410249UL);

    /// <summary>
    /// Drops every retained row and adopts <paramref name="epoch"/>.
    /// Transitions are injective only within one epoch, so a journal that
    /// outlives an epoch would hold two rows claiming the same transition.
    /// Clearing is how a rewire keeps <see cref="NetwPredictJournal.RowAt"/>
    /// unambiguous.
    /// </summary>
    public void Clear(long epoch)
    {
        long slot0 = epoch;
        long discarded = default;
        NetwThunks.Ptrcall1_Long_Long(
            _bindClear,
            Checked,
            in slot0,
            ref discarded);
    }

    private static readonly IntPtr _bindSize =
        NetwApi.MethodBind("NetwPredictJournal", "size", 3905245786UL);

    /// <summary>
    /// Returns how many rows the journal currently retains, at most
    /// <see cref="NetwPredictJournal.Capacity"/>.
    /// </summary>
    public int Size()
    {
        int answered = default;
        NetwThunks.Ptrcall0_Int(_bindSize, Checked, ref answered);
        return answered;
    }

    private static readonly IntPtr _bindCapacity =
        NetwApi.MethodBind("NetwPredictJournal", "capacity", 3905245786UL);

    /// <summary>
    /// Returns how many rows the journal retains before the oldest falls off.
    /// </summary>
    public int Capacity()
    {
        int answered = default;
        NetwThunks.Ptrcall0_Int(_bindCapacity, Checked, ref answered);
        return answered;
    }

    private static readonly IntPtr _bindEpoch =
        NetwApi.MethodBind("NetwPredictJournal", "epoch", 3905245786UL);

    /// <summary>
    /// Returns the epoch <see cref="NetwPredictJournal.Clear"/> last adopted,
    /// or <c>-1</c> before any.
    /// </summary>
    public long Epoch()
    {
        long answered = default;
        NetwThunks.Ptrcall0_Long(_bindEpoch, Checked, ref answered);
        return answered;
    }

    private static readonly IntPtr _bindTransitions =
        NetwApi.MethodBind("NetwPredictJournal", "transitions", 235988956UL);

    /// <summary>
    /// Returns the retained transitions oldest first. Every other column
    /// accessor returns values in this same order, so index <c>i</c> names one
    /// row across all of them.
    /// </summary>
    public long[] Transitions()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindTransitions, Checked, ref answered);
        long[] result =
            VariantUtils.ConvertAsPackedInt64ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindLabels =
        NetwApi.MethodBind("NetwPredictJournal", "labels", 235988956UL);

    /// <summary>
    /// Returns the retained clock labels, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public long[] Labels()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindLabels, Checked, ref answered);
        long[] result =
            VariantUtils.ConvertAsPackedInt64ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindCHashes =
        NetwApi.MethodBind("NetwPredictJournal", "c_hashes", 1930428628UL);

    /// <summary>
    /// Returns the retained command fingerprints, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public int[] CHashes()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindCHashes, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindEDigests =
        NetwApi.MethodBind("NetwPredictJournal", "e_digests", 1930428628UL);

    /// <summary>
    /// Returns the retained environment digests, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>. A row whose engine
    /// declares no environment facts carries <c>0</c>.
    /// </summary>
    public int[] EDigests()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindEDigests, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindPreFps =
        NetwApi.MethodBind("NetwPredictJournal", "pre_fps", 1930428628UL);

    /// <summary>
    /// Returns the retained pre-state fingerprints, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public int[] PreFps()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindPreFps, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindPostFps =
        NetwApi.MethodBind("NetwPredictJournal", "post_fps", 1930428628UL);

    /// <summary>
    /// Returns the retained post-solve state fingerprints, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>. An open row carries
    /// <c>0</c> until the drive closes.
    /// </summary>
    public int[] PostFps()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindPostFps, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindTopoFps =
        NetwApi.MethodBind("NetwPredictJournal", "topo_fps", 1930428628UL);

    /// <summary>
    /// Returns the retained execution-topology fingerprints, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>. The declared quantum is
    /// folded into this hash, and nothing else is. The quantum is how many
    /// physics steps a drive actually bought, and it belongs here because the
    /// physics server integrates on its own cadence: a drive and a solve are
    /// two events, and only their ratio makes a compared transition mean the
    /// same thing on both peers. Without it the boundary ladder walks all the
    /// way to closure and reports that every antecedent agreed. A different
    /// quantum is therefore a different topology, deliberately, and two peers
    /// running the same commands at different cadences disagree here rather
    /// than nowhere.
    /// </summary>
    public int[] TopoFps()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindTopoFps, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRawFps =
        NetwApi.MethodBind("NetwPredictJournal", "raw_fps", 1930428628UL);

    /// <summary>
    /// Returns the retained raw pre-state fingerprints, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>. A row without
    /// <see cref="NetwPredictJournal.EvidenceRaw"/> carries zero.
    /// </summary>
    public int[] RawFps()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindRawFps, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindWitnessFps =
        NetwApi.MethodBind("NetwPredictJournal", "witness_fps", 1930428628UL);

    /// <summary>
    /// Returns the retained realized-witness fingerprints, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>. A row without
    /// <see cref="NetwPredictJournal.EvidenceWitness"/> carries zero.
    /// </summary>
    public int[] WitnessFps()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindWitnessFps, Checked, ref answered);
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindWitnessClassBits =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "witness_class_bits",
            2362200018UL);

    /// <summary>
    /// Returns authority witness-class summaries ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public byte[] WitnessClassBits()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindWitnessClassBits, Checked, ref answered);
        byte[] result =
            VariantUtils.ConvertAsPackedByteArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindPreFamilyFps =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "pre_family_fps",
            1706082319UL);

    /// <summary>
    /// Returns <paramref name="family"/>'s retained pre-state fingerprint
    /// column, ordered by <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public int[] PreFamilyFps(int family)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)family);
        godot_variant answered = default;
        NetwThunks.Call1(_bindPreFamilyFps, Checked, in slot0, ref answered);
        slot0.Dispose();
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindPostFamilyFps =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "post_family_fps",
            1706082319UL);

    /// <summary>
    /// Returns <paramref name="family"/>'s retained post-state fingerprint
    /// column, ordered by <see cref="NetwPredictJournal.Transitions"/>. An open
    /// row carries <c>0</c> until the drive closes.
    /// </summary>
    public int[] PostFamilyFps(int family)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)family);
        godot_variant answered = default;
        NetwThunks.Call1(_bindPostFamilyFps, Checked, in slot0, ref answered);
        slot0.Dispose();
        int[] result =
            VariantUtils.ConvertAsPackedInt32ArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindKinds =
        NetwApi.MethodBind("NetwPredictJournal", "kinds", 2362200018UL);

    /// <summary>
    /// Returns the retained <see cref="NetwPredict.DriveKind"/> values, ordered
    /// by <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public byte[] Kinds()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindKinds, Checked, ref answered);
        byte[] result =
            VariantUtils.ConvertAsPackedByteArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindDomains =
        NetwApi.MethodBind("NetwPredictJournal", "domains", 2362200018UL);

    /// <summary>
    /// Returns the retained <see cref="NetwPredictJournal.Domain"/> values,
    /// ordered by <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public byte[] Domains()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindDomains, Checked, ref answered);
        byte[] result =
            VariantUtils.ConvertAsPackedByteArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindAttributions =
        NetwApi.MethodBind("NetwPredictJournal", "attributions", 2362200018UL);

    /// <summary>
    /// Returns the retained divergence charges, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public byte[] Attributions()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindAttributions, Checked, ref answered);
        byte[] result =
            VariantUtils.ConvertAsPackedByteArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindEvidenceMasks =
        NetwApi.MethodBind(
            "NetwPredictJournal",
            "evidence_masks",
            2362200018UL);

    /// <summary>
    /// Returns the retained evidence-completeness masks, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public byte[] EvidenceMasks()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindEvidenceMasks, Checked, ref answered);
        byte[] result =
            VariantUtils.ConvertAsPackedByteArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindFlags =
        NetwApi.MethodBind("NetwPredictJournal", "flags", 2362200018UL);

    /// <summary>
    /// Returns the retained <c>ROW_</c> bitfields, ordered by
    /// <see cref="NetwPredictJournal.Transitions"/>.
    /// </summary>
    public byte[] Flags()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindFlags, Checked, ref answered);
        byte[] result =
            VariantUtils.ConvertAsPackedByteArrayToSystemArray(answered);
        answered.Dispose();
        return result;
    }
}
