// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// The enum vocabulary of the prediction family, on a leaf nobody has to import
/// an engine to read.
/// </summary>
/// <remarks>
/// Every value a prediction setting is written with.
/// <see cref="NetwPredictionHandle"/> is where a game writes and reads them,
/// and this class exists so naming one costs nothing, because nothing here
/// holds state and nothing here can be constructed.
/// <code>
/// entity.prediction.schedule = NetwPredict.SCHEDULE_FRAME
/// if entity.prediction.role == NetwPredict.ROLE_PREDICT:
///     ...
/// </code>
/// <para>
/// <b>What a game declares</b>
/// - <see cref="NetwPredict.Archetype"/> what kind of body this is, which
/// presets the rest
/// - <see cref="NetwPredict.Schedule"/> how often the entity is driven
/// - <see cref="NetwPredict.CorrectionMode"/> how a correction is applied
/// - <see cref="NetwPredict.RestoreMode"/> how a snapped correction places the
/// state
/// - <see cref="NetwPredict.RecoveryPolicy"/> what a recovery is allowed to do
/// - <see cref="NetwPredict.MissingInput"/> what the server does about an input
/// that never came
/// - <see cref="NetwPredict.BreachResponse"/> what happens on a contact outside
/// the prediction
/// - <see cref="NetwPredict.Fidelity"/> how one member of an island is
/// represented here
/// - <see cref="NetwPredict.Promotion"/> which island members are simulated
/// locally
/// - <see cref="NetwPredict.Pacing"/> when an island's members open a
/// transition
/// - <see cref="NetwPredict.Reconcile"/> whether an island is corrected
/// together or apart
/// <b>What the session reports back</b>
/// - <see cref="NetwPredict.Role"/> the name for one
/// <see cref="NetwPredict.InputSource"/> and <see cref="NetwPredict.SimMode"/>
/// pair
/// - <see cref="NetwPredict.InputSource"/> where this peer's copy gets its
/// input
/// - <see cref="NetwPredict.SimMode"/> what this peer's simulation counts for
/// - <see cref="NetwPredict.DriveKind"/> how the last drive chose its input
/// - <see cref="NetwPredict.ConsumeAction"/> what a consume pass did this frame
/// - <see cref="NetwPredict.ContactClass"/> what the local solve reported
/// touching
/// - <see cref="NetwPredict.WitnessClass"/> what both peers agree was touched
/// - <see cref="NetwPredict.CommandOrigin"/> where one replayed input came from
/// - <see cref="NetwPredict.CellProvenance"/> the same, ranked, when a group
/// replays together
/// - <see cref="NetwPredict.ExactVerdict"/> whether fingerprints have been
/// compared yet
/// - <see cref="NetwPredict.TriggerShape"/> what asked for a recovery
/// - <see cref="NetwPredict.OperatorOutcome"/> what a recovery attempt achieved
/// - <see cref="NetwPredict.EpisodeState"/> how far a divergence episode has
/// got
/// - <see cref="NetwPredict.VerdictReason"/> why a comparison did not reach the
/// body
/// </para>
/// </remarks>
public sealed class NetwPredict : NetwObject
{
    public NetwPredict(IntPtr native) : base(native, owned: false)
    {
    }

    public static NetwPredict Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwPredict(native);
    }

    public static NetwPredict From(Variant value)
    {
        return Adopt(NetwApi.ObjectOf(value));
    }

    public enum Role : long
    {
        /// <summary>
        /// A remote client controls the entity, which predicts and corrects
        /// itself when the server acknowledges. A role is never chosen on its
        /// own. It is the name <see cref="NetwPredictionHandle.RoleForAxes"/>
        /// gives to a pair of <see cref="NetwPredictionHandle.InputSource"/>
        /// and <see cref="NetwPredictionHandle.SimMode"/>, so the name and the
        /// two facts behind it cannot disagree. Every role is driven, because
        /// the work done for an entity is the same whichever peer owns it. A
        /// role decides whether a caller reaches the simulation at all and
        /// never what the simulation then does, which is what makes a
        /// transition recorded under one role comparable against the same
        /// transition recorded under another.
        /// </summary>
        Predict = 0,
        /// <summary>
        /// The server consumes a remote peer's received input into
        /// authoritative state.
        /// </summary>
        Consume = 1,
        /// <summary>
        /// A listen-server host controls its own entity, simulating
        /// authoritatively.
        /// </summary>
        HostLocal = 2,
        /// <summary>
        /// A remote display. Never simulates here, the interpolator shows it.
        /// </summary>
        Remote = 3,
        /// <summary>
        /// A replicated remote stepped locally with a predicted command.
        /// </summary>
        Simulate = 4,
    }

    public enum InputSource : long
    {
        /// <summary>
        /// This peer produces the input it simulates. Read the entity value
        /// from <see cref="NetwPredictionHandle.InputSource"/>.
        /// </summary>
        Local = 0,
        /// <summary>
        /// This peer reads a command another peer authored and sent.
        /// </summary>
        Received = 1,
        /// <summary>
        /// This peer guesses a command nobody sent, for a simulated island
        /// participant.
        /// </summary>
        Predicted = 2,
        /// <summary>
        /// This peer simulates nothing, so it needs no command.
        /// </summary>
        None = 3,
    }

    public enum SimMode : long
    {
        /// <summary>
        /// The simulation produces the authoritative state. Read the entity
        /// value from <see cref="NetwPredictionHandle.SimMode"/>.
        /// </summary>
        Authoritative = 0,
        /// <summary>
        /// The simulation produces a guess this peer will reconcile.
        /// </summary>
        Speculative = 1,
        /// <summary>
        /// No simulation runs and received state is shown.
        /// </summary>
        Display = 2,
    }

    public enum Schedule : long
    {
        /// <summary>
        /// Drive once for every network tick, which is what a kinematic body
        /// predicts under.
        /// </summary>
        Tick = 0,
        /// <summary>
        /// Apply once after every physics frame's network tick loop.
        /// </summary>
        Frame = 1,
        /// <summary>
        /// Apply once per network tick through a
        /// <see cref="NetwPhysicsStepper"/>, which can re-run a space step
        /// inside one frame. Every member in the space is driven first and the
        /// space is stepped once after all of them, so one step integrates the
        /// forces the whole tick authored and the state each member records is
        /// the one that step produced. A space with no stepper installed cannot
        /// re-run a step, so a member declaring this there resolves to
        /// <see cref="NetwPredict.Schedule.Frame"/> and the engine reports that
        /// once, naming the entity and the space. The handle keeps the
        /// declaration the game wrote and so does the recovery policy, so
        /// installing a stepper with
        /// <see cref="NetwMultiplayer.PredictStepperInstall"/> restores the
        /// schedule that was asked for.
        /// </summary>
        Stepped = 2,
    }

    public enum ContactClass : long
    {
        /// <summary>
        /// The solve reported no collider. A
        /// <see cref="NetwPredict.ContactClass"/> is kept for reading
        /// afterwards and is never compared between peers.
        /// </summary>
        None = 0,
        /// <summary>
        /// The collider is the support reported by the declared ground sensor.
        /// </summary>
        DeclaredSupport = 1,
        /// <summary>
        /// Static geometry other than the declared support.
        /// </summary>
        OtherStatic = 2,
        /// <summary>
        /// A dynamic entity this peer predicts or simulates authoritatively.
        /// </summary>
        PredictedDynamic = 3,
        /// <summary>
        /// A dynamic entity outside this peer's prediction island.
        /// </summary>
        UnpredictedDynamic = 4,
        /// <summary>
        /// A kinematic or animated collision proxy.
        /// </summary>
        KinematicProxy = 5,
    }

    public enum WitnessClass : long
    {
        /// <summary>
        /// Nothing was touched. A <see cref="NetwPredict.WitnessClass"/> reads
        /// the same on every peer, which is what lets it travel in a
        /// fingerprint and be compared.
        /// </summary>
        None = 0,
        /// <summary>
        /// The declared support was contacted.
        /// </summary>
        Support = 1,
        /// <summary>
        /// Static geometry other than the declared support was contacted.
        /// </summary>
        Static = 2,
        /// <summary>
        /// A replicated dynamic entity was contacted.
        /// </summary>
        DynamicEntity = 4,
    }

    public enum CommandOrigin : long
    {
        /// <summary>
        /// This peer's own guess for an entity it does not own. A group
        /// replaying its members together replays them from these, so the
        /// origin is what says whether a replay reproduced what a player
        /// actually did or repeated a guess.
        /// </summary>
        Predicted = 0,
        /// <summary>
        /// The authoring peer's own command, relayed through the server.
        /// </summary>
        Relayed = 1,
    }

    public enum DriveKind : long
    {
        /// <summary>
        /// No drive has run yet.
        /// </summary>
        None = 0,
        /// <summary>
        /// A newly authored input label drove the simulation.
        /// </summary>
        Fresh = 1,
        /// <summary>
        /// The previous input label drove the simulation again.
        /// </summary>
        Repeat = 2,
        /// <summary>
        /// The consume cursor held while repeating its acknowledged input.
        /// </summary>
        Hold = 3,
        /// <summary>
        /// The consume cursor had no input stream and repeated its acknowledged
        /// input.
        /// </summary>
        Starved = 4,
        /// <summary>
        /// A fresh input drove after older eligible labels were folded away.
        /// </summary>
        FoldDrive = 5,
        /// <summary>
        /// A missing input label drove through <c>missing_policy</c>.
        /// </summary>
        Missing = 6,
        /// <summary>
        /// A command this peer predicted for an entity it does not own drove
        /// the simulation, so the owner never authored the input the transition
        /// ran.
        /// </summary>
        Substituted = 7,
    }

    public enum TriggerShape : long
    {
        /// <summary>
        /// No field that can trigger was past its own tolerance. The
        /// fingerprints can still disagree while every field sits inside its
        /// tolerance, so a recovery can be prepared with nothing having asked
        /// for one. A <see cref="NetwPredict.TriggerShape"/> records what the
        /// triggering fields looked like when the recovery was judged. The
        /// distinction that matters is whether the recovery could write any of
        /// them. A write returning a withheld field and a writable one did
        /// repair something, while a write whose every trigger was withheld
        /// repaired nothing.
        /// </summary>
        None = 0,
        /// <summary>
        /// At least one field past its epsilon is one a sub-teleport restore
        /// may write.
        /// </summary>
        Mixed = 1,
        /// <summary>
        /// Every field past its epsilon is one no sub-teleport restore may
        /// write.
        /// </summary>
        AllWithheld = 2,
    }

    public enum ConsumeAction : long
    {
        /// <summary>
        /// A queued transition is available past the buffer being held, so it
        /// runs.
        /// </summary>
        Replay = 0,
        /// <summary>
        /// Transitions are queued but not yet past the buffer, so the pass
        /// waits.
        /// </summary>
        Hold = 1,
        /// <summary>
        /// Nothing is queued at all, so the pass has no command to run.
        /// </summary>
        Starved = 2,
    }

    public enum ExactVerdict : long
    {
        /// <summary>
        /// Nobody has compared fingerprints for this transition yet.
        /// </summary>
        Unjudged = 0,
        /// <summary>
        /// The two independently recorded fingerprints are equal.
        /// </summary>
        Equal = 1,
        /// <summary>
        /// The two independently recorded fingerprints differ.
        /// </summary>
        Unequal = 2,
    }

    public enum MissingInput : long
    {
        /// <summary>
        /// With no input, the entity does not move.
        /// </summary>
        Stall = 0,
        /// <summary>
        /// Carry the last input forward over the gap.
        /// </summary>
        RepeatLast = 1,
    }

    public enum CorrectionMode : long
    {
        /// <summary>
        /// Decide from what the body is. A kinematic body gets
        /// <see cref="NetwPredict.CorrectionMode.Replay"/> and a dynamic one
        /// gets <see cref="NetwPredict.CorrectionMode.Snap"/>.
        /// </summary>
        Auto = 0,
        /// <summary>
        /// Restore authoritative state, then replay every unacked input over
        /// it.
        /// </summary>
        Replay = 1,
        /// <summary>
        /// Restore authoritative state and stop, with no replay.
        /// </summary>
        Snap = 2,
    }

    public enum RestoreMode : long
    {
        /// <summary>
        /// Write the state that arrived, exactly, at the tick it belongs to.
        /// </summary>
        Exact = 0,
        /// <summary>
        /// Project each carry-declaring field forward to the present tick by
        /// its replicated velocity before restoring, so a dynamic body lands
        /// near where it is instead of snapping back to a stale tick.
        /// </summary>
        Extrapolated = 1,
    }

    public enum Archetype : long
    {
        /// <summary>
        /// No preset, so every setting keeps its own default until something
        /// declares it. An archetype is a starting point rather than a limit.
        /// Writing one applies its settings, and anything declared afterwards
        /// overrides what it applied. No archetype sets a
        /// <see cref="NetwPredict.BreachResponse"/>, because that decides
        /// whether a body stops predicting at all, and a preset choosing it
        /// would change the most visible behaviour an entity has with no game
        /// file saying so.
        /// </summary>
        None = 0,
        /// <summary>
        /// A body whose step is ordinary code and can be re-run inside one
        /// frame. It sets <see cref="NetwPredict.Schedule.Tick"/>,
        /// <see cref="NetwPredict.MissingInput.Stall"/> and
        /// <see cref="NetwPredict.RecoveryPolicy.RebaseReplay"/>, because a
        /// velocity that comes straight from the input catches up again on the
        /// next tick.
        /// </summary>
        Kinematic = 1,
        /// <summary>
        /// A body the physics engine solves, whose step cannot be re-run once
        /// per input. It sets <see cref="NetwPredict.Schedule.Frame"/>,
        /// <see cref="NetwPredict.MissingInput.RepeatLast"/>,
        /// <see cref="NetwPredict.RecoveryPolicy.RebaseRecover"/> and
        /// <see cref="NetwPredict.RestoreMode.Extrapolated"/>, with a teleport
        /// distance sized for a body that settles through contacts.
        /// </summary>
        SolverBody = 2,
    }

    public enum RecoveryPolicy : long
    {
        /// <summary>
        /// Restore the acknowledged state and replay every unacknowledged input
        /// over it, which reaches the present through the entity's own
        /// simulation. <see cref="NetwPredictionHandle.RecoveryPolicy"/> is
        /// where an entity declares one, and it names what the entity wants
        /// rather than how the engine does it.
        /// </summary>
        RebaseReplay = 0,
        /// <summary>
        /// Restore the acknowledged state and write the correction directly,
        /// with no replay.
        /// </summary>
        RebaseRecover = 1,
        /// <summary>
        /// Do not predict at all. Simulate only where the input is already
        /// authoritative, and draw what arrives everywhere else.
        /// </summary>
        DelayClosed = 2,
        /// <summary>
        /// Report the divergence and write nothing. An entity under this policy
        /// can hold an episode open for as long as it keeps diverging, and it
        /// can never oscillate between corrections, because it makes none.
        /// </summary>
        Observe = 3,
    }

    public enum Fidelity : long
    {
        /// <summary>
        /// Draw the state that arrives, and treat contact with it as contact
        /// with a stand-in.
        /// </summary>
        Proxy = 0,
        /// <summary>
        /// Step the member locally with substituted commands.
        /// </summary>
        Simulated = 1,
    }

    public enum Promotion : long
    {
        /// <summary>
        /// Promote nothing on its own. A member named outright through
        /// <see cref="NetwPredictIsland.Simulate"/> is still promoted, because
        /// naming one is not a policy and this decides only what happens to the
        /// members nobody named. The two policies differ in what limits them. A
        /// count is a budget a game knows it can afford, and a radius is a
        /// claim about where contact can happen.
        /// </summary>
        None = 0,
        /// <summary>
        /// Promote the nearest <c>promotion_count</c> produced members.
        /// </summary>
        Nearest = 1,
        /// <summary>
        /// Promote produced members within <c>promotion_meters</c>.
        /// </summary>
        Within = 2,
        /// <summary>
        /// Promote every produced member. The honest expensive mode of a joint
        /// group, where partial promotion is meaningless.
        /// </summary>
        All = 3,
    }

    public enum Pacing : long
    {
        /// <summary>
        /// Open a transition as soon as there is one to open, and correct it
        /// afterwards.
        /// </summary>
        Speculate = 0,
        /// <summary>
        /// Open a transition only when every member's command for it is in
        /// hand. Nothing speculates, nothing rolls back, and the cost is the
        /// declared input delay plus the slowest peer's transport.
        /// </summary>
        DelayClosed = 1,
    }

    public enum Reconcile : long
    {
        /// <summary>
        /// Correct each predicted entity on its own.
        /// </summary>
        Independent = 0,
        /// <summary>
        /// Restore and replay the island together. The engine admits the group
        /// at membership commit, where every member's schedule is known. An
        /// authoritative row a member receives here is where a replay starts
        /// from rather than somewhere to jump to. The group replays from one
        /// floor, so a member that snapped to wherever its own extrapolated row
        /// landed would enter that replay from a state no other member's
        /// history knows about. The unextrapolated payload is the basis, and
        /// the pass re-runs the transitions the extrapolation was standing in
        /// for.
        /// </summary>
        Joint = 1,
    }

    public enum CellProvenance : long
    {
        /// <summary>
        /// Nothing named this one, so it coasts on the value it already held.
        /// </summary>
        Coast = 0,
        /// <summary>
        /// A registered command predictor guessed the cell for an entity this
        /// peer does not own.
        /// </summary>
        Substituted = 1,
        /// <summary>
        /// The authoring peer's own command reached here through the server.
        /// </summary>
        Relayed = 2,
        /// <summary>
        /// The owner authored this cell itself, which is the only provenance a
        /// replay reproduces rather than repeats.
        /// </summary>
        Authored = 3,
    }

    public enum BreachResponse : long
    {
        /// <summary>
        /// Keep predicting and let an ordinary recovery absorb whatever
        /// divergence follows. Touching the unmoving world is never a breach,
        /// because every peer solves against the same world. A breach is
        /// contact with a moving body this peer does not simulate, whose drawn
        /// pose is a stand-in the solve cannot reproduce.
        /// </summary>
        PredictThrough = 0,
        /// <summary>
        /// Follow authority immediately while commands continue to flow.
        /// </summary>
        Demote = 1,
    }

    public enum EpisodeState : long
    {
        /// <summary>
        /// The episode is still taking in comparisons and the results of
        /// recovery attempts.
        /// </summary>
        Open = 0,
        /// <summary>
        /// A verified agreement run retired the episode.
        /// </summary>
        Closed = 1,
        /// <summary>
        /// Bounded recovery evidence was exhausted.
        /// </summary>
        Fallback = 2,
    }

    public enum OperatorOutcome : long
    {
        /// <summary>
        /// No later comparison has judged the write yet.
        /// </summary>
        Pending = 0,
        /// <summary>
        /// A later comparison strictly reduced or closed the aligned error.
        /// </summary>
        Contracted = 1,
        /// <summary>
        /// The verification window held or grew the aligned error.
        /// </summary>
        FailedToContract = 2,
        /// <summary>
        /// The write introduced a realized boundary absent on authority.
        /// </summary>
        IntroducedBoundary = 3,
        /// <summary>
        /// Every field that asked for this recovery was one the recovery was
        /// declared never to write, so the error it holds belongs to the
        /// declaration rather than to the operator. It is recorded beside
        /// <see cref="NetwPredict.OperatorOutcome.FailedToContract"/> rather
        /// than as a kind of it, because the two look identical from outside
        /// and mean opposite things. One is an operator that tried and did not
        /// shrink the error, and the other is an operator that was forbidden to
        /// touch it. Spending an episode's evidence on the second turns a gap
        /// in the declaration into a breach, and a breach into a demotion,
        /// which leaves the game worse off than declaring nothing at all.
        /// </summary>
        Withheld = 4,
    }

    public enum VerdictReason : long
    {
        /// <summary>
        /// Nothing stood between the comparison and the body. Either it found
        /// agreement, or a recovery ran and decided what to write.
        /// <see cref="NetwPredictionHandle.StateEvaluated"/> reports a
        /// comparison, not a write. This value identifies paths that detect
        /// divergence without applying a correction.
        /// </summary>
        None = 0,
        /// <summary>
        /// No comparison ran. A masked set is reconciled only once the stream
        /// has seen its gain-edge full row, and before that edge a receive is
        /// recorded having judged nothing.
        /// </summary>
        AwaitingReconstruction = 1,
        /// <summary>
        /// The reseed's evidence-free horizon alignment is still waiting for
        /// its command epoch, so this receive is neither compared nor written.
        /// </summary>
        RealignPending = 2,
        /// <summary>
        /// The acknowledgement is at or before the reseed horizon, so the row
        /// returns for transitions the seed has already replaced.
        /// </summary>
        ReseedIgnored = 3,
        /// <summary>
        /// The first comparison after resuming disagreed, so the entity went
        /// straight back to following authority. It writes nothing, spends no
        /// evidence, and does not count against the next attempt, because a
        /// resume that was never proven says nothing a longer wait would not
        /// settle.
        /// </summary>
        ProbationRequarantine = 4,
        /// <summary>
        /// The episode's bounded recovery evidence ran out on this comparison,
        /// so speculation closed instead of correcting.
        /// </summary>
        EvidenceExhausted = 5,
        /// <summary>
        /// A transport is already staged against this divergence and owns the
        /// write that returns it.
        /// </summary>
        TransportPending = 6,
        /// <summary>
        /// A dissipation is already staged against this divergence.
        /// </summary>
        DissipatePending = 7,
        /// <summary>
        /// The comparison chose to let the divergence fade without writing a
        /// correction.
        /// </summary>
        Dissipated = 8,
        /// <summary>
        /// The operator is deferred until an authority witness covers the
        /// boundary it would rebase across.
        /// </summary>
        WitnessDeferred = 9,
        /// <summary>
        /// The ladder ran and the recovery it selected declined to write.
        /// </summary>
        Declined = 10,
    }

    /// <summary>
    /// The unacknowledged span, in transitions, past which the prediction
    /// governor stops speculating and holds. A hard limit rather than something
    /// to tune. It is a quarter of the 256 transitions the engine records, so
    /// how far ahead an entity may run can never outrun the record a recovery
    /// would replay against. Read it beside
    /// <see cref="NetwPredictionHandle.AckAgeTicks"/>.
    /// </summary>
    public const long AckAgeMax = 64;

    private static readonly IntPtr _bindJointFloor =
        NetwApi.MethodBind("NetwPredict", "joint_floor", 1249350991UL);

    /// <summary>
    /// The one transition a joint group replays from, as <c>floor</c>, and
    /// whether reaching it needed a heal, as <c>heal</c>. The floor is the
    /// oldest point any member still needs, because a group replaying from a
    /// newer one would leave a member re-running transitions its own history no
    /// longer covers. A negative value is a member with nothing outstanding and
    /// does not lower the floor. A floor older than
    /// <paramref name="historyFloor"/> is one no member can still replay
    /// across, so the group heals to <paramref name="present"/> instead and
    /// says so. A caller reading <c>floor</c> without <c>heal</c> cannot tell a
    /// group that rewound from one that gave up on rewinding.
    /// <code>
    /// Dictionary
    /// ┠╴floor  int   the transition the group replays from
    /// ┖╴heal   bool  true when no member's floor could be honored
    /// </code>
    /// </summary>
    public static Godot.Collections.Dictionary JointFloor(
        Godot.Collections.Dictionary bases,
        Godot.Collections.Dictionary relayFloors,
        long epochFloor,
        long historyFloor,
        long present)
    {
        IntPtr pack = NetwThunks.ArgsNew(5);
        godot_variant slot0 = VariantUtils.CreateFromDictionary(bases);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        godot_variant slot1 = VariantUtils.CreateFromDictionary(relayFloors);
        NetwThunks.ArgsSet(pack, 1, in slot1);
        slot1.Dispose();
        godot_variant slot2 = VariantUtils.CreateFromInt((long)epochFloor);
        NetwThunks.ArgsSet(pack, 2, in slot2);
        slot2.Dispose();
        godot_variant slot3 = VariantUtils.CreateFromInt((long)historyFloor);
        NetwThunks.ArgsSet(pack, 3, in slot3);
        slot3.Dispose();
        godot_variant slot4 = VariantUtils.CreateFromInt((long)present);
        NetwThunks.ArgsSet(pack, 4, in slot4);
        slot4.Dispose();
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindJointFloor,
            IntPtr.Zero,
            pack,
            5,
            ref answered);
        NetwThunks.ArgsFree(pack);
        Godot.Collections.Dictionary result =
            VariantUtils.ConvertToDictionary(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindJointCell =
        NetwApi.MethodBind("NetwPredict", "joint_cell", 343996642UL);

    /// <summary>
    /// The <see cref="NetwPredict.CellProvenance"/> one replayed input
    /// receives, ranked. What the owner actually did outranks a relay, a relay
    /// outranks a substituted guess, and one with none of the three coasts on
    /// what it already held. Ranked rather than exclusive because more than one
    /// can be true at once, and a replay that charged the weaker of two would
    /// report a guess where authorship was reproduced.
    /// </summary>
    public static int JointCell(
        bool authored,
        bool relayed,
        bool predictorValid)
    {
        byte slot0 = authored ? (byte)1 : (byte)0;
        byte slot1 = relayed ? (byte)1 : (byte)0;
        byte slot2 = predictorValid ? (byte)1 : (byte)0;
        int answered = default;
        NetwThunks.Ptrcall3_Byte_Byte_Byte_Int(
            _bindJointCell,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref answered);
        return answered;
    }

    private static readonly IntPtr _bindScheduleName =
        NetwApi.MethodBind("NetwPredict", "schedule_name", 2113299152UL);

    /// <summary>
    /// The <see cref="NetwPredict.Schedule"/> member
    /// <paramref name="schedule"/> names, without its prefix. Returns with the
    /// decimal value when it names no member, so a capture written by a newer
    /// build stays readable rather than reporting a wrong name.
    /// </summary>
    public static string ScheduleName(NetwPredict.Schedule schedule)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)schedule);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindScheduleName,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        string result = VariantUtils.ConvertToString(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindDriveKindName =
        NetwApi.MethodBind("NetwPredict", "drive_kind_name", 1383288956UL);

    /// <summary>
    /// The <see cref="NetwPredict.DriveKind"/> member <paramref name="kind"/>
    /// names, without its prefix. Returns with the decimal value when it names
    /// no member, so a capture written by a newer build stays readable rather
    /// than reporting a wrong name.
    /// </summary>
    public static string DriveKindName(NetwPredict.DriveKind kind)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)kind);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindDriveKindName,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        string result = VariantUtils.ConvertToString(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindVerdictReasonName =
        NetwApi.MethodBind("NetwPredict", "verdict_reason_name", 4160287344UL);

    /// <summary>
    /// The <see cref="NetwPredict.VerdictReason"/> member
    /// <paramref name="reason"/> names, without its prefix. Returns with the
    /// decimal value when it names no member, so a capture written by a newer
    /// build stays readable rather than reporting a wrong name.
    /// </summary>
    public static string VerdictReasonName(NetwPredict.VerdictReason reason)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)reason);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindVerdictReasonName,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        string result = VariantUtils.ConvertToString(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindEpisodeStateName =
        NetwApi.MethodBind("NetwPredict", "episode_state_name", 2539266548UL);

    /// <summary>
    /// The <see cref="NetwPredict.EpisodeState"/> member
    /// <paramref name="state"/> names, without its prefix. Returns with the
    /// decimal value when it names no member, so a capture written by a newer
    /// build stays readable rather than reporting a wrong name.
    /// </summary>
    public static string EpisodeStateName(NetwPredict.EpisodeState state)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)state);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindEpisodeStateName,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        string result = VariantUtils.ConvertToString(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindOperatorOutcomeName =
        NetwApi.MethodBind("NetwPredict", "operator_outcome_name", 990163283UL);

    public static string OperatorOutcomeName(int outcome)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)outcome);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindOperatorOutcomeName,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        string result = VariantUtils.ConvertToString(answered);
        answered.Dispose();
        return result;
    }
}
