// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// One live binding of a <see cref="NetwPropertySet"/> to the node that
/// declares it through <see cref="Netw.ConfigureProperty"/>, the route-keyed
/// gather source for a state or input group.
/// </summary>
/// <remarks>
/// The shell captures <see cref="NetwPropertySetBinding.Route"/>,
/// <see cref="NetwPropertySetBinding.Comp"/>, and
/// <see cref="NetwPropertySetBinding.OrderKey"/> at registration. The set
/// carries the wire contract, while the binding carries the live gather state:
/// the two lanes' rows, the windowed input ring, and the row each lane last
/// merged a frame onto. A set's <see cref="NetwPropertySet.Lane.Volatile"/>
/// fields ride the SYNC_ROW channel freshest-wins, and its
/// <see cref="NetwPropertySet.Lane.Retained"/> fields ride the reliable
/// SYNC_ROW_DELTA lane only when they change, so the two lanes of one set never
/// re-send each other. Both lanes offer the whole row every pass and neither
/// decides what a recipient is owed. The send plane holds one baseline per peer
/// per stream, a stream being one route, one component ordinal and one lane,
/// and returns the columns that moved, which is why a binding carries no
/// per-peer book of its own.
/// </remarks>
public sealed class NetwPropertySetBinding : NetwRefCounted
{
    public NetwPropertySetBinding(IntPtr native) : base(native)
    {
    }

    public static NetwPropertySetBinding Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwPropertySetBinding(
            native);
    }

    public static NetwPropertySetBinding From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    private static readonly IntPtr _bindGetSet =
        NetwApi.MethodBind("NetwPropertySetBinding", "get_set", 1264756376UL);

    private static readonly IntPtr _bindSetSet =
        NetwApi.MethodBind("NetwPropertySetBinding", "set_set", 2351675682UL);

    /// <summary>
    /// The declaration this binding is a live instance of.
    /// </summary>
    public NetwPropertySet Set
    {
        get
        {
            IntPtr answered = default;
            NetwThunks.Ptrcall0_IntPtr(_bindGetSet, Checked, ref answered);
            return NetwPropertySet.Adopt(answered);
        }
        set
        {
            IntPtr slot0 = value?.Native ?? IntPtr.Zero;
            long discarded = default;
            NetwThunks.Ptrcall1_IntPtr_Long(
                _bindSetSet,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetRoute =
        NetwApi.MethodBind("NetwPropertySetBinding", "get_route", 3905245786UL);

    private static readonly IntPtr _bindSetRoute =
        NetwApi.MethodBind("NetwPropertySetBinding", "set_route", 1286410249UL);

    /// <summary>
    /// Cached entity route. A zero value has not bound to liveness yet.
    /// </summary>
    public long Route
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetRoute, Checked, ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetRoute,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetComp =
        NetwApi.MethodBind("NetwPropertySetBinding", "get_comp", 3905245786UL);

    private static readonly IntPtr _bindSetComp =
        NetwApi.MethodBind("NetwPropertySetBinding", "set_comp", 1286410249UL);

    /// <summary>
    /// Registered component address under the entity root.
    /// </summary>
    public long Comp
    {
        get
        {
            long answered = default;
            NetwThunks.Ptrcall0_Long(_bindGetComp, Checked, ref answered);
            return answered;
        }
        set
        {
            long slot0 = value;
            long discarded = default;
            NetwThunks.Ptrcall1_Long_Long(
                _bindSetComp,
                Checked,
                in slot0,
                ref discarded);
        }
    }

    private static readonly IntPtr _bindGetOrderKey =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "get_order_key",
            2002593661UL);

    private static readonly IntPtr _bindSetOrderKey =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "set_order_key",
            3304788590UL);

    /// <summary>
    /// Stable registration key used by the session's declaration table.
    /// </summary>
    public StringName OrderKey
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetOrderKey, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromStringName(value);
            godot_variant answered = default;
            NetwThunks.Call1(_bindSetOrderKey, Checked, in slot0, ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindGetOnApplied =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "get_on_applied",
            1307783378UL);

    private static readonly IntPtr _bindSetOnApplied =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "set_on_applied",
            1611583062UL);

    /// <summary>
    /// Called once per committed row, with the decoded header <c>{ordinal,
    /// tick, ack, payload, samples?}</c>. It observes a row the receiver has
    /// already committed and cannot refuse one, so raising an error here does
    /// not undo it. A refused row never reaches this call. A prediction engine
    /// subscribes here so a state receive drives reconciliation and an input
    /// receive opens the consume cursor. Unset for a plain display set, which
    /// just snaps the node.
    /// </summary>
    public Callable OnApplied
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetOnApplied, Checked, ref answered);
            Callable result = VariantUtils.ConvertToCallable(answered);
            answered.Dispose();
            return result;
        }
        set
        {
            godot_variant slot0 = VariantUtils.CreateFromCallable(value);
            godot_variant answered = default;
            NetwThunks.Call1(
                _bindSetOnApplied,
                Checked,
                in slot0,
                ref answered);
            slot0.Dispose();
            answered.Dispose();
        }
    }

    private static readonly IntPtr _bindNode =
        NetwApi.MethodBind("NetwPropertySetBinding", "node", 3160264692UL);

    /// <summary>
    /// Returns the declaring node, or <c>null</c> once it has freed.
    /// </summary>
    public Node Node()
    {
        godot_variant answered = default;
        NetwThunks.Call0(_bindNode, Checked, ref answered);
        Node result = (Node)VariantUtils.ConvertToGodotObject(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindIsActive =
        NetwApi.MethodBind("NetwPropertySetBinding", "is_active", 36873697UL);

    /// <summary>
    /// Returns <c>true</c> while the node is alive, in the tree, and holds
    /// authority over the stream.
    /// </summary>
    public bool IsActive()
    {
        byte answered = default;
        NetwThunks.Ptrcall0_Byte(_bindIsActive, Checked, ref answered);
        return answered != 0;
    }

    private static readonly IntPtr _bindIsWindowed =
        NetwApi.MethodBind("NetwPropertySetBinding", "is_windowed", 36873697UL);

    /// <summary>
    /// Returns whether this binding's volatile lane rides the redundant sample
    /// ring rather than a single row, which is what routes it onto the
    /// SYNC_ROW_WINDOW channel.
    /// </summary>
    public bool IsWindowed()
    {
        byte answered = default;
        NetwThunks.Ptrcall0_Byte(_bindIsWindowed, Checked, ref answered);
        return answered != 0;
    }

    private static readonly IntPtr _bindPropertyClassOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "property_class_of",
            2458036349UL);

    /// <summary>
    /// Returns what <paramref name="property"/> does in the simulation, or
    /// <see cref="NetwPropertySet.PropertyClass.Causal"/> when the set does not
    /// declare it. Reconciliation uses this to decide which values it may
    /// compare and restore. Undeclared properties default to causal recovery.
    /// </summary>
    public long PropertyClassOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(_bindPropertyClassOf, Checked, in slot0, ref answered);
        slot0.Dispose();
        long result = VariantUtils.ConvertToInt64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConvergeStiffnessOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "converge_stiffness_of",
            2349060816UL);

    /// <summary>
    /// Returns how firmly a recovery pulls <paramref name="property"/> toward
    /// the authoritative value, or <c>0.0</c> when it is restored outright.
    /// </summary>
    public double ConvergeStiffnessOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConvergeStiffnessOf,
            Checked,
            in slot0,
            ref answered);
        slot0.Dispose();
        double result = VariantUtils.ConvertToFloat64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindCarryChannelOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "carry_channel_of",
            1965194235UL);

    /// <summary>
    /// Returns the sibling channel a recovery advances
    /// <paramref name="property"/> along, or an empty <see cref="StringName"/>
    /// when it is restored at the acknowledged value.
    /// </summary>
    public StringName CarryChannelOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(_bindCarryChannelOf, Checked, in slot0, ref answered);
        slot0.Dispose();
        StringName result = VariantUtils.ConvertToStringName(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindTeleportOnlyOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "teleport_only_of",
            2619796661UL);

    /// <summary>
    /// Returns whether <paramref name="property"/> is restored only by a
    /// teleport-tier recovery.
    /// </summary>
    public bool TeleportOnlyOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(_bindTeleportOnlyOf, Checked, in slot0, ref answered);
        slot0.Dispose();
        bool result = VariantUtils.ConvertToBool(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindReconcileOnlyOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "reconcile_only_of",
            2619796661UL);

    /// <summary>
    /// Returns whether <paramref name="property"/> is excluded from triggering
    /// a correction on its own.
    /// </summary>
    public bool ReconcileOnlyOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(_bindReconcileOnlyOf, Checked, in slot0, ref answered);
        slot0.Dispose();
        bool result = VariantUtils.ConvertToBool(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindEpsilonOverrideOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "epsilon_override_of",
            2349060816UL);

    /// <summary>
    /// Returns <paramref name="property"/>'s own divergence threshold, or a
    /// negative value when it inherits the entity's default.
    /// </summary>
    public double EpsilonOverrideOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindEpsilonOverrideOf,
            Checked,
            in slot0,
            ref answered);
        slot0.Dispose();
        double result = VariantUtils.ConvertToFloat64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindTeleportAtOf =
        NetwApi.MethodBind(
            "NetwPropertySetBinding",
            "teleport_at_of",
            2349060816UL);

    /// <summary>
    /// Returns <paramref name="property"/>'s own teleport-tier distance, or a
    /// negative value when it inherits the entity's default.
    /// </summary>
    public double TeleportAtOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(_bindTeleportAtOf, Checked, in slot0, ref answered);
        slot0.Dispose();
        double result = VariantUtils.ConvertToFloat64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindFieldOf =
        NetwApi.MethodBind("NetwPropertySetBinding", "field_of", 1890347125UL);

    /// <summary>
    /// Returns the declared <see cref="NetwPropertySetColumn"/> for
    /// <paramref name="property"/>, or <c>null</c> when this set does not carry
    /// it.
    /// </summary>
    public NetwPropertySetColumn FieldOf(StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call1(_bindFieldOf, Checked, in slot0, ref answered);
        slot0.Dispose();
        NetwPropertySetColumn result =
            NetwPropertySetColumn.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }
}
