// <auto-generated/>
using System;
using System.Runtime.InteropServices;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// The fixed-arity entry points every generated body calls through.
/// </summary>
/// <remarks>
/// The addon exports one native function per arity rather than one variadic
/// one, so each argument is its own parameter and the CLR passes its address.
/// That is what lets these bindings compile in a project that has not set
/// <c>AllowUnsafeBlocks</c>.
/// </remarks>
internal static class NetwThunks
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        ref IntPtr answered);

    private static Ptrcall0_IntPtrFn _ptrcall0_IntPtr;

    internal static void Ptrcall0_IntPtr(
        IntPtr bind,
        IntPtr instance,
        ref IntPtr answered)
    {
        Ptrcall0_IntPtrFn thunk =
            _ptrcall0_IntPtr ??= NetwApi.Thunk<Ptrcall0_IntPtrFn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_Rect2Fn(
        IntPtr bind,
        IntPtr instance,
        ref Rect2 answered);

    private static Ptrcall0_Rect2Fn _ptrcall0_Rect2;

    internal static void Ptrcall0_Rect2(
        IntPtr bind,
        IntPtr instance,
        ref Rect2 answered)
    {
        Ptrcall0_Rect2Fn thunk =
            _ptrcall0_Rect2 ??= NetwApi.Thunk<Ptrcall0_Rect2Fn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_RidFn(
        IntPtr bind,
        IntPtr instance,
        ref Rid answered);

    private static Ptrcall0_RidFn _ptrcall0_Rid;

    internal static void Ptrcall0_Rid(
        IntPtr bind,
        IntPtr instance,
        ref Rid answered)
    {
        Ptrcall0_RidFn thunk =
            _ptrcall0_Rid ??= NetwApi.Thunk<Ptrcall0_RidFn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_Vector2IFn(
        IntPtr bind,
        IntPtr instance,
        ref Vector2I answered);

    private static Ptrcall0_Vector2IFn _ptrcall0_Vector2I;

    internal static void Ptrcall0_Vector2I(
        IntPtr bind,
        IntPtr instance,
        ref Vector2I answered)
    {
        Ptrcall0_Vector2IFn thunk =
            _ptrcall0_Vector2I ??= NetwApi.Thunk<Ptrcall0_Vector2IFn>(
                "ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_ByteFn(
        IntPtr bind,
        IntPtr instance,
        ref byte answered);

    private static Ptrcall0_ByteFn _ptrcall0_Byte;

    internal static void Ptrcall0_Byte(
        IntPtr bind,
        IntPtr instance,
        ref byte answered)
    {
        Ptrcall0_ByteFn thunk =
            _ptrcall0_Byte ??= NetwApi.Thunk<Ptrcall0_ByteFn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_DoubleFn(
        IntPtr bind,
        IntPtr instance,
        ref double answered);

    private static Ptrcall0_DoubleFn _ptrcall0_Double;

    internal static void Ptrcall0_Double(
        IntPtr bind,
        IntPtr instance,
        ref double answered)
    {
        Ptrcall0_DoubleFn thunk =
            _ptrcall0_Double ??= NetwApi.Thunk<Ptrcall0_DoubleFn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_IntFn(
        IntPtr bind,
        IntPtr instance,
        ref int answered);

    private static Ptrcall0_IntFn _ptrcall0_Int;

    internal static void Ptrcall0_Int(
        IntPtr bind,
        IntPtr instance,
        ref int answered)
    {
        Ptrcall0_IntFn thunk =
            _ptrcall0_Int ??= NetwApi.Thunk<Ptrcall0_IntFn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall0_LongFn(
        IntPtr bind,
        IntPtr instance,
        ref long answered);

    private static Ptrcall0_LongFn _ptrcall0_Long;

    internal static void Ptrcall0_Long(
        IntPtr bind,
        IntPtr instance,
        ref long answered)
    {
        Ptrcall0_LongFn thunk =
            _ptrcall0_Long ??= NetwApi.Thunk<Ptrcall0_LongFn>("ptrcall0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_IntPtr_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref IntPtr answered);

    private static Ptrcall1_IntPtr_IntPtrFn _ptrcall1_IntPtr_IntPtr;

    internal static void Ptrcall1_IntPtr_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref IntPtr answered)
    {
        Ptrcall1_IntPtr_IntPtrFn thunk =
            _ptrcall1_IntPtr_IntPtr ??= NetwApi.Thunk<Ptrcall1_IntPtr_IntPtrFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_IntPtr_RidFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref Rid answered);

    private static Ptrcall1_IntPtr_RidFn _ptrcall1_IntPtr_Rid;

    internal static void Ptrcall1_IntPtr_Rid(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref Rid answered)
    {
        Ptrcall1_IntPtr_RidFn thunk =
            _ptrcall1_IntPtr_Rid ??= NetwApi.Thunk<Ptrcall1_IntPtr_RidFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_IntPtr_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref byte answered);

    private static Ptrcall1_IntPtr_ByteFn _ptrcall1_IntPtr_Byte;

    internal static void Ptrcall1_IntPtr_Byte(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref byte answered)
    {
        Ptrcall1_IntPtr_ByteFn thunk =
            _ptrcall1_IntPtr_Byte ??= NetwApi.Thunk<Ptrcall1_IntPtr_ByteFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_IntPtr_IntFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref int answered);

    private static Ptrcall1_IntPtr_IntFn _ptrcall1_IntPtr_Int;

    internal static void Ptrcall1_IntPtr_Int(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref int answered)
    {
        Ptrcall1_IntPtr_IntFn thunk =
            _ptrcall1_IntPtr_Int ??= NetwApi.Thunk<Ptrcall1_IntPtr_IntFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref long answered);

    private static Ptrcall1_IntPtr_LongFn _ptrcall1_IntPtr_Long;

    internal static void Ptrcall1_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        ref long answered)
    {
        Ptrcall1_IntPtr_LongFn thunk =
            _ptrcall1_IntPtr_Long ??= NetwApi.Thunk<Ptrcall1_IntPtr_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_IntPtr_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        ref IntPtr answered);

    private static Ptrcall2_IntPtr_IntPtr_IntPtrFn _ptrcall2_IntPtr_IntPtr_IntPtr;

    internal static void Ptrcall2_IntPtr_IntPtr_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        ref IntPtr answered)
    {
        Ptrcall2_IntPtr_IntPtr_IntPtrFn thunk =
            _ptrcall2_IntPtr_IntPtr_IntPtr ??= NetwApi.Thunk<Ptrcall2_IntPtr_IntPtr_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_IntPtr_RidFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        ref Rid answered);

    private static Ptrcall2_IntPtr_IntPtr_RidFn _ptrcall2_IntPtr_IntPtr_Rid;

    internal static void Ptrcall2_IntPtr_IntPtr_Rid(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        ref Rid answered)
    {
        Ptrcall2_IntPtr_IntPtr_RidFn thunk =
            _ptrcall2_IntPtr_IntPtr_Rid ??= NetwApi.Thunk<Ptrcall2_IntPtr_IntPtr_RidFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        ref long answered);

    private static Ptrcall2_IntPtr_IntPtr_LongFn _ptrcall2_IntPtr_IntPtr_Long;

    internal static void Ptrcall2_IntPtr_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        ref long answered)
    {
        Ptrcall2_IntPtr_IntPtr_LongFn thunk =
            _ptrcall2_IntPtr_IntPtr_Long ??= NetwApi.Thunk<Ptrcall2_IntPtr_IntPtr_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_IntPtr_IntPtr_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        in IntPtr a2,
        ref long answered);

    private static Ptrcall3_IntPtr_IntPtr_IntPtr_LongFn _ptrcall3_IntPtr_IntPtr_IntPtr_Long;

    internal static void Ptrcall3_IntPtr_IntPtr_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        in IntPtr a2,
        ref long answered)
    {
        Ptrcall3_IntPtr_IntPtr_IntPtr_LongFn thunk =
            _ptrcall3_IntPtr_IntPtr_IntPtr_Long ??= NetwApi.Thunk<Ptrcall3_IntPtr_IntPtr_IntPtr_LongFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_IntPtr_IntPtr_Int_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        in int a2,
        ref long answered);

    private static Ptrcall3_IntPtr_IntPtr_Int_LongFn _ptrcall3_IntPtr_IntPtr_Int_Long;

    internal static void Ptrcall3_IntPtr_IntPtr_Int_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        in int a2,
        ref long answered)
    {
        Ptrcall3_IntPtr_IntPtr_Int_LongFn thunk =
            _ptrcall3_IntPtr_IntPtr_Int_Long ??= NetwApi.Thunk<Ptrcall3_IntPtr_IntPtr_Int_LongFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_IntPtr_IntPtr_Long_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        in long a2,
        ref IntPtr answered);

    private static Ptrcall3_IntPtr_IntPtr_Long_IntPtrFn _ptrcall3_IntPtr_IntPtr_Long_IntPtr;

    internal static void Ptrcall3_IntPtr_IntPtr_Long_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in IntPtr a1,
        in long a2,
        ref IntPtr answered)
    {
        Ptrcall3_IntPtr_IntPtr_Long_IntPtrFn thunk =
            _ptrcall3_IntPtr_IntPtr_Long_IntPtr ??= NetwApi.Thunk<Ptrcall3_IntPtr_IntPtr_Long_IntPtrFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_Int_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in int a1,
        ref IntPtr answered);

    private static Ptrcall2_IntPtr_Int_IntPtrFn _ptrcall2_IntPtr_Int_IntPtr;

    internal static void Ptrcall2_IntPtr_Int_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in int a1,
        ref IntPtr answered)
    {
        Ptrcall2_IntPtr_Int_IntPtrFn thunk =
            _ptrcall2_IntPtr_Int_IntPtr ??= NetwApi.Thunk<Ptrcall2_IntPtr_Int_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_Int_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in int a1,
        ref long answered);

    private static Ptrcall2_IntPtr_Int_LongFn _ptrcall2_IntPtr_Int_Long;

    internal static void Ptrcall2_IntPtr_Int_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in int a1,
        ref long answered)
    {
        Ptrcall2_IntPtr_Int_LongFn thunk =
            _ptrcall2_IntPtr_Int_Long ??= NetwApi.Thunk<Ptrcall2_IntPtr_Int_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_Long_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        ref IntPtr answered);

    private static Ptrcall2_IntPtr_Long_IntPtrFn _ptrcall2_IntPtr_Long_IntPtr;

    internal static void Ptrcall2_IntPtr_Long_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        ref IntPtr answered)
    {
        Ptrcall2_IntPtr_Long_IntPtrFn thunk =
            _ptrcall2_IntPtr_Long_IntPtr ??= NetwApi.Thunk<Ptrcall2_IntPtr_Long_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_Long_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        ref byte answered);

    private static Ptrcall2_IntPtr_Long_ByteFn _ptrcall2_IntPtr_Long_Byte;

    internal static void Ptrcall2_IntPtr_Long_Byte(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        ref byte answered)
    {
        Ptrcall2_IntPtr_Long_ByteFn thunk =
            _ptrcall2_IntPtr_Long_Byte ??= NetwApi.Thunk<Ptrcall2_IntPtr_Long_ByteFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_IntPtr_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        ref long answered);

    private static Ptrcall2_IntPtr_Long_LongFn _ptrcall2_IntPtr_Long_Long;

    internal static void Ptrcall2_IntPtr_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        ref long answered)
    {
        Ptrcall2_IntPtr_Long_LongFn thunk =
            _ptrcall2_IntPtr_Long_Long ??= NetwApi.Thunk<Ptrcall2_IntPtr_Long_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_IntPtr_Long_Byte_LongFn(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        in byte a2,
        ref long answered);

    private static Ptrcall3_IntPtr_Long_Byte_LongFn _ptrcall3_IntPtr_Long_Byte_Long;

    internal static void Ptrcall3_IntPtr_Long_Byte_Long(
        IntPtr bind,
        IntPtr instance,
        in IntPtr a0,
        in long a1,
        in byte a2,
        ref long answered)
    {
        Ptrcall3_IntPtr_Long_Byte_LongFn thunk =
            _ptrcall3_IntPtr_Long_Byte_Long ??= NetwApi.Thunk<Ptrcall3_IntPtr_Long_Byte_LongFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Rect2I_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rect2I a0,
        ref long answered);

    private static Ptrcall1_Rect2I_LongFn _ptrcall1_Rect2I_Long;

    internal static void Ptrcall1_Rect2I_Long(
        IntPtr bind,
        IntPtr instance,
        in Rect2I a0,
        ref long answered)
    {
        Ptrcall1_Rect2I_LongFn thunk =
            _ptrcall1_Rect2I_Long ??= NetwApi.Thunk<Ptrcall1_Rect2I_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Rid_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref IntPtr answered);

    private static Ptrcall1_Rid_IntPtrFn _ptrcall1_Rid_IntPtr;

    internal static void Ptrcall1_Rid_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref IntPtr answered)
    {
        Ptrcall1_Rid_IntPtrFn thunk =
            _ptrcall1_Rid_IntPtr ??= NetwApi.Thunk<Ptrcall1_Rid_IntPtrFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Rid_RidFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref Rid answered);

    private static Ptrcall1_Rid_RidFn _ptrcall1_Rid_Rid;

    internal static void Ptrcall1_Rid_Rid(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref Rid answered)
    {
        Ptrcall1_Rid_RidFn thunk =
            _ptrcall1_Rid_Rid ??= NetwApi.Thunk<Ptrcall1_Rid_RidFn>("ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Rid_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref byte answered);

    private static Ptrcall1_Rid_ByteFn _ptrcall1_Rid_Byte;

    internal static void Ptrcall1_Rid_Byte(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref byte answered)
    {
        Ptrcall1_Rid_ByteFn thunk =
            _ptrcall1_Rid_Byte ??= NetwApi.Thunk<Ptrcall1_Rid_ByteFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Rid_IntFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref int answered);

    private static Ptrcall1_Rid_IntFn _ptrcall1_Rid_Int;

    internal static void Ptrcall1_Rid_Int(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref int answered)
    {
        Ptrcall1_Rid_IntFn thunk =
            _ptrcall1_Rid_Int ??= NetwApi.Thunk<Ptrcall1_Rid_IntFn>("ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Rid_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref long answered);

    private static Ptrcall1_Rid_LongFn _ptrcall1_Rid_Long;

    internal static void Ptrcall1_Rid_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        ref long answered)
    {
        Ptrcall1_Rid_LongFn thunk =
            _ptrcall1_Rid_Long ??= NetwApi.Thunk<Ptrcall1_Rid_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_IntPtr_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in IntPtr a1,
        ref IntPtr answered);

    private static Ptrcall2_Rid_IntPtr_IntPtrFn _ptrcall2_Rid_IntPtr_IntPtr;

    internal static void Ptrcall2_Rid_IntPtr_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in IntPtr a1,
        ref IntPtr answered)
    {
        Ptrcall2_Rid_IntPtr_IntPtrFn thunk =
            _ptrcall2_Rid_IntPtr_IntPtr ??= NetwApi.Thunk<Ptrcall2_Rid_IntPtr_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in IntPtr a1,
        ref long answered);

    private static Ptrcall2_Rid_IntPtr_LongFn _ptrcall2_Rid_IntPtr_Long;

    internal static void Ptrcall2_Rid_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in IntPtr a1,
        ref long answered)
    {
        Ptrcall2_Rid_IntPtr_LongFn thunk =
            _ptrcall2_Rid_IntPtr_Long ??= NetwApi.Thunk<Ptrcall2_Rid_IntPtr_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Rid_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in Rid a1,
        ref long answered);

    private static Ptrcall2_Rid_Rid_LongFn _ptrcall2_Rid_Rid_Long;

    internal static void Ptrcall2_Rid_Rid_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in Rid a1,
        ref long answered)
    {
        Ptrcall2_Rid_Rid_LongFn thunk =
            _ptrcall2_Rid_Rid_Long ??= NetwApi.Thunk<Ptrcall2_Rid_Rid_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_Rid_Rid_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in Rid a1,
        in long a2,
        ref long answered);

    private static Ptrcall3_Rid_Rid_Long_LongFn _ptrcall3_Rid_Rid_Long_Long;

    internal static void Ptrcall3_Rid_Rid_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in Rid a1,
        in long a2,
        ref long answered)
    {
        Ptrcall3_Rid_Rid_Long_LongFn thunk =
            _ptrcall3_Rid_Rid_Long_Long ??= NetwApi.Thunk<Ptrcall3_Rid_Rid_Long_LongFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Double_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in double a1,
        ref long answered);

    private static Ptrcall2_Rid_Double_LongFn _ptrcall2_Rid_Double_Long;

    internal static void Ptrcall2_Rid_Double_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in double a1,
        ref long answered)
    {
        Ptrcall2_Rid_Double_LongFn thunk =
            _ptrcall2_Rid_Double_Long ??= NetwApi.Thunk<Ptrcall2_Rid_Double_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Int_IntFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in int a1,
        ref int answered);

    private static Ptrcall2_Rid_Int_IntFn _ptrcall2_Rid_Int_Int;

    internal static void Ptrcall2_Rid_Int_Int(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in int a1,
        ref int answered)
    {
        Ptrcall2_Rid_Int_IntFn thunk =
            _ptrcall2_Rid_Int_Int ??= NetwApi.Thunk<Ptrcall2_Rid_Int_IntFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Int_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in int a1,
        ref long answered);

    private static Ptrcall2_Rid_Int_LongFn _ptrcall2_Rid_Int_Long;

    internal static void Ptrcall2_Rid_Int_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in int a1,
        ref long answered)
    {
        Ptrcall2_Rid_Int_LongFn thunk =
            _ptrcall2_Rid_Int_Long ??= NetwApi.Thunk<Ptrcall2_Rid_Int_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_Rid_Int_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in int a1,
        in IntPtr a2,
        ref long answered);

    private static Ptrcall3_Rid_Int_IntPtr_LongFn _ptrcall3_Rid_Int_IntPtr_Long;

    internal static void Ptrcall3_Rid_Int_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in int a1,
        in IntPtr a2,
        ref long answered)
    {
        Ptrcall3_Rid_Int_IntPtr_LongFn thunk =
            _ptrcall3_Rid_Int_IntPtr_Long ??= NetwApi.Thunk<Ptrcall3_Rid_Int_IntPtr_LongFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Long_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref IntPtr answered);

    private static Ptrcall2_Rid_Long_IntPtrFn _ptrcall2_Rid_Long_IntPtr;

    internal static void Ptrcall2_Rid_Long_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref IntPtr answered)
    {
        Ptrcall2_Rid_Long_IntPtrFn thunk =
            _ptrcall2_Rid_Long_IntPtr ??= NetwApi.Thunk<Ptrcall2_Rid_Long_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Long_RidFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref Rid answered);

    private static Ptrcall2_Rid_Long_RidFn _ptrcall2_Rid_Long_Rid;

    internal static void Ptrcall2_Rid_Long_Rid(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref Rid answered)
    {
        Ptrcall2_Rid_Long_RidFn thunk =
            _ptrcall2_Rid_Long_Rid ??= NetwApi.Thunk<Ptrcall2_Rid_Long_RidFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Long_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref byte answered);

    private static Ptrcall2_Rid_Long_ByteFn _ptrcall2_Rid_Long_Byte;

    internal static void Ptrcall2_Rid_Long_Byte(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref byte answered)
    {
        Ptrcall2_Rid_Long_ByteFn thunk =
            _ptrcall2_Rid_Long_Byte ??= NetwApi.Thunk<Ptrcall2_Rid_Long_ByteFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Long_IntFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref int answered);

    private static Ptrcall2_Rid_Long_IntFn _ptrcall2_Rid_Long_Int;

    internal static void Ptrcall2_Rid_Long_Int(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref int answered)
    {
        Ptrcall2_Rid_Long_IntFn thunk =
            _ptrcall2_Rid_Long_Int ??= NetwApi.Thunk<Ptrcall2_Rid_Long_IntFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Rid_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref long answered);

    private static Ptrcall2_Rid_Long_LongFn _ptrcall2_Rid_Long_Long;

    internal static void Ptrcall2_Rid_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in Rid a0,
        in long a1,
        ref long answered)
    {
        Ptrcall2_Rid_Long_LongFn thunk =
            _ptrcall2_Rid_Long_Long ??= NetwApi.Thunk<Ptrcall2_Rid_Long_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Vector2I_LongFn(
        IntPtr bind,
        IntPtr instance,
        in Vector2I a0,
        ref long answered);

    private static Ptrcall1_Vector2I_LongFn _ptrcall1_Vector2I_Long;

    internal static void Ptrcall1_Vector2I_Long(
        IntPtr bind,
        IntPtr instance,
        in Vector2I a0,
        ref long answered)
    {
        Ptrcall1_Vector2I_LongFn thunk =
            _ptrcall1_Vector2I_Long ??= NetwApi.Thunk<Ptrcall1_Vector2I_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Byte_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        ref IntPtr answered);

    private static Ptrcall1_Byte_IntPtrFn _ptrcall1_Byte_IntPtr;

    internal static void Ptrcall1_Byte_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        ref IntPtr answered)
    {
        Ptrcall1_Byte_IntPtrFn thunk =
            _ptrcall1_Byte_IntPtr ??= NetwApi.Thunk<Ptrcall1_Byte_IntPtrFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Byte_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        ref byte answered);

    private static Ptrcall1_Byte_ByteFn _ptrcall1_Byte_Byte;

    internal static void Ptrcall1_Byte_Byte(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        ref byte answered)
    {
        Ptrcall1_Byte_ByteFn thunk =
            _ptrcall1_Byte_Byte ??= NetwApi.Thunk<Ptrcall1_Byte_ByteFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Byte_LongFn(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        ref long answered);

    private static Ptrcall1_Byte_LongFn _ptrcall1_Byte_Long;

    internal static void Ptrcall1_Byte_Long(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        ref long answered)
    {
        Ptrcall1_Byte_LongFn thunk =
            _ptrcall1_Byte_Long ??= NetwApi.Thunk<Ptrcall1_Byte_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_Byte_Byte_Byte_IntFn(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        in byte a1,
        in byte a2,
        ref int answered);

    private static Ptrcall3_Byte_Byte_Byte_IntFn _ptrcall3_Byte_Byte_Byte_Int;

    internal static void Ptrcall3_Byte_Byte_Byte_Int(
        IntPtr bind,
        IntPtr instance,
        in byte a0,
        in byte a1,
        in byte a2,
        ref int answered)
    {
        Ptrcall3_Byte_Byte_Byte_IntFn thunk =
            _ptrcall3_Byte_Byte_Byte_Int ??= NetwApi.Thunk<Ptrcall3_Byte_Byte_Byte_IntFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Double_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        ref IntPtr answered);

    private static Ptrcall1_Double_IntPtrFn _ptrcall1_Double_IntPtr;

    internal static void Ptrcall1_Double_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        ref IntPtr answered)
    {
        Ptrcall1_Double_IntPtrFn thunk =
            _ptrcall1_Double_IntPtr ??= NetwApi.Thunk<Ptrcall1_Double_IntPtrFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Double_DoubleFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        ref double answered);

    private static Ptrcall1_Double_DoubleFn _ptrcall1_Double_Double;

    internal static void Ptrcall1_Double_Double(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        ref double answered)
    {
        Ptrcall1_Double_DoubleFn thunk =
            _ptrcall1_Double_Double ??= NetwApi.Thunk<Ptrcall1_Double_DoubleFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Double_LongFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        ref long answered);

    private static Ptrcall1_Double_LongFn _ptrcall1_Double_Long;

    internal static void Ptrcall1_Double_Long(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        ref long answered)
    {
        Ptrcall1_Double_LongFn thunk =
            _ptrcall1_Double_Long ??= NetwApi.Thunk<Ptrcall1_Double_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Double_Byte_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in byte a1,
        ref IntPtr answered);

    private static Ptrcall2_Double_Byte_IntPtrFn _ptrcall2_Double_Byte_IntPtr;

    internal static void Ptrcall2_Double_Byte_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in byte a1,
        ref IntPtr answered)
    {
        Ptrcall2_Double_Byte_IntPtrFn thunk =
            _ptrcall2_Double_Byte_IntPtr ??= NetwApi.Thunk<Ptrcall2_Double_Byte_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Double_Double_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in double a1,
        ref IntPtr answered);

    private static Ptrcall2_Double_Double_IntPtrFn _ptrcall2_Double_Double_IntPtr;

    internal static void Ptrcall2_Double_Double_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in double a1,
        ref IntPtr answered)
    {
        Ptrcall2_Double_Double_IntPtrFn thunk =
            _ptrcall2_Double_Double_IntPtr ??= NetwApi.Thunk<Ptrcall2_Double_Double_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Double_Double_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in double a1,
        ref byte answered);

    private static Ptrcall2_Double_Double_ByteFn _ptrcall2_Double_Double_Byte;

    internal static void Ptrcall2_Double_Double_Byte(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in double a1,
        ref byte answered)
    {
        Ptrcall2_Double_Double_ByteFn thunk =
            _ptrcall2_Double_Double_Byte ??= NetwApi.Thunk<Ptrcall2_Double_Double_ByteFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Double_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in long a1,
        ref long answered);

    private static Ptrcall2_Double_Long_LongFn _ptrcall2_Double_Long_Long;

    internal static void Ptrcall2_Double_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in double a0,
        in long a1,
        ref long answered)
    {
        Ptrcall2_Double_Long_LongFn thunk =
            _ptrcall2_Double_Long_Long ??= NetwApi.Thunk<Ptrcall2_Double_Long_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Int_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref IntPtr answered);

    private static Ptrcall1_Int_IntPtrFn _ptrcall1_Int_IntPtr;

    internal static void Ptrcall1_Int_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref IntPtr answered)
    {
        Ptrcall1_Int_IntPtrFn thunk =
            _ptrcall1_Int_IntPtr ??= NetwApi.Thunk<Ptrcall1_Int_IntPtrFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Int_RidFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref Rid answered);

    private static Ptrcall1_Int_RidFn _ptrcall1_Int_Rid;

    internal static void Ptrcall1_Int_Rid(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref Rid answered)
    {
        Ptrcall1_Int_RidFn thunk =
            _ptrcall1_Int_Rid ??= NetwApi.Thunk<Ptrcall1_Int_RidFn>("ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Int_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref byte answered);

    private static Ptrcall1_Int_ByteFn _ptrcall1_Int_Byte;

    internal static void Ptrcall1_Int_Byte(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref byte answered)
    {
        Ptrcall1_Int_ByteFn thunk =
            _ptrcall1_Int_Byte ??= NetwApi.Thunk<Ptrcall1_Int_ByteFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Int_LongFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref long answered);

    private static Ptrcall1_Int_LongFn _ptrcall1_Int_Long;

    internal static void Ptrcall1_Int_Long(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        ref long answered)
    {
        Ptrcall1_Int_LongFn thunk =
            _ptrcall1_Int_Long ??= NetwApi.Thunk<Ptrcall1_Int_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Int_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        in IntPtr a1,
        ref long answered);

    private static Ptrcall2_Int_IntPtr_LongFn _ptrcall2_Int_IntPtr_Long;

    internal static void Ptrcall2_Int_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        in IntPtr a1,
        ref long answered)
    {
        Ptrcall2_Int_IntPtr_LongFn thunk =
            _ptrcall2_Int_IntPtr_Long ??= NetwApi.Thunk<Ptrcall2_Int_IntPtr_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Int_Int_IntFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        in int a1,
        ref int answered);

    private static Ptrcall2_Int_Int_IntFn _ptrcall2_Int_Int_Int;

    internal static void Ptrcall2_Int_Int_Int(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        in int a1,
        ref int answered)
    {
        Ptrcall2_Int_Int_IntFn thunk =
            _ptrcall2_Int_Int_Int ??= NetwApi.Thunk<Ptrcall2_Int_Int_IntFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Int_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        in long a1,
        ref long answered);

    private static Ptrcall2_Int_Long_LongFn _ptrcall2_Int_Long_Long;

    internal static void Ptrcall2_Int_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in int a0,
        in long a1,
        ref long answered)
    {
        Ptrcall2_Int_Long_LongFn thunk =
            _ptrcall2_Int_Long_Long ??= NetwApi.Thunk<Ptrcall2_Int_Long_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Long_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref IntPtr answered);

    private static Ptrcall1_Long_IntPtrFn _ptrcall1_Long_IntPtr;

    internal static void Ptrcall1_Long_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref IntPtr answered)
    {
        Ptrcall1_Long_IntPtrFn thunk =
            _ptrcall1_Long_IntPtr ??= NetwApi.Thunk<Ptrcall1_Long_IntPtrFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Long_Vector2IFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref Vector2I answered);

    private static Ptrcall1_Long_Vector2IFn _ptrcall1_Long_Vector2I;

    internal static void Ptrcall1_Long_Vector2I(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref Vector2I answered)
    {
        Ptrcall1_Long_Vector2IFn thunk =
            _ptrcall1_Long_Vector2I ??= NetwApi.Thunk<Ptrcall1_Long_Vector2IFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Long_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref byte answered);

    private static Ptrcall1_Long_ByteFn _ptrcall1_Long_Byte;

    internal static void Ptrcall1_Long_Byte(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref byte answered)
    {
        Ptrcall1_Long_ByteFn thunk =
            _ptrcall1_Long_Byte ??= NetwApi.Thunk<Ptrcall1_Long_ByteFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Long_DoubleFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref double answered);

    private static Ptrcall1_Long_DoubleFn _ptrcall1_Long_Double;

    internal static void Ptrcall1_Long_Double(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref double answered)
    {
        Ptrcall1_Long_DoubleFn thunk =
            _ptrcall1_Long_Double ??= NetwApi.Thunk<Ptrcall1_Long_DoubleFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Long_IntFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref int answered);

    private static Ptrcall1_Long_IntFn _ptrcall1_Long_Int;

    internal static void Ptrcall1_Long_Int(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref int answered)
    {
        Ptrcall1_Long_IntFn thunk =
            _ptrcall1_Long_Int ??= NetwApi.Thunk<Ptrcall1_Long_IntFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall1_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref long answered);

    private static Ptrcall1_Long_LongFn _ptrcall1_Long_Long;

    internal static void Ptrcall1_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        ref long answered)
    {
        Ptrcall1_Long_LongFn thunk =
            _ptrcall1_Long_Long ??= NetwApi.Thunk<Ptrcall1_Long_LongFn>(
                "ptrcall1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Long_IntPtr_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in IntPtr a1,
        ref IntPtr answered);

    private static Ptrcall2_Long_IntPtr_IntPtrFn _ptrcall2_Long_IntPtr_IntPtr;

    internal static void Ptrcall2_Long_IntPtr_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in IntPtr a1,
        ref IntPtr answered)
    {
        Ptrcall2_Long_IntPtr_IntPtrFn thunk =
            _ptrcall2_Long_IntPtr_IntPtr ??= NetwApi.Thunk<Ptrcall2_Long_IntPtr_IntPtrFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Long_IntPtr_ByteFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in IntPtr a1,
        ref byte answered);

    private static Ptrcall2_Long_IntPtr_ByteFn _ptrcall2_Long_IntPtr_Byte;

    internal static void Ptrcall2_Long_IntPtr_Byte(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in IntPtr a1,
        ref byte answered)
    {
        Ptrcall2_Long_IntPtr_ByteFn thunk =
            _ptrcall2_Long_IntPtr_Byte ??= NetwApi.Thunk<Ptrcall2_Long_IntPtr_ByteFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Long_IntPtr_LongFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in IntPtr a1,
        ref long answered);

    private static Ptrcall2_Long_IntPtr_LongFn _ptrcall2_Long_IntPtr_Long;

    internal static void Ptrcall2_Long_IntPtr_Long(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in IntPtr a1,
        ref long answered)
    {
        Ptrcall2_Long_IntPtr_LongFn thunk =
            _ptrcall2_Long_IntPtr_Long ??= NetwApi.Thunk<Ptrcall2_Long_IntPtr_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_Long_Byte_Long_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in byte a1,
        in long a2,
        ref IntPtr answered);

    private static Ptrcall3_Long_Byte_Long_IntPtrFn _ptrcall3_Long_Byte_Long_IntPtr;

    internal static void Ptrcall3_Long_Byte_Long_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in byte a1,
        in long a2,
        ref IntPtr answered)
    {
        Ptrcall3_Long_Byte_Long_IntPtrFn thunk =
            _ptrcall3_Long_Byte_Long_IntPtr ??= NetwApi.Thunk<Ptrcall3_Long_Byte_Long_IntPtrFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Long_Int_LongFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in int a1,
        ref long answered);

    private static Ptrcall2_Long_Int_LongFn _ptrcall2_Long_Int_Long;

    internal static void Ptrcall2_Long_Int_Long(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in int a1,
        ref long answered)
    {
        Ptrcall2_Long_Int_LongFn thunk =
            _ptrcall2_Long_Int_Long ??= NetwApi.Thunk<Ptrcall2_Long_Int_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall2_Long_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in long a1,
        ref long answered);

    private static Ptrcall2_Long_Long_LongFn _ptrcall2_Long_Long_Long;

    internal static void Ptrcall2_Long_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in long a1,
        ref long answered)
    {
        Ptrcall2_Long_Long_LongFn thunk =
            _ptrcall2_Long_Long_Long ??= NetwApi.Thunk<Ptrcall2_Long_Long_LongFn>(
                "ptrcall2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_Long_Long_Long_IntPtrFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in long a1,
        in long a2,
        ref IntPtr answered);

    private static Ptrcall3_Long_Long_Long_IntPtrFn _ptrcall3_Long_Long_Long_IntPtr;

    internal static void Ptrcall3_Long_Long_Long_IntPtr(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in long a1,
        in long a2,
        ref IntPtr answered)
    {
        Ptrcall3_Long_Long_Long_IntPtrFn thunk =
            _ptrcall3_Long_Long_Long_IntPtr ??= NetwApi.Thunk<Ptrcall3_Long_Long_Long_IntPtrFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Ptrcall3_Long_Long_Long_LongFn(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in long a1,
        in long a2,
        ref long answered);

    private static Ptrcall3_Long_Long_Long_LongFn _ptrcall3_Long_Long_Long_Long;

    internal static void Ptrcall3_Long_Long_Long_Long(
        IntPtr bind,
        IntPtr instance,
        in long a0,
        in long a1,
        in long a2,
        ref long answered)
    {
        Ptrcall3_Long_Long_Long_LongFn thunk =
            _ptrcall3_Long_Long_Long_Long ??= NetwApi.Thunk<Ptrcall3_Long_Long_Long_LongFn>(
                "ptrcall3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Call0Fn(
        IntPtr bind,
        IntPtr instance,
        ref godot_variant answered);

    private static Call0Fn _call0;

    internal static void Call0(
        IntPtr bind,
        IntPtr instance,
        ref godot_variant answered)
    {
        Call0Fn thunk = _call0 ??= NetwApi.Thunk<Call0Fn>("call0");
        thunk(bind, instance, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Call1Fn(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        ref godot_variant answered);

    private static Call1Fn _call1;

    internal static void Call1(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        ref godot_variant answered)
    {
        Call1Fn thunk = _call1 ??= NetwApi.Thunk<Call1Fn>("call1");
        thunk(bind, instance, in a0, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Call2Fn(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        in godot_variant a1,
        ref godot_variant answered);

    private static Call2Fn _call2;

    internal static void Call2(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        in godot_variant a1,
        ref godot_variant answered)
    {
        Call2Fn thunk = _call2 ??= NetwApi.Thunk<Call2Fn>("call2");
        thunk(bind, instance, in a0, in a1, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Call3Fn(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        in godot_variant a1,
        in godot_variant a2,
        ref godot_variant answered);

    private static Call3Fn _call3;

    internal static void Call3(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        in godot_variant a1,
        in godot_variant a2,
        ref godot_variant answered)
    {
        Call3Fn thunk = _call3 ??= NetwApi.Thunk<Call3Fn>("call3");
        thunk(bind, instance, in a0, in a1, in a2, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void Call4Fn(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        in godot_variant a1,
        in godot_variant a2,
        in godot_variant a3,
        ref godot_variant answered);

    private static Call4Fn _call4;

    internal static void Call4(
        IntPtr bind,
        IntPtr instance,
        in godot_variant a0,
        in godot_variant a1,
        in godot_variant a2,
        in godot_variant a3,
        ref godot_variant answered)
    {
        Call4Fn thunk = _call4 ??= NetwApi.Thunk<Call4Fn>("call4");
        thunk(bind, instance, in a0, in a1, in a2, in a3, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr ArgsNewFn(long count);

    private static ArgsNewFn _argsNew;

    internal static IntPtr ArgsNew(long count)
    {
        ArgsNewFn thunk = _argsNew ??= NetwApi.Thunk<ArgsNewFn>("args_new");
        return thunk(count);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void ArgsSetFn(
        IntPtr pack,
        long index,
        in godot_variant value);

    private static ArgsSetFn _argsSet;

    internal static void ArgsSet(
        IntPtr pack,
        long index,
        in godot_variant value)
    {
        ArgsSetFn thunk = _argsSet ??= NetwApi.Thunk<ArgsSetFn>("args_set");
        thunk(pack, index, in value);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void CallPackFn(
        IntPtr bind,
        IntPtr instance,
        IntPtr pack,
        long count,
        ref godot_variant answered);

    private static CallPackFn _callPack;

    internal static void CallPack(
        IntPtr bind,
        IntPtr instance,
        IntPtr pack,
        long count,
        ref godot_variant answered)
    {
        CallPackFn thunk = _callPack ??= NetwApi.Thunk<CallPackFn>("call_pack");
        thunk(bind, instance, pack, count, ref answered);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void ArgsFreeFn(IntPtr pack);

    private static ArgsFreeFn _argsFree;

    internal static void ArgsFree(IntPtr pack)
    {
        ArgsFreeFn thunk = _argsFree ??= NetwApi.Thunk<ArgsFreeFn>("args_free");
        thunk(pack);
    }
}
