// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// The scene an entity belongs to, reached as <see cref="NetwEntity.Scene"/>.
/// </summary>
/// <remarks>
/// Tells who is in a multiplayer scene and which players it replicates to.
/// Reach it with <see cref="Netw.Scene"/> or <see cref="NetwEntity.Scene"/>. An
/// entity declared with <see cref="Netw.ConfigureMultiplayerScene"/> resolves
/// to itself, any other entity to its closest scene ancestor. Each scene has
/// one handle, so <c>==</c> compares scenes. A scene replicates to a player
/// while a body of theirs is in it, or while the player watches it with
/// <see cref="NetwSceneHandle.Watch"/>. <see cref="NetwSceneHandle.Unwatch"/>
/// does not remove a player whose body is still in the scene.
/// <code>
/// lobby.watch(player)
/// arena.add_child(Netw.spawn_player(player, make_player))
/// lobby.unwatch(player)
/// </code>
/// <para>
/// Inside a scene, <see cref="NetwInterestLayer"/> still filters which entities
/// a player receives. A body is moved with <see cref="Node.Reparent"/> as you
/// would normally do. Use <see cref="Netw.Reparent"/> when you need to await
/// the server taking the move.
/// </para>
/// </remarks>
public sealed class NetwSceneHandle : NetwRefCounted
{
    public NetwSceneHandle(IntPtr native) : base(native)
    {
    }

    public static NetwSceneHandle Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new NetwSceneHandle(native);
    }

    public static NetwSceneHandle From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    /// <summary>
    /// Emitted when <c>body</c> enters this scene.
    /// </summary>
    public event Action<Variant> BodyEntered
    {
        add => Connect("body_entered", Callable.From(value));
        remove => Disconnect("body_entered", Callable.From(value));
    }

    /// <summary>
    /// Emitted when <c>body</c> leaves this scene.
    /// </summary>
    public event Action<Variant> BodyLeft
    {
        add => Connect("body_left", Callable.From(value));
        remove => Disconnect("body_left", Callable.From(value));
    }

    /// <summary>
    /// Emitted when this scene starts replicating to <c>player</c>.
    /// <see cref="NetwSceneHandle.Viewers"/> already includes them. To spawn
    /// players, use <see cref="NetwSessionHandle.SceneChanged"/> instead.
    /// </summary>
    public event Action<Variant> ViewerEntered
    {
        add => Connect("viewer_entered", Callable.From(value));
        remove => Disconnect("viewer_entered", Callable.From(value));
    }

    /// <summary>
    /// Emitted when this scene stops replicating to <c>player</c>.
    /// </summary>
    public event Action<Variant> ViewerLeft
    {
        add => Connect("viewer_left", Callable.From(value));
        remove => Disconnect("viewer_left", Callable.From(value));
    }

    private static readonly IntPtr _bindGetEntity =
        NetwApi.MethodBind("NetwSceneHandle", "get_entity", 2944877500UL);

    /// <summary>
    /// The <see cref="Rid"/> of the scene's entity, invalid outside a session.
    /// The <c>scene_*</c> methods of <see cref="NetwMultiplayer"/> take it.
    /// </summary>
    public Rid Entity
    {
        get
        {
            Rid answered = default;
            NetwThunks.Ptrcall0_Rid(_bindGetEntity, Checked, ref answered);
            return answered;
        }
    }

    private static readonly IntPtr _bindGetIsDeclared =
        NetwApi.MethodBind("NetwSceneHandle", "get_is_declared", 36873697UL);

    /// <summary>
    /// Whether a scene was found. <c>false</c> for an entity outside every
    /// scene or not in the tree, and every other member is empty.
    /// </summary>
    public bool IsDeclared
    {
        get
        {
            byte answered = default;
            NetwThunks.Ptrcall0_Byte(_bindGetIsDeclared, Checked, ref answered);
            return answered != 0;
        }
    }

    private static readonly IntPtr _bindGetRoot =
        NetwApi.MethodBind("NetwSceneHandle", "get_root", 3160264692UL);

    /// <summary>
    /// The node the scene was declared on, <c>null</c> outside a session. When
    /// the scene is <see cref="NetwSceneConfig.Isolated"/>,
    /// <see cref="Netw.Spawn"/> returns <see cref="NetwSceneHandle.World"/> and
    /// this is the node inside it.
    /// </summary>
    public Node Root
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetRoot, Checked, ref answered);
            Node result = (Node)VariantUtils.ConvertToGodotObject(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetWorld =
        NetwApi.MethodBind("NetwSceneHandle", "get_world", 3160264692UL);

    /// <summary>
    /// The <see cref="SubViewport"/> above <see cref="NetwSceneHandle.Root"/>
    /// that gives an <see cref="NetwSceneConfig.Isolated"/> scene its own
    /// <see cref="World2D"/> and <see cref="World3D"/>, <c>null</c> otherwise.
    /// </summary>
    public Node World
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetWorld, Checked, ref answered);
            Node result = (Node)VariantUtils.ConvertToGodotObject(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetLabel =
        NetwApi.MethodBind("NetwSceneHandle", "get_label", 2002593661UL);

    /// <summary>
    /// The name <see cref="Netw.Scene"/> finds this scene by. See
    /// <see cref="NetwSceneConfig.Labeled"/>.
    /// </summary>
    public StringName Label
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetLabel, Checked, ref answered);
            StringName result = VariantUtils.ConvertToStringName(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetBodies =
        NetwApi.MethodBind("NetwSceneHandle", "get_bodies", 3995934104UL);

    /// <summary>
    /// Every body in this scene, in no particular order. A body is removed as
    /// soon as it is despawned, before its node is freed.
    /// </summary>
    public Godot.Collections.Array Bodies
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetBodies, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetViewers =
        NetwApi.MethodBind("NetwSceneHandle", "get_viewers", 3995934104UL);

    /// <summary>
    /// Every player this scene replicates to, see
    /// <see cref="NetwSceneHandle.IsWatching"/>.
    /// </summary>
    public Godot.Collections.Array Viewers
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetViewers, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetLocalBodies =
        NetwApi.MethodBind("NetwSceneHandle", "get_local_bodies", 3995934104UL);

    /// <summary>
    /// Every body in this scene that belongs to this peer.
    /// </summary>
    public Godot.Collections.Array LocalBodies
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetLocalBodies, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindGetEntities =
        NetwApi.MethodBind("NetwSceneHandle", "get_entities", 3995934104UL);

    /// <summary>
    /// Every entity in this scene.
    /// </summary>
    public Godot.Collections.Array Entities
    {
        get
        {
            godot_variant answered = default;
            NetwThunks.Call0(_bindGetEntities, Checked, ref answered);
            Godot.Collections.Array result =
                VariantUtils.ConvertToArray(answered);
            answered.Dispose();
            return result;
        }
    }

    private static readonly IntPtr _bindObserve =
        NetwApi.MethodBind("NetwSceneHandle", "observe", 957362965UL);

    /// <summary>
    /// Calls <paramref name="callback"/> whenever this scene gains or loses a
    /// subject of <paramref name="event"/>. Registering the same
    /// <paramref name="callback"/> twice does nothing.
    /// <code>
    /// arena.observe(NetwMultiplayer.SCENE_EVENT_BODY, on_car_edge)
    ///
    /// func on_car_edge(present: bool, car: NetwEntity) -&gt; bool:
    ///         reshuffle(car)
    ///         return false        # true drops the subscription
    /// </code>
    /// <para>
    /// <see cref="NetwMultiplayer.SceneEvent.Viewer"/> passes a
    /// <see cref="NetwPlayer"/>. <see cref="NetwMultiplayer.SceneEvent.Body"/>
    /// and <see cref="NetwMultiplayer.SceneEvent.Entity"/> pass a
    /// <see cref="NetwEntity"/>.
    /// </para>
    /// </summary>
    public void Observe(long @event, Callable callback)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)@event);
        godot_variant slot1 = VariantUtils.CreateFromCallable(callback);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindObserve,
            Checked,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        answered.Dispose();
    }

    private static readonly IntPtr _bindUnobserve =
        NetwApi.MethodBind("NetwSceneHandle", "unobserve", 957362965UL);

    /// <summary>
    /// Removes a <paramref name="callback"/> registered with
    /// <see cref="NetwSceneHandle.Observe"/>. It must be the same
    /// <see cref="Callable"/> that was passed to
    /// <see cref="NetwSceneHandle.Observe"/>.
    /// </summary>
    public void Unobserve(long @event, Callable callback)
    {
        godot_variant slot0 = VariantUtils.CreateFromInt((long)@event);
        godot_variant slot1 = VariantUtils.CreateFromCallable(callback);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindUnobserve,
            Checked,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        answered.Dispose();
    }

    private static readonly IntPtr _bindWatch =
        NetwApi.MethodBind("NetwSceneHandle", "watch", 1229657424UL);

    /// <summary>
    /// Replicates this scene to <paramref name="player"/> without giving them a
    /// body in it, such as for a lobby or a spectator. A player can watch
    /// several scenes at once.
    /// <code>
    /// Netw.scene(lobby).watch(who)
    /// </code>
    /// <para>
    /// Watching a nested scene also sends the scene roots above it, but not
    /// their content.
    /// <code>
    /// Error
    /// ┠╴OK                      the watch stands
    /// ┠╴ERR_UNAUTHORIZED        this peer is not the server
    /// ┠╴ERR_INVALID_PARAMETER   a null player, or one this session no longer holds
    /// ┖╴ERR_DOES_NOT_EXIST      this scene names no live node
    /// </code>
    /// </para>
    /// <para>
    /// <b>Server Only.</b>
    /// </para>
    /// </summary>
    public Error Watch(NetwPlayer player)
    {
        IntPtr slot0 = player?.Native ?? IntPtr.Zero;
        long answered = default;
        NetwThunks.Ptrcall1_IntPtr_Long(
            _bindWatch,
            Checked,
            in slot0,
            ref answered);
        return (Error)answered;
    }

    private static readonly IntPtr _bindUnwatch =
        NetwApi.MethodBind("NetwSceneHandle", "unwatch", 1229657424UL);

    /// <summary>
    /// Undoes <see cref="NetwSceneHandle.Watch"/>. The scene keeps replicating
    /// to <paramref name="player"/> while a body of theirs is in it.
    /// <code>
    /// Error
    /// ┠╴OK                      the watch is withdrawn
    /// ┠╴ERR_INVALID_PARAMETER   a null player, or one this session no longer holds
    /// ┖╴ERR_DOES_NOT_EXIST      this player was not watching
    /// </code>
    /// <para>
    /// <b>Server Only.</b>
    /// </para>
    /// </summary>
    public Error Unwatch(NetwPlayer player)
    {
        IntPtr slot0 = player?.Native ?? IntPtr.Zero;
        long answered = default;
        NetwThunks.Ptrcall1_IntPtr_Long(
            _bindUnwatch,
            Checked,
            in slot0,
            ref answered);
        return (Error)answered;
    }

    private static readonly IntPtr _bindIsWatching =
        NetwApi.MethodBind("NetwSceneHandle", "is_watching", 2698762196UL);

    /// <summary>
    /// Whether this scene replicates to <paramref name="player"/>, either
    /// because a body of theirs is in it or because of
    /// <see cref="NetwSceneHandle.Watch"/>.
    /// </summary>
    public bool IsWatching(NetwPlayer player)
    {
        IntPtr slot0 = player?.Native ?? IntPtr.Zero;
        byte answered = default;
        NetwThunks.Ptrcall1_IntPtr_Byte(
            _bindIsWatching,
            Checked,
            in slot0,
            ref answered);
        return answered != 0;
    }
}
