// <auto-generated/>
using System;
using Godot;
using Godot.NativeInterop;

namespace Networked;

/// <summary>
/// Static entry points for the Networked API.
/// </summary>
/// <remarks>
/// The interface provided by this class is optional and is supposed to work
/// with the default <see cref="SceneMultiplayer"/>.
/// </remarks>
public sealed class Netw : NetwRefCounted
{
    public Netw(IntPtr native) : base(native)
    {
    }

    public static Netw Adopt(IntPtr native)
    {
        return native == IntPtr.Zero ? null : new Netw(native);
    }

    public static Netw From(Variant value)
    {
        return Adopt(NetwApi.Retained(NetwApi.ObjectOf(value)));
    }

    public enum SceneChange : long
    {
        /// <summary>
        /// Every player moves to the new scene.
        /// </summary>
        Session = 0,
        /// <summary>
        /// Only the requesting player moves.
        /// </summary>
        Player = 1,
        /// <summary>
        /// Every player in the requester's scene moves.
        /// </summary>
        Scene = 2,
    }

    public enum SceneIsolation : long
    {
        /// <summary>
        /// The multiplayer scene shares the physics and render world of
        /// whatever it is parented into.
        /// </summary>
        None = 0,
        /// <summary>
        /// The multiplayer scene has its own world in a
        /// <see cref="SubViewport"/>, so it never collides with another scene.
        /// </summary>
        OwnWorld = 1,
    }

    private static readonly IntPtr _bindOf =
        NetwApi.MethodBind("Netw", "of", 850293890UL);

    /// <summary>
    /// Returns the <see cref="Node.Multiplayer"/> of <paramref name="node"/> as
    /// a <see cref="NetwMultiplayer"/>.
    /// <code>
    /// var api := Netw.of(self)
    /// api.entity_despawn(route)
    /// </code>
    /// <para>
    /// A node that is in no tree returns <c>null</c>.
    /// </para>
    /// </summary>
    public static NetwMultiplayer Of(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindOf,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwMultiplayer.Adopt(answered);
    }

    private static readonly IntPtr _bindConnection =
        NetwApi.MethodBind("Netw", "connection", 1219668382UL);

    /// <summary>
    /// The <see cref="NetwConnectHandle"/> of the
    /// <see cref="Node.Multiplayer"/>, used to connect to other peers and probe
    /// servers.
    /// <code>
    /// var c := Netw.connection(self)
    /// var ticket := c.create_peer(
    ///         ENetMultiplayerPeer,
    ///         NetwMultiplayer.TRANSPORT_MODE_HOST,
    ///         "", {port = 21253}, _created)
    ///
    /// func _created(peer: MultiplayerPeer, error: Error, detail: String):
    ///     if error == OK:
    ///         Netw.of(self).multiplayer_peer = peer
    /// </code>
    /// <para>
    /// This is optional. Assigning a <see cref="MultiplayerPeer"/> to
    /// <see cref="MultiplayerApi.MultiplayerPeer"/> works as usual.
    /// </para>
    /// </summary>
    public static NetwConnectHandle Connection(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindConnection,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwConnectHandle.Adopt(answered);
    }

    private static readonly IntPtr _bindSession =
        NetwApi.MethodBind("Netw", "session", 1978167305UL);

    /// <summary>
    /// The <see cref="NetwSessionHandle"/> of the
    /// <see cref="Node.Multiplayer"/>. Mostly useful for connecting signals.
    /// <code>
    /// var s := Netw.session(self)
    /// s.entered.connect(_on_entered)
    /// s.disconnected.connect(_on_over)
    /// s.ended.connect(_on_over)
    /// </code>
    /// </summary>
    public static NetwSessionHandle Session(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindSession,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwSessionHandle.Adopt(answered);
    }

    private static readonly IntPtr _bindClock =
        NetwApi.MethodBind("Netw", "clock", 358350475UL);

    /// <summary>
    /// Returns the clock for the <see cref="Node.Multiplayer"/> of
    /// <paramref name="node"/>.
    /// <code>
    /// @onready var clock := Netw.clock(self)
    ///
    /// func _ready() -&gt; void:
    ///     clock.before_tick.connect(_sample_input)
    ///     clock.on_tick.connect(_simulate)
    /// </code>
    /// <para>
    /// <see cref="Netw.ConfigureClock"/> is where the clock is set up before
    /// <see cref="MultiplayerApi.MultiplayerPeer"/> connects.
    /// </para>
    /// </summary>
    public static NetwClockHandle Clock(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindClock,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwClockHandle.Adopt(answered);
    }

    private static readonly IntPtr _bindService =
        NetwApi.MethodBind("Netw", "service", 158477627UL);

    /// <summary>
    /// Returns the service registered as <paramref name="type"/>, or
    /// <c>null</c>. A service is like an autoload, but one per
    /// <see cref="MultiplayerApi"/>.
    /// <code>
    /// var gamestate := Netw.service(self, MyGamestate) as MyGamestate
    /// </code>
    /// </summary>
    public static Variant Service(Node node, GodotObject type)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromGodotObject(type);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindService,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        Variant result = Variant.CreateCopyingBorrowed(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindServiceRegister =
        NetwApi.MethodBind("Netw", "service_register", 3274971611UL);

    /// <summary>
    /// Registers <paramref name="service"/> so <see cref="Netw.Service"/>
    /// returns it.
    /// <code>
    /// Netw.service_register(self, MyGamestate.new())
    /// </code>
    /// <para>
    /// <paramref name="type"/> defaults to the class of
    /// <paramref name="service"/>. Registering another service with the same
    /// <paramref name="type"/> replaces it.
    /// </para>
    /// </summary>
    public static void ServiceRegister(
        Node node,
        GodotObject service,
        GodotObject type = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = service?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot2 = type?.NativeInstance ?? IntPtr.Zero;
        long discarded = default;
        NetwThunks.Ptrcall3_IntPtr_IntPtr_IntPtr_Long(
            _bindServiceRegister,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref discarded);
    }

    private static readonly IntPtr _bindServiceUnregister =
        NetwApi.MethodBind("Netw", "service_unregister", 3274971611UL);

    /// <summary>
    /// Reverses <see cref="Netw.ServiceRegister"/>.
    /// </summary>
    public static void ServiceUnregister(
        Node node,
        GodotObject service,
        GodotObject type = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = service?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot2 = type?.NativeInstance ?? IntPtr.Zero;
        long discarded = default;
        NetwThunks.Ptrcall3_IntPtr_IntPtr_IntPtr_Long(
            _bindServiceUnregister,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref discarded);
    }

    private static readonly IntPtr _bindPrepareJoin =
        NetwApi.MethodBind("Netw", "prepare_join", 966125735UL);

    /// <summary>
    /// Joins the game as <paramref name="userName"/>. The arguments after
    /// <paramref name="userName"/> are passed to the
    /// <see cref="Netw.ConfigureJoin"/> handler.
    /// <code>
    /// Netw.prepare_join(self, &amp;"Dev", &amp;"red")
    /// multiplayer.multiplayer_peer = peer
    /// </code>
    /// <para>
    /// Call it before or after assigning
    /// <see cref="MultiplayerApi.MultiplayerPeer"/>. The join can still be
    /// refused later, which emits <see cref="NetwConnectHandle.JoinFailed"/>.
    /// <code>
    /// Error
    /// ┠╴OK                     the join will be sent
    /// ┠╴ERR_UNAVAILABLE        the join could not be sent
    /// ┠╴ERR_ALREADY_IN_USE     a join was already requested
    /// ┖╴ERR_INVALID_PARAMETER  username is empty
    /// </code>
    /// </para>
    /// <para>
    /// <b>Player request.</b>
    /// </para>
    /// </summary>
    public static NetwPromise PrepareJoin(
        Node node,
        StringName userName,
        params Variant[] rest)
    {
        int total = 2 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        godot_variant slot1 = VariantUtils.CreateFromStringName(userName);
        NetwThunks.ArgsSet(pack, 1, in slot1);
        slot1.Dispose();
        for (int index = 2; index < total; index++)
        {
            godot_variant carried = rest[index - 2].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindPrepareJoin,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        NetwPromise result =
            NetwPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindScene =
        NetwApi.MethodBind("Netw", "scene", 2326313168UL);

    /// <summary>
    /// Returns the multiplayer scene <paramref name="node"/> is in, or the one
    /// called <paramref name="named"/>.
    /// <code>
    /// var here := Netw.scene(self)              # the scene I am in
    /// var arena := Netw.scene(spawned)         # the one I just spawned
    /// var track := Netw.scene(self, &amp;"Track")  # the only live Track
    /// </code>
    /// </summary>
    public static NetwSceneHandle Scene(Node node, StringName named = null)
    {
        named ??= new StringName("");
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromStringName(named);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindScene,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        NetwSceneHandle result =
            NetwSceneHandle.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureServerInfo =
        NetwApi.MethodBind("Netw", "configure_server_info", 2275419960UL);

    /// <summary>
    /// Declares what this server says about itself when another peer probes it
    /// with <see cref="NetwConnectHandle.EndpointProbe"/>.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_server_info(server_info)
    ///
    /// func server_info(info: NetwServerInfo) -&gt; NetwServerInfo:
    ///     info.motd = "Friday night session"
    ///     info.max_players = 8
    ///     return info
    /// </code>
    /// </summary>
    public static Error ConfigureServerInfo(Callable provider)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(provider);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureServerInfo,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        Error result = (Error)VariantUtils.ConvertToInt64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureJoin =
        NetwApi.MethodBind("Netw", "configure_join", 591905551UL);

    /// <summary>
    /// Declares what the server does with each peer that joins.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_join(spawn_at)
    ///
    /// func spawn_at(who: NetwPlayer, point: StringName, team: int) -&gt; void:
    ///     arena.add_child(Netw.spawn_player(who, _spawn_avatar, team))
    /// </code>
    /// <para>
    /// <paramref name="handler"/> receives the <see cref="NetwPlayer"/>, then
    /// the arguments the client passed to <see cref="Netw.PrepareJoin"/> after
    /// its username. The username is <see cref="NetwPlayer.UserName"/>.
    /// <b>Server Only.</b>
    /// </para>
    /// </summary>
    public static NetwJoinConfig ConfigureJoin(Callable handler)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(handler);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureJoin,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        NetwJoinConfig result =
            NetwJoinConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureAdmission =
        NetwApi.MethodBind("Netw", "configure_admission", 2275419960UL);

    /// <summary>
    /// Decides whether a joining peer gets a <see cref="NetwPlayer"/>.
    /// <paramref name="handler"/> receives the peer id and the arguments of
    /// <see cref="Netw.PrepareJoin"/>. Return <c>@GlobalScope.OK</c> to accept.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_admission(admit)
    ///
    /// # the client called Netw.prepare_join(self, username)
    /// func admit(peer_id: int, username: StringName) -&gt; Error:
    ///     if nakama.username_for_peer(peer_id) != username:
    ///         return ERR_UNAUTHORIZED
    ///     return OK
    /// </code>
    /// <para>
    /// To stop a peer from connecting at all, before
    /// <c>MultiplayerAPI.peer_connected</c>, use
    /// <see cref="NetwMultiplayer.AuthCallback"/> as you would with
    /// <see cref="SceneMultiplayer"/>. <b>Server Only.</b>
    /// </para>
    /// </summary>
    public static Error ConfigureAdmission(Callable handler)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(handler);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureAdmission,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        Error result = (Error)VariantUtils.ConvertToInt64(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureSession =
        NetwApi.MethodBind("Netw", "configure_session", 3986669177UL);

    /// <summary>
    /// Configures the <see cref="Node.Multiplayer"/> session with settings
    /// <see cref="SceneMultiplayer"/> does not have.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_session(self) \
    ///             .app(&amp;"bomber-v2") \
    ///             .role(NetwMultiplayer.ROLE_LISTEN_SERVER)
    /// </code>
    /// <para>
    /// See <see cref="NetwSessionConfig"/> for the settings.
    /// </para>
    /// </summary>
    public static NetwSessionConfig ConfigureSession(
        Node node,
        NetwSessionConfig preset = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = preset?.Native ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_IntPtr_IntPtr(
            _bindConfigureSession,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwSessionConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureClock =
        NetwApi.MethodBind("Netw", "configure_clock", 4279755522UL);

    /// <summary>
    /// Sets up the clock for the <see cref="Node.Multiplayer"/> and returns the
    /// <see cref="NetwClockConfig"/> to fill in.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_clock(self) \
    ///             .ticks_per_second(60) \
    ///             .display_offset_ticks(2)
    /// </code>
    /// <para>
    /// Pass an [annotation @GDScript.@export] <see cref="NetwClockConfig"/> as
    /// <paramref name="preset"/> to set it from the inspector, and call this
    /// from <c>Node._enter_tree</c>.
    /// </para>
    /// </summary>
    public static NetwClockConfig ConfigureClock(
        Node node,
        NetwClockConfig preset = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = preset?.Native ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_IntPtr_IntPtr(
            _bindConfigureClock,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwClockConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureLagcomp =
        NetwApi.MethodBind("Netw", "configure_lagcomp", 3224442444UL);

    /// <summary>
    /// Tunes how far back the <see cref="NetwMultiplayer"/> records what every
    /// node held.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_lagcomp(self).input_gate_deadline(16)
    /// </code>
    /// <para>
    /// <paramref name="preset"/> works as in <see cref="Netw.ConfigureClock"/>.
    /// </para>
    /// </summary>
    public static NetwLagCompensationConfig ConfigureLagcomp(
        Node node,
        NetwLagCompensationConfig preset = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = preset?.Native ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_IntPtr_IntPtr(
            _bindConfigureLagcomp,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwLagCompensationConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureProperty =
        NetwApi.MethodBind("Netw", "configure_property", 1544261587UL);

    /// <summary>
    /// Declares how <paramref name="property"/> is synchronized.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_property(self, &amp;"fuel")
    ///
    /// func refuel() -&gt; void:
    ///     fuel = 100.0
    ///     Netw.sync_property(self, &amp;"fuel")
    /// </code>
    /// <para>
    /// See <see cref="NetwPropertyConfig"/> for the options.
    /// </para>
    /// </summary>
    public static NetwPropertyConfig ConfigureProperty(
        Node node,
        StringName property,
        bool warnLate = true)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromStringName(property);
        godot_variant slot2 = VariantUtils.CreateFromBool(warnLate);
        godot_variant answered = default;
        NetwThunks.Call3(
            _bindConfigureProperty,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        slot2.Dispose();
        NetwPropertyConfig result =
            NetwPropertyConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureRpc =
        NetwApi.MethodBind("Netw", "configure_rpc", 2692389314UL);

    /// <summary>
    /// Declares extra configuration for <paramref name="callable"/> that
    /// [annotation @GDScript.@rpc] does not cover.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_rpc(self.aim).controller().quantize(
    ///             NetwQuantizeAngle.new().bits(12).centered(),
    ///     )
    ///
    /// @rpc("any_peer", "unreliable")
    /// func aim(yaw: float) -&gt; void:
    ///     turret.rotation.y = yaw
    /// </code>
    /// </summary>
    public static NetwMemberConfig ConfigureRpc(Callable callable)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureRpc,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        NetwMemberConfig result =
            NetwMemberConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureSignal =
        NetwApi.MethodBind("Netw", "configure_signal", 4061727032UL);

    /// <summary>
    /// Registers <paramref name="sig"/> so <see cref="Netw.EmitEntitySignal"/>
    /// may emit it on every peer.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_signal(self.exploded)   # only the server may emit it
    /// </code>
    /// <para>
    /// Emitting it also fires the local listeners, as with
    /// <see cref="NetwMemberConfig.CallLocal"/>.
    /// </para>
    /// </summary>
    public static NetwMemberConfig ConfigureSignal(Signal sig)
    {
        godot_variant slot0 = VariantUtils.CreateFromSignal(sig);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureSignal,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        NetwMemberConfig result =
            NetwMemberConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureSpawn =
        NetwApi.MethodBind("Netw", "configure_spawn", 2692389314UL);

    /// <summary>
    /// Registers <paramref name="callable"/> as a function
    /// <see cref="Netw.Spawn"/> may run on every peer to build the same node.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_spawn(_spawn_bullet)
    ///
    /// func _spawn_bullet(dir: Vector2, tier: int) -&gt; Node:
    ///     var bullet := BulletScene.instantiate()
    ///     bullet.setup(dir, tier)
    ///     return bullet
    ///
    /// # ...
    ///
    /// var bullet := Netw.spawn(_spawn_bullet, dir, tier) # server only
    /// muzzle.add_child(bullet)
    ///
    /// # clients build the same node with the same arguments, in the same place
    /// </code>
    /// </summary>
    public static NetwMemberConfig ConfigureSpawn(Callable callable)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureSpawn,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        NetwMemberConfig result =
            NetwMemberConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureEntity =
        NetwApi.MethodBind("Netw", "configure_entity", 1743742259UL);

    /// <summary>
    /// Returns the <see cref="NetwEntity"/> that represents
    /// <paramref name="node"/> in the <see cref="Node.Multiplayer"/> session.
    /// <code>
    /// func _init() -&gt; void:
    ///     var entity := Netw.configure_entity(self)
    ///     # the node now behaves like `Node.set_multiplayer_authority(peer_id)`
    ///     entity.initial_controller = NetwEntity.INITIAL_REPRESENTED_PEER
    /// </code>
    /// </summary>
    public static NetwEntity ConfigureEntity(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindConfigureEntity,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwEntity.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureDespawn =
        NetwApi.MethodBind("Netw", "configure_despawn", 1867730116UL);

    /// <summary>
    /// Declares what the other peers do with <paramref name="node"/> when
    /// <see cref="Netw.Despawn"/> removes it.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_despawn(self).linger(0.5)
    /// </code>
    /// </summary>
    public static NetwDespawnConfig ConfigureDespawn(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindConfigureDespawn,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwDespawnConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigurePersistence =
        NetwApi.MethodBind("Netw", "configure_persistence", 2962870821UL);

    /// <summary>
    /// Declares which row of which <see cref="NetwDatabase"/>
    /// <paramref name="node"/> loads and saves from.
    /// <code>
    /// func _ready() -&gt; void:
    ///     Netw.configure_property(self, &amp;"gold") \
    ///             .persisted(game.save_schema.column_ref(0))
    ///     Netw.configure_persistence(self) \
    ///             .database(&amp;"saves") \
    ///             .schema(game.save_schema) \
    ///             .record_id(account_name)
    /// </code>
    /// <para>
    /// See <see cref="NetwPersistenceConfig"/>,
    /// <see cref="NetwPersistenceHandle"/> and <see cref="NetwDatabase"/>.
    /// </para>
    /// </summary>
    public static NetwPersistenceConfig ConfigurePersistence(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindConfigurePersistence,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwPersistenceConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureInterest =
        NetwApi.MethodBind("Netw", "configure_interest", 3837747350UL);

    /// <summary>
    /// Declares which <see cref="NetwInterestLayer"/> layer
    /// <paramref name="node"/> belongs to, and returns the
    /// <see cref="NetwInterestHandle"/> that is also
    /// <see cref="NetwEntity.Interest"/> of that <paramref name="node"/>.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_interest(self) \
    ///             .join( \
    ///                 &amp;"team:red", \
    ///                 NetwMultiplayer.LEAVE_POLICY_RETAIN, \
    ///                 NetwMultiplayer.PERCEPTION_POLICY_HIDE, \
    ///             ) \
    ///             .join(&amp;"sight") \
    ///             .on_enter(_on_interest_enter)
    /// </code>
    /// </summary>
    public static NetwInterestHandle ConfigureInterest(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindConfigureInterest,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwInterestHandle.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureSchema =
        NetwApi.MethodBind("Netw", "configure_schema", 261365823UL);

    /// <summary>
    /// Declares a schema for a table of records.
    /// <code>
    /// class Mobs:
    ///     static var schema := Netw.configure_schema(&amp;"Mob")
    ///     static var pos    := schema.vector3(&amp;"pos")
    ///     static var hp     := schema.u16(&amp;"hp")
    ///
    /// @onready var mobs := Netw.table(self, &amp;"Mob")
    /// </code>
    /// <para>
    /// Read and write the table with <see cref="Netw.Table"/>.
    /// </para>
    /// </summary>
    public static NetwSchema ConfigureSchema(StringName name)
    {
        godot_variant slot0 = VariantUtils.CreateFromStringName(name);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureSchema,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        NetwSchema result =
            NetwSchema.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRpc =
        NetwApi.MethodBind("Netw", "rpc", 187483682UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on every peer that can see the node.
    /// <code>
    /// Netw.rpc(turret.aim, yaw)
    /// </code>
    /// </summary>
    public static void Rpc(Callable callable, params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(_bindRpc, IntPtr.Zero, pack, total, ref answered);
        NetwThunks.ArgsFree(pack);
        answered.Dispose();
    }

    private static readonly IntPtr _bindRpcId =
        NetwApi.MethodBind("Netw", "rpc_id", 3088989228UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on <paramref name="peerId"/>, or on
    /// every peer when <c>0</c>.
    /// </summary>
    public static void RpcId(
        long peerId,
        Callable callable,
        params Variant[] rest)
    {
        int total = 2 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromInt((long)peerId);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        godot_variant slot1 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 1, in slot1);
        slot1.Dispose();
        for (int index = 2; index < total; index++)
        {
            godot_variant carried = rest[index - 2].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(_bindRpcId, IntPtr.Zero, pack, total, ref answered);
        NetwThunks.ArgsFree(pack);
        answered.Dispose();
    }

    private static readonly IntPtr _bindRpcController =
        NetwApi.MethodBind("Netw", "rpc_controller", 187483682UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on the peer driving the node, its
    /// <see cref="NetwEntity.Controller"/>.
    /// </summary>
    public static void RpcController(Callable callable, params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindRpcController,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        answered.Dispose();
    }

    private static readonly IntPtr _bindRequest =
        NetwApi.MethodBind("Netw", "request", 2325787334UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on the server and returns a
    /// <see cref="NetwPromise"/> with its return value.
    /// <code>
    /// var sold: bool = await Netw.request(shop.buy, &amp;"shield").wait()
    /// </code>
    /// <para>
    /// The method must be an RPC, as for <see cref="Netw.Rpc"/>.
    /// </para>
    /// </summary>
    public static NetwPromise Request(Callable callable, params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindRequest,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        NetwPromise result =
            NetwPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRequestId =
        NetwApi.MethodBind("Netw", "request_id", 1728372685UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on <paramref name="peerId"/> and
    /// returns a <see cref="NetwPromise"/> with its return value. Use
    /// <see cref="Netw.RequestAll"/> to call every peer.
    /// </summary>
    public static NetwPromise RequestId(
        long peerId,
        Callable callable,
        params Variant[] rest)
    {
        int total = 2 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromInt((long)peerId);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        godot_variant slot1 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 1, in slot1);
        slot1.Dispose();
        for (int index = 2; index < total; index++)
        {
            godot_variant carried = rest[index - 2].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindRequestId,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        NetwPromise result =
            NetwPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRequestAll =
        NetwApi.MethodBind("Netw", "request_all", 2458339060UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on every peer that can see the node,
    /// and returns a <see cref="NetwGroupPromise"/> with each return value.
    /// </summary>
    public static NetwGroupPromise RequestAll(
        Callable callable,
        params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindRequestAll,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        NetwGroupPromise result =
            NetwGroupPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindRequestController =
        NetwApi.MethodBind("Netw", "request_controller", 2325787334UL);

    /// <summary>
    /// Calls <paramref name="callable"/> on the peer driving the node, its
    /// <see cref="NetwEntity.Controller"/>.
    /// </summary>
    public static NetwPromise RequestController(
        Callable callable,
        params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromCallable(callable);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindRequestController,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        NetwPromise result =
            NetwPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindSyncProperty =
        NetwApi.MethodBind("Netw", "sync_property", 1494684691UL);

    /// <summary>
    /// Sends the current value of <paramref name="property"/> to the other
    /// peers. Use it for a property that changes rarely.
    /// <code>
    /// func refuel() -&gt; void:
    ///     fuel = 100.0
    ///     Netw.sync_property(self, &amp;"fuel")
    /// </code>
    /// <para>
    /// Call <see cref="Netw.ConfigureProperty"/> first.
    /// </para>
    /// </summary>
    public static void SyncProperty(Node node, StringName property)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromStringName(property);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindSyncProperty,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        answered.Dispose();
    }

    private static readonly IntPtr _bindEmitEntitySignal =
        NetwApi.MethodBind("Netw", "emit_entity_signal", 2789890179UL);

    /// <summary>
    /// Emits <paramref name="sig"/> on every peer, including the local one,
    /// with the arguments that follow.
    /// <code>
    /// signal exploded(position: Vector2)
    ///
    /// func _init() -&gt; void:
    ///     Netw.configure_signal(self.exploded)
    ///
    /// # ...
    ///
    /// Netw.emit_entity_signal(self.exploded, position)
    /// </code>
    /// <para>
    /// Do not also call <c>sig.emit()</c>, or local listeners fire twice.
    /// </para>
    /// </summary>
    public static void EmitEntitySignal(Signal sig, params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromSignal(sig);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindEmitEntitySignal,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        answered.Dispose();
    }

    private static readonly IntPtr _bindChannel =
        NetwApi.MethodBind("Netw", "channel", 3231424134UL);

    /// <summary>
    /// A <see cref="NetwChannel"/> for sending raw bytes in batches.
    /// <paramref name="channelId"/> runs from <c>100</c> to <c>254</c>.
    /// <code>
    /// var voice := Netw.channel(self, 100)
    /// voice.broadcast(frame, false)
    /// </code>
    /// </summary>
    public static NetwChannel Channel(Node node, long channelId)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        long slot1 = channelId;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_Long_IntPtr(
            _bindChannel,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwChannel.Adopt(answered);
    }

    private static readonly IntPtr _bindTable =
        NetwApi.MethodBind("Netw", "table", 482665393UL);

    /// <summary>
    /// Returns the table of the schema <paramref name="name"/> from
    /// <see cref="Netw.ConfigureSchema"/>.
    /// <code>
    /// @onready var mobs := Netw.table(self, &amp;"Mob")
    ///
    /// func _ready() -&gt; void:
    ///     mobs.received.connect(_on_mobs)
    /// </code>
    /// </summary>
    public static NetwTableHandle Table(Node node, StringName name)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromStringName(name);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindTable,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        NetwTableHandle result =
            NetwTableHandle.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindConfigureDatabase =
        NetwApi.MethodBind("Netw", "configure_database", 429892123UL);

    /// <summary>
    /// Declares a <see cref="NetwDatabase"/> named <paramref name="name"/> on
    /// <see cref="Node.Multiplayer"/> of <paramref name="node"/>.
    /// <code>
    /// func _ready() -&gt; void:
    ///     Netw.configure_database(self, &amp;"saves").backend(preload("res://save_backend.tres"))
    /// </code>
    /// <para>
    /// Get it later with <see cref="Netw.Database"/>. Pass an [annotation
    /// @GDScript.@export] <see cref="NetwDatabaseConfig"/> as
    /// <paramref name="preset"/> to set it from the inspector.
    /// <code>
    /// @export var database_config: NetwDatabaseConfig
    ///
    /// func _enter_tree() -&gt; void:
    ///     Netw.configure_database(self, &amp;"saves", database_config)
    /// </code>
    /// </para>
    /// </summary>
    public static NetwDatabaseConfig ConfigureDatabase(
        Node node,
        StringName name,
        NetwDatabaseConfig preset = null)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromStringName(name);
        godot_variant slot2 =
            VariantUtils.CreateFromGodotObjectPtr(
                preset?.Native ?? IntPtr.Zero);
        godot_variant answered = default;
        NetwThunks.Call3(
            _bindConfigureDatabase,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        slot2.Dispose();
        NetwDatabaseConfig result =
            NetwDatabaseConfig.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindDatabase =
        NetwApi.MethodBind("Netw", "database", 927809139UL);

    /// <summary>
    /// Returns the <see cref="NetwDatabase"/> declared as
    /// <paramref name="name"/> with <see cref="Netw.ConfigureDatabase"/>.
    /// <code>
    /// var db: NetwDatabase = Netw.database(self, &amp;"saves")
    /// </code>
    /// </summary>
    public static NetwDatabase Database(Node node, StringName name)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromStringName(name);
        godot_variant answered = default;
        NetwThunks.Call2(
            _bindDatabase,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        NetwDatabase result =
            NetwDatabase.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindReplicate =
        NetwApi.MethodBind("Netw", "replicate", 707187235UL);

    /// <summary>
    /// Spawns <paramref name="node"/> on every peer from its
    /// <see cref="Node.SceneFilePath"/>, and returns its
    /// <see cref="NetwEntity"/>. Call it before adding <paramref name="node"/>
    /// to the tree. Peers receive it when it enters the tree, so set its
    /// starting values in between.
    /// <code>
    /// var body := PlayerScene.instantiate()
    /// var entity := Netw.replicate(body, player)
    /// body.position = spawn_point
    /// scene.add_child(body)
    /// </code>
    /// <para>
    /// A client can call it without <paramref name="owner"/> when
    /// <paramref name="node"/> sets <see cref="NetwEntity.Lifecycle"/> to
    /// <see cref="NetwEntity.LifecycleEnum.Controller"/>. That client becomes
    /// its <see cref="NetwEntity.Controller"/>.
    /// </para>
    /// </summary>
    public static NetwEntity Replicate(Node node, NetwPlayer owner = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = owner?.Native ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_IntPtr_IntPtr(
            _bindReplicate,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwEntity.Adopt(answered);
    }

    private static readonly IntPtr _bindSpawn =
        NetwApi.MethodBind("Netw", "spawn", 3345110683UL);

    /// <summary>
    /// Calls <paramref name="fn"/> with the arguments after it on every peer,
    /// and returns the node it created here. Add it to the tree yourself.
    /// <code>
    /// muzzle.add_child(Netw.spawn(_spawn_bullet, dir, 2))
    /// </code>
    /// <para>
    /// Register <paramref name="fn"/> with <see cref="Netw.ConfigureSpawn"/>
    /// first, and add the node to the tree before the next tick. A client can
    /// call it when the node sets <see cref="NetwEntity.Lifecycle"/> to
    /// <see cref="NetwEntity.LifecycleEnum.Controller"/>. That client becomes
    /// its <see cref="NetwEntity.Controller"/>, sees it at once, and loses it
    /// if the server refuses.
    /// </para>
    /// </summary>
    public static Node Spawn(Callable fn, params Variant[] rest)
    {
        int total = 1 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 = VariantUtils.CreateFromCallable(fn);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        for (int index = 1; index < total; index++)
        {
            godot_variant carried = rest[index - 1].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(_bindSpawn, IntPtr.Zero, pack, total, ref answered);
        NetwThunks.ArgsFree(pack);
        Node result = (Node)VariantUtils.ConvertToGodotObject(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindSpawnPlayer =
        NetwApi.MethodBind("Netw", "spawn_player", 1228628813UL);

    /// <summary>
    /// Like <see cref="Netw.Spawn"/>, for the node <paramref name="player"/>
    /// controls.
    /// <code>
    /// players.add_child(
    ///     Netw.spawn_player(player, _spawn_avatar, character_class)
    /// )
    /// </code>
    /// <para>
    /// The node is despawned when <paramref name="player"/> leaves. With
    /// <see cref="NetwPersistenceConfig.LoadOnSpawn"/>, other peers receive it
    /// once its save is loaded. <b>Server Only.</b>
    /// </para>
    /// </summary>
    public static Node SpawnPlayer(
        NetwPlayer player,
        Callable fn,
        params Variant[] rest)
    {
        int total = 2 + (rest == null ? 0 : rest.Length);
        IntPtr pack = NetwThunks.ArgsNew(total);
        godot_variant slot0 =
            VariantUtils.CreateFromGodotObjectPtr(
                player?.Native ?? IntPtr.Zero);
        NetwThunks.ArgsSet(pack, 0, in slot0);
        slot0.Dispose();
        godot_variant slot1 = VariantUtils.CreateFromCallable(fn);
        NetwThunks.ArgsSet(pack, 1, in slot1);
        slot1.Dispose();
        for (int index = 2; index < total; index++)
        {
            godot_variant carried = rest[index - 2].CopyNativeVariant();
            NetwThunks.ArgsSet(pack, index, in carried);
            carried.Dispose();
        }
        godot_variant answered = default;
        NetwThunks.CallPack(
            _bindSpawnPlayer,
            IntPtr.Zero,
            pack,
            total,
            ref answered);
        NetwThunks.ArgsFree(pack);
        Node result = (Node)VariantUtils.ConvertToGodotObject(answered);
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindDespawn =
        NetwApi.MethodBind("Netw", "despawn", 1486035182UL);

    /// <summary>
    /// Removes the node <see cref="Netw.Spawn"/> or
    /// <see cref="Netw.Replicate"/> made, on every peer.
    /// <code>
    /// Netw.despawn(bullet)
    /// </code>
    /// <para>
    /// See <see cref="NetwDespawnOpts"/> for <paramref name="opts"/>. Returns
    /// <c>@GlobalScope.ERR_DOES_NOT_EXIST</c> for a node that was not spawned,
    /// and <c>@GlobalScope.ERR_UNAVAILABLE</c> outside a session. A client can
    /// call it when it is the <see cref="NetwEntity.Controller"/> and
    /// <see cref="NetwEntity.Lifecycle"/> is
    /// <see cref="NetwEntity.LifecycleEnum.Controller"/>. The node is removed
    /// on that client at once, and comes back if the server refuses.
    /// </para>
    /// </summary>
    public static Error Despawn(Node node, NetwDespawnOpts opts = null)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = opts?.Native ?? IntPtr.Zero;
        long answered = default;
        NetwThunks.Ptrcall2_IntPtr_IntPtr_Long(
            _bindDespawn,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return (Error)answered;
    }

    private static readonly IntPtr _bindReparent =
        NetwApi.MethodBind("Netw", "reparent", 941587451UL);

    /// <summary>
    /// Moves <paramref name="node"/> under <paramref name="newParent"/> like
    /// <see cref="Node.Reparent"/>. The promise resolves once the server has
    /// moved it. Other peers move it after.
    /// <code>
    /// await Netw.reparent(body, level2.get_node(^"Players")).wait()
    /// </code>
    /// <para>
    /// Unlike <see cref="Node.Reparent"/>, it does not fire
    /// <see cref="Area3D"/> and <see cref="Area2D"/> enter and exit signals
    /// during the move, which works around this issue. Otherwise
    /// <see cref="Node.Reparent"/> works fine. The promise fails with
    /// <c>@GlobalScope.ERR_DOES_NOT_EXIST</c> when <paramref name="node"/> has
    /// no entity, and <c>@GlobalScope.ERR_UNAVAILABLE</c> outside a session. A
    /// client can call it when it is the <see cref="NetwEntity.Controller"/>
    /// and <see cref="NetwEntity.Lifecycle"/> is
    /// <see cref="NetwEntity.LifecycleEnum.Controller"/>. The node moves on
    /// that client at once, and moves back if the server refuses.
    /// </para>
    /// </summary>
    public static NetwPromise Reparent(Node node, Node newParent)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = newParent?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_IntPtr_IntPtr(
            _bindReparent,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindClaimAuthority =
        NetwApi.MethodBind("Netw", "claim_authority", 1659447253UL);

    /// <summary>
    /// Asks the server to make this peer the
    /// <see cref="NetwEntity.Controller"/> of the entity
    /// <paramref name="node"/> belongs to. Same as
    /// <see cref="NetwEntity.ClaimAuthority"/>.
    /// <code>
    /// Netw.claim_authority(self, NetwEntity.HOLD_YIELDABLE).then(pick_up)
    /// </code>
    /// <para>
    /// The promise fails with <c>@GlobalScope.ERR_DOES_NOT_EXIST</c> when
    /// <paramref name="node"/> has no entity. <b>Player request.</b>
    /// </para>
    /// </summary>
    public static NetwPromise ClaimAuthority(Node node, NetwEntity.HoldEnum hold =
        (NetwEntity.HoldEnum)2)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        long slot1 = (long)hold;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_Long_IntPtr(
            _bindClaimAuthority,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindReleaseAuthority =
        NetwApi.MethodBind("Netw", "release_authority", 4095760114UL);

    /// <summary>
    /// Gives control of the entity <paramref name="node"/> belongs to to
    /// <paramref name="successor"/>, or to the server when <c>0</c>. Same as
    /// <see cref="NetwEntity.ReleaseAuthority"/>. The promise fails with
    /// <c>@GlobalScope.ERR_DOES_NOT_EXIST</c> when <paramref name="node"/> has
    /// no entity. <b>Player request.</b>
    /// </summary>
    public static NetwPromise ReleaseAuthority(Node node, long successor = 0)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        long slot1 = successor;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_Long_IntPtr(
            _bindReleaseAuthority,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindAction =
        NetwApi.MethodBind("Netw", "action", 1326300923UL);

    /// <summary>
    /// A <see cref="NetwAction"/> for an action such as firing or placing
    /// something, bound to <paramref name="authority"/> the server runs to
    /// judge it. Repeated calls return the same <see cref="NetwAction"/>.
    /// <code>
    /// @onready var place_bomb := Netw.action(_place_bomb)
    ///
    /// func _ready() -&gt; void:
    ///     place_bomb.predict = _show_bomb_now
    ///
    /// func _place_bomb(ctx: NetwActionContext) -&gt; void:
    ///     var bomb := BOMB.instantiate()
    ///     ctx.bind(bomb)
    ///     bombs.add_child(bomb)
    /// </code>
    /// <para>
    /// The server judges an action before other peers see it. To let a client
    /// spawn, move and despawn a node first and have the server confirm it
    /// later, see <see cref="NetwEntity.Lifecycle"/>.
    /// </para>
    /// </summary>
    public static NetwAction Action(Callable authority)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(authority);
        godot_variant answered = default;
        NetwThunks.Call1(_bindAction, IntPtr.Zero, in slot0, ref answered);
        slot0.Dispose();
        NetwAction result =
            NetwAction.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindSample =
        NetwApi.MethodBind("Netw", "sample", 4262892489UL);

    /// <summary>
    /// Returns a copy of the state of <paramref name="entity"/> at
    /// <paramref name="tick"/>. It is empty when nothing was recorded.
    /// <code>
    /// func _place_bomb(ctx: NetwActionContext, pos: Vector2) -&gt; void:
    ///     var past := Netw.sample(entity, ctx.view_tick)
    ///     if not past.has_value(&amp;"position"):
    ///         ctx.deny()
    ///         return
    /// </code>
    /// </summary>
    public static DictionaryRecord Sample(NetwEntity entity, long tick)
    {
        IntPtr slot0 = entity?.Native ?? IntPtr.Zero;
        long slot1 = tick;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_Long_IntPtr(
            _bindSample,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return DictionaryRecord.Adopt(answered);
    }

    private static readonly IntPtr _bindRewind =
        NetwApi.MethodBind("Netw", "rewind", 827478004UL);

    /// <summary>
    /// Moves every entity in <paramref name="entities"/> back to where it was
    /// at <paramref name="tick"/>, calls <paramref name="body"/>, then moves
    /// them back. Use it to check a hit where the shooter saw the target.
    /// <code>
    /// func _fire(ctx: NetwActionContext) -&gt; void:
    ///     Netw.rewind(Netw.scene(self).entities, ctx.view_tick, _trace_shot)
    /// </code>
    /// </summary>
    public static void Rewind(
        Godot.Collections.Array entities,
        long tick,
        Callable body)
    {
        godot_variant slot0 = VariantUtils.CreateFromArray(entities);
        godot_variant slot1 = VariantUtils.CreateFromInt((long)tick);
        godot_variant slot2 = VariantUtils.CreateFromCallable(body);
        godot_variant answered = default;
        NetwThunks.Call3(
            _bindRewind,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        slot2.Dispose();
        answered.Dispose();
    }

    private static readonly IntPtr _bindChangeSceneToFile =
        NetwApi.MethodBind("Netw", "change_scene_to_file", 1402832089UL);

    /// <summary>
    /// Opens <paramref name="path"/> and moves players to it. No node moves
    /// with them, so spawn their nodes from
    /// <see cref="NetwSessionHandle.SceneChanged"/>. <paramref name="scope"/>
    /// says who moves. On a client this is a request that
    /// <see cref="Netw.ConfigureSceneRequests"/> decides, and it is rejected
    /// when there is none.
    /// <code>
    /// var err: Error = await Netw.change_scene_to_file(
    ///         self, "res://match.tscn").wait()
    /// if err != OK:
    ///     status.text = "Could not start the match."
    /// </code>
    /// </summary>
    public static NetwPromise ChangeSceneToFile(Node node, string path, Netw.SceneChange scope =
        (Netw.SceneChange)0)
    {
        godot_variant slot0 = VariantUtils.CreateFromGodotObject(node);
        godot_variant slot1 = VariantUtils.CreateFromString(path);
        godot_variant slot2 = VariantUtils.CreateFromInt((long)scope);
        godot_variant answered = default;
        NetwThunks.Call3(
            _bindChangeSceneToFile,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref answered);
        slot0.Dispose();
        slot1.Dispose();
        slot2.Dispose();
        NetwPromise result =
            NetwPromise.Adopt(
                NetwApi.Retained(
                    VariantUtils.ConvertToGodotObjectPtr(answered)));
        answered.Dispose();
        return result;
    }

    private static readonly IntPtr _bindChangeSceneToPacked =
        NetwApi.MethodBind("Netw", "change_scene_to_packed", 1459653292UL);

    /// <summary>
    /// The same change as <see cref="Netw.ChangeSceneToFile"/>, from a
    /// <see cref="PackedScene"/> that came from a file. A
    /// <see cref="PackedScene"/> built in memory is rejected.
    /// </summary>
    public static NetwPromise ChangeSceneToPacked(Node node, PackedScene packed, Netw.SceneChange scope =
        (Netw.SceneChange)0)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr slot1 = packed?.NativeInstance ?? IntPtr.Zero;
        long slot2 = (long)scope;
        IntPtr answered = default;
        NetwThunks.Ptrcall3_IntPtr_IntPtr_Long_IntPtr(
            _bindChangeSceneToPacked,
            IntPtr.Zero,
            in slot0,
            in slot1,
            in slot2,
            ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindReloadCurrentScene =
        NetwApi.MethodBind("Netw", "reload_current_scene", 1539982598UL);

    /// <summary>
    /// Reloads the scene this peer displays, like
    /// <see cref="SceneTree.ReloadCurrentScene"/>.
    /// </summary>
    public static NetwPromise ReloadCurrentScene(Node node, Netw.SceneChange scope =
        (Netw.SceneChange)0)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        long slot1 = (long)scope;
        IntPtr answered = default;
        NetwThunks.Ptrcall2_IntPtr_Long_IntPtr(
            _bindReloadCurrentScene,
            IntPtr.Zero,
            in slot0,
            in slot1,
            ref answered);
        return NetwPromise.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureMultiplayerScene =
        NetwApi.MethodBind("Netw", "configure_multiplayer_scene", 3354192785UL);

    /// <summary>
    /// Makes <paramref name="node"/> a multiplayer scene. Players only see its
    /// children while they are in it.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_multiplayer_scene(self).labeled(&amp;"Arena")
    /// </code>
    /// </summary>
    public static NetwSceneConfig ConfigureMultiplayerScene(Node node)
    {
        IntPtr slot0 = node?.NativeInstance ?? IntPtr.Zero;
        IntPtr answered = default;
        NetwThunks.Ptrcall1_IntPtr_IntPtr(
            _bindConfigureMultiplayerScene,
            IntPtr.Zero,
            in slot0,
            ref answered);
        return NetwSceneConfig.Adopt(answered);
    }

    private static readonly IntPtr _bindConfigureSceneRequests =
        NetwApi.MethodBind("Netw", "configure_scene_requests", 2275419960UL);

    /// <summary>
    /// Lets clients request a scene change. <paramref name="handler"/> runs on
    /// the server for every request and returns <c>@GlobalScope.OK</c> to allow
    /// it.
    /// <code>
    /// func _init() -&gt; void:
    ///     Netw.configure_scene_requests(authorize_scene_request)
    ///
    /// func authorize_scene_request(
    ///     player: NetwPlayer,
    ///     destination: String,
    ///     scope: Netw.SceneChange
    /// ) -&gt; Error:
    ///     if scope != Netw.SCENE_CHANGE_PLAYER:
    ///         return ERR_UNAUTHORIZED
    ///     return OK if unlocked(player, destination) else ERR_UNAUTHORIZED
    /// </code>
    /// </summary>
    public static Error ConfigureSceneRequests(Callable handler)
    {
        godot_variant slot0 = VariantUtils.CreateFromCallable(handler);
        godot_variant answered = default;
        NetwThunks.Call1(
            _bindConfigureSceneRequests,
            IntPtr.Zero,
            in slot0,
            ref answered);
        slot0.Dispose();
        Error result = (Error)VariantUtils.ConvertToInt64(answered);
        answered.Dispose();
        return result;
    }
}
