#include "netw/api/predict.hpp"

#include "godot/class_db.hpp"

using namespace godot;

namespace netw {

void NetwPredict::_bind_methods() {
    BIND_CONSTANT(ACK_AGE_MAX);

    BIND_ENUM_CONSTANT(CONTACT_CLASS_NONE);
    BIND_ENUM_CONSTANT(CONTACT_CLASS_DECLARED_SUPPORT);
    BIND_ENUM_CONSTANT(CONTACT_CLASS_OTHER_STATIC);
    BIND_ENUM_CONSTANT(CONTACT_CLASS_PREDICTED_DYNAMIC);
    BIND_ENUM_CONSTANT(CONTACT_CLASS_UNPREDICTED_DYNAMIC);
    BIND_ENUM_CONSTANT(CONTACT_CLASS_KINEMATIC_PROXY);

    BIND_ENUM_CONSTANT(COMMAND_ORIGIN_PREDICTED);
    BIND_ENUM_CONSTANT(COMMAND_ORIGIN_RELAYED);

    BIND_ENUM_CONSTANT(DRIVE_KIND_NONE);
    BIND_ENUM_CONSTANT(DRIVE_KIND_FRESH);
    BIND_ENUM_CONSTANT(DRIVE_KIND_REPEAT);
    BIND_ENUM_CONSTANT(DRIVE_KIND_HOLD);
    BIND_ENUM_CONSTANT(DRIVE_KIND_STARVED);
    BIND_ENUM_CONSTANT(DRIVE_KIND_FOLD_DRIVE);
    BIND_ENUM_CONSTANT(DRIVE_KIND_MISSING);
    BIND_ENUM_CONSTANT(DRIVE_KIND_SUBSTITUTED);

    BIND_ENUM_CONSTANT(TRIGGER_SHAPE_NONE);
    BIND_ENUM_CONSTANT(TRIGGER_SHAPE_MIXED);
    BIND_ENUM_CONSTANT(TRIGGER_SHAPE_ALL_WITHHELD);

    BIND_ENUM_CONSTANT(CONSUME_ACTION_REPLAY);
    BIND_ENUM_CONSTANT(CONSUME_ACTION_HOLD);
    BIND_ENUM_CONSTANT(CONSUME_ACTION_STARVED);

    BIND_ENUM_CONSTANT(EXACT_VERDICT_UNJUDGED);
    BIND_ENUM_CONSTANT(EXACT_VERDICT_EQUAL);
    BIND_ENUM_CONSTANT(EXACT_VERDICT_UNEQUAL);

    BIND_ENUM_CONSTANT(MISSING_INPUT_STALL);
    BIND_ENUM_CONSTANT(MISSING_INPUT_REPEAT_LAST);

    BIND_ENUM_CONSTANT(ARCHETYPE_NONE);
    BIND_ENUM_CONSTANT(ARCHETYPE_SCRIPTED);
    BIND_ENUM_CONSTANT(ARCHETYPE_SOLVER_BODY);

    BIND_ENUM_CONSTANT(RECOVERY_POLICY_REBASE_REPLAY);
    BIND_ENUM_CONSTANT(RECOVERY_POLICY_REBASE_RECOVER);
    BIND_ENUM_CONSTANT(RECOVERY_POLICY_DELAY_CLOSED);
    BIND_ENUM_CONSTANT(RECOVERY_POLICY_OBSERVE);
    BIND_ENUM_CONSTANT(RECOVERY_POLICY_AUTO);

    BIND_ENUM_CONSTANT(RECONCILE_INDEPENDENT);
    BIND_ENUM_CONSTANT(RECONCILE_JOINT);

    BIND_ENUM_CONSTANT(BREACH_RESPONSE_PREDICT_THROUGH);
    BIND_ENUM_CONSTANT(BREACH_RESPONSE_DEMOTE);

    BIND_ENUM_CONSTANT(EPISODE_STATE_OPEN);
    BIND_ENUM_CONSTANT(EPISODE_STATE_CLOSED);
    BIND_ENUM_CONSTANT(EPISODE_STATE_FALLBACK);

    BIND_ENUM_CONSTANT(OPERATOR_OUTCOME_PENDING);
    BIND_ENUM_CONSTANT(OPERATOR_OUTCOME_CONTRACTED);
    BIND_ENUM_CONSTANT(OPERATOR_OUTCOME_FAILED_TO_CONTRACT);
    BIND_ENUM_CONSTANT(OPERATOR_OUTCOME_INTRODUCED_BOUNDARY);
    BIND_ENUM_CONSTANT(OPERATOR_OUTCOME_WITHHELD);

    BIND_ENUM_CONSTANT(ATTRIBUTION_UNKNOWN);
    BIND_ENUM_CONSTANT(ATTRIBUTION_PRE_STATE);
    BIND_ENUM_CONSTANT(ATTRIBUTION_COMMAND);
    BIND_ENUM_CONSTANT(ATTRIBUTION_ENVIRONMENT);
    BIND_ENUM_CONSTANT(ATTRIBUTION_TOPOLOGY);
    BIND_ENUM_CONSTANT(ATTRIBUTION_EXECUTION);
    BIND_ENUM_CONSTANT(ATTRIBUTION_CONTACT);
    BIND_ENUM_CONSTANT(ATTRIBUTION_CLOSURE);

    BIND_ENUM_CONSTANT(OPERATOR_NONE);
    BIND_ENUM_CONSTANT(OPERATOR_REBASE_PROJECTED);
    BIND_ENUM_CONSTANT(OPERATOR_REBASE_EXACT);
    BIND_ENUM_CONSTANT(OPERATOR_FULL_CLOSURE);
    BIND_ENUM_CONSTANT(OPERATOR_TRANSPORT_DELTA);
    BIND_ENUM_CONSTANT(OPERATOR_RESEED);
    BIND_ENUM_CONSTANT(OPERATOR_RESEED_ALIGN);
    BIND_ENUM_CONSTANT(OPERATOR_DEMOTE);
    BIND_ENUM_CONSTANT(OPERATOR_DISSIPATE);
    BIND_ENUM_CONSTANT(OPERATOR_JOINT_REBASE);

    BIND_ENUM_CONSTANT(DOMAIN_IN);
    BIND_ENUM_CONSTANT(DOMAIN_OUT);
}

} // namespace netw
