#pragma once

#define NETW_SESSION_STAT_TABLE(X) \
    X(DROPS_UNKNOWN_ROUTE, "drops_unknown_route") \
    X(DROPS_NOT_LIVE, "drops_not_live") \
    X(DROPS_NO_NODE, "drops_no_node") \
    X(DROPS_BACKLOG_LIMIT, "drops_backlog_limit") \
    X(DROPS_TRAVERSAL, "drops_traversal") \
    X(DROPS_COMP_UNRESOLVED, "drops_comp_unresolved") \
    X(SENDS_DROPPED_UNROUTABLE, "sends_dropped_unroutable") \
    X(SENDS_DROPPED_NOT_LIVE, "sends_dropped_not_live") \
    X(SYNC_DROPS_STALE, "sync_drops_stale") \
    X(DERIVED_SETS_ACTIVE, "derived_sets_active") \
    X(DERIVED_FRAMES_IN, "derived_frames_in") \
    X(DROPS_DERIVED_NO_SET, "drops_derived_no_set") \
    X(DROPS_DERIVED_BAD_SENDER, "drops_derived_bad_sender") \
    X(DROPS_DERIVED_SCHEMA, "drops_derived_schema") \
    X(ROW_FRAMES_OUT, "row_frames_out") \
    X(ROW_FRAMES_FULL, "row_frames_full") \
    X(ROW_FRAMES_STAGE_REFUSED, "row_frames_stage_refused") \
    X(ROW_FRAMES_UNGATHERED, "row_frames_ungathered") \
    X(RETAINED_FRAMES_OUT, "retained_frames_out") \
    X(WINDOW_FRAMES_OUT, "window_frames_out") \
    X(WINDOW_SAMPLES_OUT, "window_samples_out") \
    X(SYNC_SETS_ACTIVE, "sync_sets_active") \
    X(SYNC_FRAMES_OUT, "sync_frames_out") \
    X(SYNC_FRAMES_IN, "sync_frames_in") \
    X(DELTA_FRAMES_OUT, "delta_frames_out") \
    X(DELTA_FRAMES_IN, "delta_frames_in") \
    X(DROPS_SYNC_NO_SET, "drops_sync_no_set") \
    X(DROPS_SYNC_BAD_SENDER, "drops_sync_bad_sender") \
    X(DROPS_SYNC_POISONED, "drops_sync_poisoned") \
    X(DROPS_SYNC_UNKNOWN_FLAG, "drops_sync_unknown_flag") \
    X(SPAWN_BOOK_ARMED, "spawn_book_armed") \
    X(SPAWN_BOOK_SPAWNED, "spawn_book_spawned") \
    X(SPAWN_BOOK_RECV, "spawn_book_recv") \
    X(SENT_PACKETS, "sent_packets") \
    X(SENT_BYTES, "sent_bytes") \
    X(RECEIVED_PACKETS, "received_packets") \
    X(RECEIVED_BYTES, "received_bytes") \
    X(STATE_ACKS_OUT, "state_acks_out") \
    X(STATE_ACKS_IN, "state_acks_in") \
    X(STANDALONE_ACKS_OUT, "standalone_acks_out") \
    X(PENDING_LIVE, "pending_live") \
    X(INTEREST_LAYERS, "interest_layers") \
    X(INTEREST_ENTITIES_FILTERED, "interest_entities_filtered") \
    X(INTEREST_VISIBLE_EDGES, "interest_visible_edges") \
    X(INTEREST_DIRTY_ENTITIES, "interest_dirty_entities") \
    X(INTEREST_RELAY_BACKLOG, "interest_relay_backlog") \
    X(INTEREST_TRANSITIONS_TOTAL, "interest_transitions_total") \
    X(PREDICT_ENTITIES, "predict_entities") \
    X(PREDICT_TIMELINES, "predict_timelines") \
    X(PREDICT_CORRECTIONS, "predict_corrections") \
    X(PREDICT_MAX_REPLAY_DEPTH, "predict_max_replay_depth") \
    X(PREDICT_CONSUMED, "predict_consumed") \
    X(PREDICT_MISSING, "predict_missing") \
    X(PREDICT_PENDING_ACTIONS, "predict_pending_actions") \
    X(PREDICT_EFFECTS_ARMED, "predict_effects_armed") \
    X(PREDICT_GATE_FALLBACKS, "predict_gate_fallbacks") \
    X(DISPLAY_RUNTIMES, "display_runtimes") \
    X(DISPLAY_STARVING, "display_starving") \
    X(DISPLAY_SLEEPING, "display_sleeping") \
    X(DISPLAY_PROJECTING, "display_projecting") \
    X(DISPLAY_SNAPS, "display_snaps") \
    X(DISPLAY_MAX_DISPLAY_LAG, "display_max_display_lag") \
    X(DISPLAY_MAX_FORECAST_AGE, "display_max_forecast_age") \
    X(VERDICT_DOES_NOT_EXIST, "verdict_does_not_exist") \
    X(VERDICT_SKIP, "verdict_skip") \
    X(VERDICT_UNAVAILABLE, "verdict_unavailable") \
    X(VERDICT_UNAUTHORIZED, "verdict_unauthorized") \
    X(VERDICT_INVALID_DATA, "verdict_invalid_data") \
    X(VERDICT_BUSY, "verdict_busy") \
    X(DROPS_TABLE_UNKNOWN, "drops_table_unknown") \
    X(DROPS_TABLE_SCHEMA, "drops_table_schema") \
    X(DROPS_TABLE_UNKNOWN_FLAG, "drops_table_unknown_flag") \
    X(DROPS_TABLE_TRUNCATED, "drops_table_truncated") \
    X(DROPS_TABLE_BAD_SENDER, "drops_table_bad_sender") \
    X(TABLE_DROPS_STALE, "table_drops_stale") \
    X(TABLE_DROPS_TOMBSTONE, "table_drops_tombstone") \
    X(TABLE_DROPS_STALE_ROW, "table_drops_stale_row") \
    X(SYNC_PUMP_SKIPS_INVALID_NODE, "sync_pump_skips_invalid_node") \
    X(SYNC_PUMP_SKIPS_NO_ENTITY, "sync_pump_skips_no_entity") \
    X(SYNC_PUMP_SKIPS_NO_ROUTE, "sync_pump_skips_no_route") \
    X(SYNC_PUMP_SKIPS_NOT_AUTHOR, "sync_pump_skips_not_author") \
    X(SYNC_PUMP_SKIPS_NO_RECIPIENTS, "sync_pump_skips_no_recipients") \
    X(INTEREST_VANISHED_DIRTY_SKIPS, "interest_vanished_dirty_skips") \
    X(JOINT_PASSES, "joint_passes") \
    X(JOINT_MEMBERS, "joint_members") \
    X(JOINT_CELLS_RELAYED, "joint_cells_relayed") \
    X(JOINT_CELLS_SUBSTITUTED, "joint_cells_substituted") \
    X(JOINT_HEAL_SNAPS, "joint_heal_snaps") \
    X(JOINT_LINGER_HELD, "joint_linger_held") \
    X(DROPS_LINGERING_ROUTE, "drops_lingering_route") \
    X(DROPS_DEAD_ROUTE, "drops_dead_route") \
    X(ATTRIBUTED_BYTES_OUT, "attributed_bytes_out") \
    X(ATTRIBUTED_BYTES_IN, "attributed_bytes_in") \
    X(ATTRIBUTED_FRAMES_OUT, "attributed_frames_out") \
    X(ATTRIBUTED_FRAMES_IN, "attributed_frames_in") \
    X(ATTRIBUTION_FRAMING_OUT, "attribution_framing_out") \
    X(ATTRIBUTION_DROPPED_OUT, "attribution_dropped_out")
